### ISSUE TITLE
Improve SentinelAPI.query interface

### ISSUE THREAD

**Issue by j08lue** [sentinelsat/sentinelsat#101]
When using `SentinelAPI` from a scripts, I found it a bit tricky to figure out what to provide to the `SentinelAPI.query` function:

1. `area` - this needs to be a string of coordinates formatted in a special way. We have a function for reading a geojson file ([`get_coordinates`](https://github.com/ibamacsr/sentinelsat/blob/v0.9.1/sentinelsat/sentinel.py#L425)). But it includes both, **reading** the geojson file and **formatting** the string. I suggest to separate the two steps, so users can use the formatting function on its own with a coordinates sequence e.g. from `fiona` or some other source of geojson-like information.
2. `initial_date` and `end_date` - we parse these with [`_format_date`](https://github.com/ibamacsr/sentinelsat/blob/v0.9.1/sentinelsat/sentinel.py#L472) but that function **does not fail** when receiving some invalid input but just passes it on. I think fail it should.

The error the user gets from mistakes in the formats is some very very cryptic `SentinelAPIError` with lots Java traceback information from COAHub, because the query payload *is* generated but invalid. Very hard to figure out what went wrong.

Regarding the `area` parameter, we could also consider to do the string formatting **inside** the `query` function. Then the user just has to provide a (well-defined) geojson `coordinates` sequence. Would you support this, @willemarcel, @Fernerkundung and @valgur?

**Comment by j08lue** [comment]
I see now that there was a **meaning** with `_format_date` passing values: The Open Access Hub supports things like `NOW` and `NOW-1DAY`. Some of these are listed in the [Open Access Hub query examples](https://scihub.copernicus.eu/twiki/do/view/SciHubUserGuide/5APIsAndBatchScripting#Open_Search_Queries_examples).

What should we do? Should we 

1. continue to pass (potentially invalid) values on
2. somehow validate non-date strings (e.g. `in_date.startswith('NOW')`) (and document which we allow)
3. or just not allow these special strings in our API, but only date strings and python dates?

**Comment by j08lue** [comment]
Here is an implementation of the above suggestions:

1. Separate `format_coordinates_string` function for `area` parameter
2. Non-date strings are supported that fulfil `.startswith(`NOW`)`.

https://github.com/ibamacsr/sentinelsat/compare/master...DHI-GRAS:master

**Comment by valgur** [comment]
These relative date values (`NOW`, etc.) seem easy enough to validate with a regex, so I support doing that. 

I was not actually aware that the OpenSearch API supports relative dates like that. Knowing this, I suggest also changing the default `initial_date` value in `.query()` to `NOW-1DAY` instead of `None`. That way the `None` value could be used as one might expect: to leave the initial date unset in the query.

**Comment by valgur** [comment]
Regarding the handling of `area`, I would modify `.query()` to take WKT-formatted features as input and adjust the `.get_coordinates()` and `.get_product_odata()` accordingly.
Currently `.get_coordinates()` returns a string that is *almost* WKT but is missing the `POLYGON((...))` around it. I think taking WKT as the input is both the most logical and convenient option. E.g. if you have `shapely` features, then you can simply do `feature.wkt` to get a proper input value.

**Comment by j08lue** [comment]
> That way the None value could be used as one might expect: to leave the initial date unset in the query.

Good idea.

> I would modify .query() to take a WKT-formatted feature as input

WKT is a good suggestion. However, without `shapely`, there is no automated way of getting from the parsed geojson to `POLYGON((...))`. But the parameter type would be better defined and if `get_coordinates` does not work for the user (e.g. providing `MultiPolygon` or so), they can always use `shapely` or so in between.

**Comment by Fernerkundung** [comment]
Great changes all around. :+1: 

I also support splitting `get_coordinates` into 'read geojson file' and 'format geojson polygon to WKT' functionality. This would ensure that users could use existing GeoJSON features with something like `.query(area=format_geojson(<geoJSON feature>,...`

**Comment by Fernerkundung** [comment]
@j08lue Can this issue be closed? I think all proposed changes are included as of `v0.10` or did I miss something?

**Comment by j08lue** [comment]
@Fernerkundung Yes, sorry I was sleeping here...
