### ISSUE TITLE
Slow download

### ISSUE THREAD

**Issue by g-roc** [sentinelsat/sentinelsat#103]
Hi all,

I am a new sentinelsat user. Since I started using sentinelsat I have never experienced a download speed greater than 2 Kb/s, usually around 500 b/s.  The same occurs with different internet connetions. The server could be limiting the download speed, but it seems to be to extreme. Is it normal? 
Thanks in advance.

**Comment by Fernerkundung** [comment]
This is definitely out of the ordinary download speeds.

- What version of `sentinelsat` and Python are you using and on which OS?

- Do you encounter the same speeds when using a direct download link such as: https://scihub.copernicus.eu/dhus/odata/v1/Products('9a1bc72d-6ba4-4c2d-8611-dc110d24c953')/$value

- Can you test if the slow speed occurs when using `curl`? This might be an issue of your system/firewall throttling connections through `curl`

- What do you mean by 'different internet connections'? I guess the error is persistent with your laptop?

**Comment by valgur** [comment]
You might want to also take a look at what's inside the (incomplete) files you have downloaded in this manner. Is the content binary or is the server perhaps sending error messages as the content?

**Comment by g-roc** [comment]
Thanks @Fernerkundung  and @valgur for the quick answear.

- My OS is a Windows 8.1 - 64 bits and I am using Python 2.7.13 and `sentinelsat-0.8.1`. 

- Using a link download, like the one @Fernerkundung has mentioned, the download speed ranges between 150-200 Kb/s.

- As suggested I have tried to perform a test using `curl` (script below), but I have got any success.
`import pycurl` 
`path = '~sentinel2/'`
`url = "https://scihub.copernicus.eu/dhus/odata/v1/Products('9a1bc72d-6ba4-4c2d-8611-dc110d24c953')/$value"`
`c = pycurl.Curl()`
`c.setopt(c.URL, url)`
`c.setopt(c.USERPWD, 'user:password')`
`c.setopt(c.WRITEDATA, path)`
`c.perform()`
I attempted to download with the firewall turned off and the download speed was the same.

- I mean that I have tested the speed download connected in different locations (personal internet, work internet, ...) and the download speed was the same. Even using another computer - Windowns 7 - 32 bits, Python 2.7.13 and `sentinelsat-0.8.1` - the problem persistis.

- When the incomplete file is opened it seems to be 'regular', containing some of the expected folders. Looks like the download was running properly, aside the slow speed.

**Comment by Fernerkundung** [comment]
> I mean that I have tested the speed download connected in different locations (personal internet, work internet, ...) and the download speed was the same. Even using another computer - Windowns 7 - 32 bits, Python 2.7.13 and sentinelsat-0.8.1 - the problem persistis.

So the only constants not changed are the version `0.8.1` and your user account, right?

You could try upgrading `sentinelsat`, but this shouldn't affect the speed. Only ideas for causes I have left are an issue with `(py)curl` or that somehow ESA throttles your speed based on your login credentials, with the first one being more likely.

What is the download speed if you download a file directly through your browser, also in the 150-200 Kb/s range?

**Comment by g-roc** [comment]
That is rigth. Now `sentinelsat` is up to date and the issue persists. 

I will test `(py)curl` again and give a feedback if something changes.

Yes, the speed through the browser is also around 150-200 kb/s. One thing that I have not mentioned is that when the download starts the speed is 'normal' and then gradually decreases till 500 b/s.

**Comment by Fernerkundung** [comment]
@g-roc Do you still encounter those slow download speeds?

**Comment by g-roc** [comment]
@Fernerkundung , sorry for the delay. Yes, still the same problem.

**Comment by Fernerkundung** [comment]
Also with the new `v0.11` version? In the newest version the download functionality was refactored and does not depend on `curl`. If the slow speeds persist that only leaves your connection or PC as source of the issue.

**Comment by g-roc** [comment]
Working fine with version `v0.11` . Awesome! Thanks for the support.

**Comment by valgur** [comment]
Glad to hear that. Thanks for letting us know.

**Comment by Santiago-Peraza** [comment]
Hi, thanks for this information. I have a same problem. 
I downloaded from url with browser with download rate of 100 -200 kB. 
what is the correct way to download to reduce download time?
