### ISSUE TITLE
Release/versioning strategy

### ISSUE THREAD

**Issue by Fernerkundung** [sentinelsat/sentinelsat#118]
What should our versioning and release strategy be?

I would follow @valgur suggestion and propose we try to follow [semantic versioning](http://semver.org/). 

I'd also suggest that we merge PRs without creating a new release for every PR. The next important question then would be: How many PRs constitute a new release? Are there any hard and fast rules we can/should follow?

@willemarcel gave me rights to publish new releases on PyPi. I can manage to do that but this is the first project where I would be responsible for this. If anyone feels more qualified and would like to do that I'm happy to transfer that role. This would also entail being responsible for managing the Github releases.

**Comment by valgur** [comment]
Indeed, let's use semantic versioning.

Agreed, it's not a good idea to create a release for every merged PR. A solution might be to

1. Make sure we have a separate issue for each potential improvement or bug that needs fixing, assign a milestone for each. E.g. `0.10.1`, `0.11`, `1.0`, `someday`, `won't fix`. [pandas' milestones](https://github.com/pandas-dev/pandas/milestones) are a good example.
2. If all issues belonging to a milestone are resolved, then ship the release.

Regarding publishing of the releases, I don't think I'm more qualified than @Fernerkundung, but I can take care of this if you prefer not to.

**Comment by j08lue** [comment]
OK and happy if either of you takes care of PyPi.

**Comment by valgur** [comment]
Oops, fat fingers. Sorry!

**Comment by Fernerkundung** [comment]
Good suggestions, I'll try to copy the milestones pandas and rasterio use in the next days and then we have a clear expectation what goes into which release.

Up to `v.1.0` I propose that we adapt semantic versioning to `None.Major.MinorAndPatch` as we can expect a number of backwards incompatible changes occuring up to this milestone.
