### ISSUE TITLE
Logo / Avatar

### ISSUE THREAD

**Issue by kr-stn** [sentinelsat/sentinelsat#124]
After we moved to an organization we can select a logor or avatar to represent `sentinelsat`.

The current placeholder is the [WikiMedia satellite icon](https://www.google.de/imgres?imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F2%2F27%2FFP_Satellite_icon.svg%2F1024px-FP_Satellite_icon.svg.png&imgrefurl=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AFP_Satellite_icon.svg&docid=1DokCmEGV5THoM&tbnid=AHwUxoDwwdNUmM%3A&vet=10ahUKEwiA4_zw8qPUAhUPZlAKHRoAB3sQMwg4KAIwAg..i&w=1024&h=1024&safe=off&bih=1050&biw=1713&q=satellite%20icon&ved=0ahUKEwiA4_zw8qPUAhUPZlAKHRoAB3sQMwg4KAIwAg&iact=mrc&uact=8).

Any suggestions/ideas for a more fitting logo, that is preferrably CC licensed?

**Comment by LeptoSpira** [comment]
Possible suggestion, you can use icons from here: https://icons8.com/icons/set/satellite
