### ISSUE TITLE
Method to checksum existing products

### ISSUE THREAD

**Issue by valgur** [sentinelsat/sentinelsat#128]
#126 removes the `check_existing` option from `download()` and `download_all()`, as it is quite unrelated to the main purpose of these functions. The main use case for that feature was to check the integrity of already downloaded files, which is potentially quite useful.

There are a couple of options regarding this feature:
* Add a separate method for this (`checksum()`?) functionality. Its input could be a list of product ids and a directory or a list of file paths.
* Not implement this at all. The zip files can be verified quite easily with `zip -T` or `7z t` commands or via a GUI.
* Re-add it to `download()`. Since you are likely interested in fixing the broken files rather than just deleting them, `download()` is actually a quite sensible place for this functionality.

The consensus so far in #126 was to make it a separate function.

**Comment by Fernerkundung** [comment]
From a design perspective I would expect such a function to work with the following use cases:
- call with a folder of downloaded files (using the filenames as reference)
- list of product IDs and corresponding folder of files or list of files
- full OData dictionary and corresponding folder of files or list of files

**Comment by j08lue** [comment]
If this becomes a full-fledged function, maybe we should not collapse the CLI into one command (`sentinelsat`) anyways but keep it a group with sub-commands?

**Comment by Fernerkundung** [comment]
I don't think every option the API offers has to be exposed to the CLI which is supposed to be a user friendly way to use the API. If we include every option it becomes too convoluted.

That being said, we still include the most common use cases, so I'd say still merge it and include a flag like `--checksum` that takes all query elements and checks the integrity of downloaded files. In turn I would remove the `--no-md5` option proposed in #129 and just use the default API behaviour for the CLI.

**Comment by valgur** [comment]
Resolved by #133.
