### ISSUE TITLE
Make checksumming of downloaded products the default behavior

### ISSUE THREAD

**Issue by valgur** [sentinelsat/sentinelsat#129]
It is a good practice to verify the integrity of downloaded products and it makes sense to do it by default.
So, let's set `checksum` to `True` in `download()` and `download_all()` and change `--md5` to `--no-md5` in the CLI.
This is a backwards-incompatible change, so we probably want to do implement it in a release that bundles other such changes.

**Comment by Fernerkundung** [comment]
I propose to remove or repurpose the `--md5` flag and just use the default API behaviour for every download, otherwise the CLI might become too convoluted if we include every option.

**Comment by valgur** [comment]
Good point, I agree @Fernerkundung.

**Comment by gkeller2** [comment]
Hi. If you are still interested in having this code change done, I can take a pass at it.

**Comment by Fernerkundung** [comment]
@gkeller2 please do :+1:
