### ISSUE TITLE
Search Sentinel 2 by tile

### ISSUE THREAD

**Issue by j08lue** [sentinelsat/sentinelsat#140]
Currently, you have to provide an area of interest for `sentinelsat`. But I often know exactly which tile(s) I am interested in. It would be awesome to have a function to download specific tiles, like [`sentinelhub`](https://github.com/sinergise/sentinelhub) has.

As far as I can see, DHuS unfortunately does not have a high-level function to search by tile (see their [Full Text Search](https://scihub.copernicus.eu/userguide/3FullTextSearch) docs).

But you can search for the tile ID in the file name, like `filename:*_TDDABC_*` which however will only work for the [post-2016 single-tile product format](https://earth.esa.int/web/sentinel/user-guides/sentinel-2-msi/naming-convention).

NB: For some reason, combining several `filename` patterns with `OR` like `filename:*_T32UPF_* OR filename:*_T32UMF_*` only returns results for the last tile and `filename:(*_T32UPF_* OR *_T32UMF_*)` does not work at all.

What do you think, should we add a high-level function to the CLI / API to search by tile? It could create the `filename` search pattern and perhaps run several queries when several tiles are provided - unless there is a better way with DHuS that I did not see...

**Comment by Fernerkundung** [comment]
Good idea and should be reasonably easy to implement.

>  search for the tile ID in the file name, like filename:*_TDDABC_* which however will only work for the post-2016 single-tile product format.

Downloading pre-single-tile products is another beast entirely. You can access the tiles in the old format as sub-datasets, like [`sentinel-download`](https://github.com/olivierhagolle/Sentinel-download) does. However, this is then missing some metadata necessary for Sen2Cor and other pre-processing software.

I would propose that we implement this function only for datasets available as single-tile products on the DHuS endpoint. For the CLI this would then be a `-t, --tile` option that requires no area GeoJSON/WKT (which could be made optional as dicussed in #115)?

**Comment by pidancier** [comment]
Instead of filtering filename, a more efficient solution may consist in querying the MGRS formatted Tile id with the syntax ```tileid:32UPF``` (without starting 'T').

**Comment by j08lue** [comment]
> a more efficient solution may consist in querying the MGRS formatted Tile id with the syntax tileid:32UPF (without starting 'T').

Excellent, @pidancier, I did not know that existed. But still no `OR` functionality (e.g. `tileid:32UMF OR tileid:32UPF`).

I will make a PR.

**Comment by j08lue** [comment]
Hmm. Thinking more about this, I am actually hesitating a bit:

1. A `--tile` option would be only for Sentinel 2. Apart from `--cloud`, we have no instrument-specific options and `--cloud` at least works for both Sentinel 2 and 3.
1. If we only permit one `--tile`, there is really not much added convenience compared to `--query 'tileid=32UPF'`. But if we permit multiple `--tile` flags, that would require a not so pretty change to our call to `api.query` [inside the CLI function](https://github.com/sentinelsat/sentinelsat/blob/6797f0a2b60d973f0c5a246813a852636ec4a5c1/sentinelsat/scripts/cli.py#L132) - we would have to call it `len(tile)` times, but only if `tile` is specified...

So maybe Sentinel 2 tile query/download should just be covered as examples in the docs?

Or is it relevant enough to make compromises for it?

**Comment by Fernerkundung** [comment]
Your making good points. After giving it some more thought I'd also say:

> Sentinel 2 tile query/download should just be covered as examples in the docs

This might also be a good starting point for "Examples" sub-sections in the CLI and API docs where we move the examples we already have and add more if deemed usefull.

**Comment by j08lue** [comment]
Weird. Queries by `tileid` seem to work only for data from 2017-03-31 onwards. Do you know anything about this, @pidancier?

SciHub keeps astonishing me. It is like H2G2's Italian restaurant...

**Comment by sotosoul** [comment]
Hi, it's been a while but I think I may have a workaround. Since no two tiles have the same XY centroid coordinates, I suggest that you use a dictionary that "translates" tile codes to their respective XY coordinates and use these coordinates in your query. You can extract the relevant data from the centroids shapefile found [here](https://github.com/justinelliotmeyers/Sentinel-2-Shapefile-Index).

**Comment by j08lue** [comment]
> Since no two tiles have the same XY centroid coordinates

Not the same, but there is quite some overlap between tiles of adjacent UTM zones, so your queries by tile centroid will return different tiles in those areas.

**Comment by sotosoul** [comment]
Oh yes, good point. Scratch what I wrote

**Comment by GGA557** [comment]
How can I use this tileid argument? I don't see it in the docs but I saw some code that has to do with this merged on 2017.
