### ISSUE TITLE
Access the latest information available

### ISSUE THREAD

**Issue by viogp** [sentinelsat/sentinelsat#144]
Hi,

I'm trying to get the latest data for a given region. If I specify a date, following your example, I do get values:
```
products = api.query(footprint,
                     '20170703',
                     platformname = 'Sentinel-2')
```
The first question I have is: which type of date is the above referring to? I tried using the 'date(2017,07,03)' but it didn't work.

Because I'd like to access the most recent data, I tried the following:
```
products = api.query(footprint,
                     beginposition = '[NOW-10DAY TO NOW]',
                     platformname = 'Sentinel-2')
```
The above gives me an error.

Maybe this questions are trivial, but I haven't found more specific tutorials or help pages to look at.

Thanks

**Comment by Fernerkundung** [comment]
There is an example for what you do in the documentation - specifically the [OpenSearch example](https://sentinelsat.readthedocs.io/en/v0.11/api.html#opensearch-example).

The docstring of `query` also lists the valid parameters. In your case you need to change `beginposition` to `initial_date`. Internally we format the search to `[<intitial_date> TO <end_date>]`. Therefore your query needs to look like this:

```python
products = api.query(footprint,
                     initial_date = 'NOW-10DAY',
                     end_date='NOW',
                     platformname = 'Sentinel-2')
```
