### ISSUE TITLE
Examples in Documentation

### ISSUE THREAD

**Issue by kr-stn** [sentinelsat/sentinelsat#146]
I propose that we create an example section in the Documentation for both the API and CLI. Possible contents are, but not limited to:

- [ ] most common use cases
- [ ] advanced use of geometries, wildcards, queries, order-by etc.
- [ ] unexpected behaviour by the Open Access Hub
- [ ] automated workflows

This is a beginner friendly issue. A good starting point would be #140 and then build from there.

For better integration with the documentation and as a starting point for new users I propose to create these as individual [Jupyter notebooks](https://github.com/jupyter/notebook). This would entail:
- [ ] integrate a folder of example notebooks into docs with [nbsphinx](http://nbsphinx.readthedocs.io/en/0.2.8/index.html)

**Comment by valgur** [comment]
Just an idea: we could add an [asciinema](https://asciinema.org/) video of a CLI session to our landing page for a good demo of the command line utility. It could perhaps consist of doing one or two queries and then adding a `--download` to it.

**Comment by Fernerkundung** [comment]
Good idea. One could also combine it with [doitlive](https://github.com/sloria/doitlive) for easier recording.

```bash
asciinema rec -c "doitlive play session.sh -q"
```

How to we get around the issue of plaintext password recording though?

**Comment by j08lue** [comment]
> How to we get around the issue of plaintext password recording though?

Create a dummy SciHub account and change the password right after the recording? Or we should make `.netrc` support reality now.

**Comment by amjack100** [comment]
Is the state of this issue pretty much the same as it was in 2017? Either way, I'd be happy to put some work into it. I've been looking for ways to enter the open source world and they say docs are a good way to start.

**Comment by j08lue** [comment]
> they say docs are a good way to start

Makes a lot of sense, if you are a user and can identify some shortcomings or misleading parts of the docs. Or even spelling errors.

So if you have used the library and can identify a basic use case, it would be awesome to get a write-up for that and kick off some iterations on the scope and format of the examples.

**Comment by amjack100** [comment]
Example notebooks are in progress. In the meantime I also put together a minimal example of what @valgur suggested and thought I'd put it here for feedback. Would a clip with two queries and a `--download` be ideal?

https://user-images.githubusercontent.com/46258320/128516270-53991c35-1e4b-44f4-a40e-006c80e2acc0.mp4

**Comment by amjack100** [comment]
Ok, example notebooks are in progress. I also wanted to post a quick clip I made based on @valgur 's suggestion. This is just a minimal example and any feedback would be helpful - would it still be ideal to show two queries and then a `--download`?

![Query](https://raw.githubusercontent.com/amjack100/usercontent/master/query1.svg)

**Comment by j08lue** [comment]
> would it still be ideal to show two queries and then a `--download`?

Sounds good to me! Maybe with an initial `--help`, too.

**Comment by amjack100** [comment]
[Here](https://colab.research.google.com/drive/1UwLb-79KcvMpiZ6w2ncygF4WWZM0flik?usp=sharing) is a rough draft for the first example. I did this one without an outline because it basically mimics the "getting started" part of the docs, just in an interactive way. I'm intending for this one to be the first of 4 suggested by @Fernerkundung in the first comment. My impression of this draft right now is that it still needs more bulk/content, but that could be because I've been looking at it for too long. Just let me know what it needs/doesn't need!
