### ISSUE TITLE
Under which license is Sentinelsat?

### ISSUE THREAD

**Issue by PhML** [sentinelsat/sentinelsat#147]
In setup.py and README.rst it is GPLv3+.

But the LICENSE file is AGPL.

Which information is the good one?

**Comment by Fernerkundung** [comment]
That's a good question. Originally `sentinelsat` was setup by @willemarcel with AGPL. In the current state references to GPLv3+ are errors.

This might be a good starting point to discuss if we should stick to AGPL or move to another license @willemarcel @j08lue @valgur?

**Comment by willemarcel** [comment]
@Fernerkundung I should have used GPLv3, but I think I copied the license file from another project and didn't notice it was AGPL. Is a message declaring that all the contributors agree with the change enough to move to GPLv3?

**Comment by Fernerkundung** [comment]
>  Is a message declaring that all the contributors agree with the change enough to move to GPLv3?

I don't see why not. We had mixed license information up to now anyway and the difference between AGPL and GPL is only triggered when it is run over a network.

So at the moment we are +2 for GPLv3. Are there other license suggestions or valid reasons not to switch from AGPL to GPLv3+?

**Comment by j08lue** [comment]
Another +1 for GPLv3.

**Comment by Fernerkundung** [comment]
Resolved with #148
