### ISSUE TITLE
Allow --name to take multiple inputs

### ISSUE THREAD

**Issue by valgur** [sentinelsat/sentinelsat#156]
The `--name` parameter could be fairly easily extended to take a list of product names as input. Perhaps as a comma separated list.

**Comment by Fernerkundung** [comment]
I support this idea. One thing we need to keep in mind when parsing the string is that users might use wildcards, which might look like so: `--name S1A*20160101*, S2A*SGS_*`

**Comment by j08lue** [comment]
> Perhaps as a comma separated list.

Maybe also as `multiple=True`, so you can do `--name S2A*20161101* --name S2B*20171001*`. Depends on the potential use pattern: if there will be many names, a comma-separated list is better.

**Comment by Fernerkundung** [comment]
Would it make sense to implement both? A comma is not a valid character for the product names, so implementing `multiple=True` as well as parsing should be doable.

I'd prefer we implement one obvious way. I'm leaning a bit towards @j08lue suggestion with multiples. If someone has a long list of filenames can we expect them to use the Python API instead? Or should we implement an option to read a list of names from a file like `wget -i`?

**Comment by j08lue** [comment]
Sorry, yes, my "also" was misleading. I meant "alternatively" and agree that there should be only one way.

Let us go with the commas.

NB: The string obviously cannot contain spaces and has to be in quotes if you have glob-like patterns.

**Comment by j08lue** [comment]
Are you going to make this one, @Fernerkundung?

**Comment by Fernerkundung** [comment]
@j08lue I'm still stuck working on the examples in whatever time I find. If you want to implement this please do! :)

**Comment by j08lue** [comment]
For anyone who wants to take this on (including future self): The solution we are after is that `--name` takes a comma-separated list of names.
