### ISSUE TITLE
Should CLI raise an error when search for uuid?

### ISSUE THREAD

**Issue by PhML** [sentinelsat/sentinelsat#157]
I was reading the code when I saw this line:
https://github.com/sentinelsat/sentinelsat/blob/a29508c62f54c4db74df6a32d10d7ee5d60037e4/sentinelsat/scripts/cli.py#L130
There is no else clause thus if the condition is not meet, the exception is silenced.
Is it on purpose?
Should not `api.get_product_odata` raise a kind of `SentinelProductIdError` that CLI would catch to print the error message?

**Comment by valgur** [comment]
I'm not the author of that bit of code but that was probably unintentional and is a bug. So thanks for pointing this out. Much appreciated!

Whether `get_product_odata()` should raise a distinct exception that is a subclass of `SentinelAPIError` is a good question. The `if 'Invalid key' in e.msg:` check is indeed more of a concern of `get_product_odata` better suited inside it.

Redesigning the taxonomy of exception classes is an open topic right now (#131) which I have intended to address at some point. This is a good addition to the changes proposed in that issue.
