### ISSUE TITLE
Include functionality to consume CopHub CSV catalogues?

### ISSUE THREAD

**Issue by Fernerkundung** [sentinelsat/sentinelsat#158]
As of 2017-09-04 the Copernicus Open Access Hub has published monthly CSV files containing all products published during that time and available through the CopHub ([source](https://scihub.copernicus.eu/userguide/6CatalogueViewInCSV)).

Is this something that should be consumeable by `sentinelsat` in addition to the search of the DHuS?

Currently they are structured as 1 CSV file per month containing the following metadata:

- ID | The Universally Unique Identifier (UUID) of the product 
- Name | The product filename 
- ContentLength | The size in bytes of the .ZIP file 
- IngestionDate | The date and time of the ingestion of the product in the data hub system 
- ContentDate:Start* | The sensing start date and time of the product 
- ContentDate:End* | The sensing stop date and time of the product 
- Checksum:Algorithm | The hash function name used by the Data Hub system
- Checksum:Value | Hash value 

Using these we might be able to query large amounts of data faster if the search area is exceptionally large (continents and larger). On the other hand, no geographic relation of the datasets is stored.

Currently I lean towards not including functionality to use these CSV datasets as I can see no advantage to the usage of `sentinelsat`. I would like to have a discussion about this, maybe it is useful for people ingesting larger amounts of data (such as @valgur ?).

**Comment by valgur** [comment]
The only situation where these CSVs might be beneficial is when you are downloading a significant portion of the product archive and don't care about newly-added products. It's not too obvious at what point running several OData queries becomes less efficient than downloading a 250 kB file for each day either.
So, I'd say this is very much outside the scope of `sentinelsat`.

**Comment by j08lue** [comment]
I agree that this is beyond our scope. But thanks for taking it up for discussion!
