### ISSUE TITLE
newbie question regarding path settings

### ISSUE THREAD

**Issue by DKorman** [sentinelsat/sentinelsat#160]
**This script is working okay, it prints all products within certain date range:**
```python
import sys
from sentinelsat.sentinel import SentinelAPI, read_geojson, geojson_to_wkt
api = SentinelAPI('<user>', '<password>', 'https://scihub.copernicus.eu/dhus')
args = sys.argv

footprint = geojson_to_wkt(read_geojson('Hrvatska_sentinel.geojson'))
products = api.query(footprint,
                     date = (args[1], args[2]),
                     platformname = 'Sentinel-2',
					 producttype = 'S2MSI2Ap',
                     cloudcoverpercentage = (0,99))

print(products)
api.download_all(products)
```
If anyone can help me, where exactly do i put this line: _path='E:/SUO-PUO/Ostalo/Sentinel/Snimke/Level-2A'_, in order to set the download path of the products?
So far i got only errors. 

Thank you very much and best regards,
Davor

*edit by @fernerkundung: removed login credentials*

**Comment by valgur** [comment]
Hi! You can specify the download directory with the second parameter of `.download_all()`. E.g.
```python
path = 'E:/SUO-PUO/Ostalo/Sentinel/Snimke/Level-2A'
api.download_all(products, path)
```
See the [docs](https://sentinelsat.readthedocs.io/en/v0.12/api.html#sentinelsat.SentinelAPI.download_all) for more information.

**Comment by valgur** [comment]
I'm closing the issue. If you have any follow-up or other questions feel free to ask them, though.
