### ISSUE TITLE
ReadTheDocs landing page: stable or master? 

### ISSUE THREAD

**Issue by Fernerkundung** [sentinelsat/sentinelsat#163]
Should the ReadThe Docs landing page default reflect the docs for the latest release or the master branch?

Current default is `stable`, which shows the latest release. Master can still be reached via the dedicated version url: http://sentinelsat.readthedocs.io/en/stable/

I'm asking because our RTD badge points to master. However, I think it should rather point to stable as I expect most users install `sentinelsat` via `pip` not `git clone`.

**Comment by valgur** [comment]
`stable` seems like a more reasonable choice. I doubt the vast majority of users bother to use the development version of `sentinelsat`.

**Comment by j08lue** [comment]
`stable`, yes.
