### ISSUE TITLE
Protect spaces in query values

### ISSUE THREAD

**Issue by PhML** [sentinelsat/sentinelsat#169]
I used Sentinelsat with https://coda.eumetsat.int/ (The Sentinel 3 Marine 
Copernicus Data Access) and the extra keyword `timeliness` which expects values with spaces like `Near Real Time`.
Unfortunately when Sentinelsat does the query, such values are not protected, leading to a query error response from the server.
I tried to modify Sentinelsat to surround each value with double quotes `"` in queries but it failed when values are range values like `[NOW-1DAY TO NOW]`. It also failed with `filename` keyword and an asterisk `*` in the value like `S3A_OL_2*`. I eventually added this condition in the `format_query` method:
```python
            if " " in value and not value.startswith("["):
                query_parts.append('{}:"{}"'.format(attr, value))
            else:
                query_parts.append('{}:{}'.format(attr, value))
```
Instead of just:
```python
            query_parts.append('{}:{}'.format(attr, value))
```
On queries I made, it worked but as I find it very strange that I can't use double quotes everywhere, I ask for a discussion on this behavior.

**Comment by valgur** [comment]
You raise a good issue, this opens a whole can of worms. 😄 

I dug into the Apache Lucene query syntax that the server uses ([here](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/query-dsl-query-string-query.html#query-string-syntax)'s a good reference). There are two ways spaces can be supported in keywords:
* Quotes: `timeliness:"Non Time Critical"`. This has the downside that queries like `identifier:"S1*"` and  `relativeorbitnumber:"[100 TO 120]"` will not work.
* Escaping: `timeliness:Non\ Time\ Critical`. This has the downside that we have to take care to not escape spaces that are used as part of the syntax, e.g. `relativeorbitnumber:[100 TO 120]`.
* Using parentheses (`timeliness:(Non Time Critical)`)  also seemingly works, but this is actually equivalent to `timeliness:(Non AND Time AND Critical)` and `timeliness:Critical AND timeliness:Time AND timeliness:Non`.

So whichever approach we take we would have to check the content of the keyword first. I would choose the escaping approach and check for the presence of square brackets. In case of quoting we would also have to check for the presence of wildcards, which is a bit more extra work.

Mostly unrelated, but going over the query syntax spec I discovered some other interesting features I was not yet aware of:
* Multiple keywords per parameter. That is, `identifier:(S1A_WV_OCN__2SSV_20150526T081641_20150526T082418_006090_007E3E_104C OR S1A_WV_OCN__2SSV_20150526T211029_20150526T211737_006097_007E78_134A)` is equivalent to `identifier:S1A_WV_OCN__2SSV_20150526T081641_20150526T082418_006090_007E3E_104C OR identifier:S1A_WV_OCN__2SSV_20150526T211029_20150526T211737_006097_007E78_134A`.
* Regex support. `identifier:/S[123].*/`.
* Single-sided range queries. `relativeorbitnumber:[100 TO *]` or `beginposition:[* TO NOW-3YEAR]`.
* Exclusive ranges. `relativeorbitnumber:{101 TO 103}` matches only 102.

**Comment by Fernerkundung** [comment]
Sounds like escaping is the obvious choice.

> We might want to document some of this somewhere.

May I suggest creating a new issue with the goal to create a section in the docs dedicated to behaviour of query parameters? Would be a good beginner issue and until it is included in the docs it's documented in the issue.

**Comment by valgur** [comment]
Uh, but [tileid:32UMF OR tileid:32UPF](https://scihub.copernicus.eu/apihub/search?format=json&rows=10&start=0&q=tileid:32UMF%20OR%20tileid:32UPF) does seems to work? Or am I missing something?

> May I suggest creating a new issue with the goal to create a section in the docs dedicated to behaviour of query parameters? 

Sure. It's outside the scope of the current issue anyway.

**Comment by Fernerkundung** [comment]
It does work, but it shows some behaviour that makes me supicious. If you [sort by IngestionDate](2017-05-04) and expand the query to `tileid:*UMF or tileid:32UPF` the oldest is 2017-05-04T15:34:12.204Z.

I'll look into this further in a separate issue - if this reliably works we could re-open #140 to include `--tile` taking a list of tiles for search/download.

**Comment by PhML** [comment]
@Fernerkundung

Example of query that should work:
```python
from sentinelsat import SentinelAPI

api = SentinelAPI("MYLOGIN", "MYPASSWORD", 'https://coda.eumetsat.int')

footprint = 'POLYGON ((-133.0000000000000000 12.0000000000000000, -133.0000000000000000 44.0000000000000000, -165.0000000000000000 44.0000000000000000, -165.0000000000000000 12.0000000000000000, -133.0000000000000000 12.0000000000000000))'

dates = ('20150101', '20171015')

query_parameters = {'timeliness': 'Near Real Time', 'filename': 'S3A_OL_2*', 'platformname': 'Sentinel-3'}

r = api.query(footprint, dates, **query_parameters)
```
With quotes it returns 1012 products.

Without quotes (first it takes long) and then, I get:

```python
SentinelAPIError: HTTP status 502 Proxy Error:
# Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request _[POST /search](/search)_.

Reason: **Error reading from remote server**

* * *

Apache/2.2.31 (CentOS) Server at coda.eumetsat.int Port 443
```
With quotes around every values:

```python
SentinelAPIError: HTTP status 500 Internal Server Error: IOException : Server returned HTTP response code: 400 for URL: http://localhost:30333//solr/dhus/select?q=beginposition:"[2015-01-01T00:00:00Z%20TO%202017-10-15T00:00:00Z]"%20filename:"S3A_OL_2*"%20platformname:"Sentinel-3"%20timeliness:"Near%20Real%20Time"%20footprint:"Intersects(POLYGON%20((-133.0000000000000000%2012.0000000000000000,%20-133.0000000000000000%2044.0000000000000000,%20-165.0000000000000000%2044.0000000000000000,%20-165.0000000000000000%2012.0000000000000000,%20-133.0000000000000000%2012.0000000000000000)))"&wt=xslt&tr=opensearch_atom.xsl&dhusLongName=EUMETSAT+User+Helpdesk&dhusServer=http%3A%2F%2Fcoda.eumetsat.int%2F&originalQuery=beginPosition%3A%22%5B2015-01-01T00%3A00%3A00Z+TO+2017-10-15T00%3A00%3A00Z%5D%22+filename%3A%22S3A_OL_2*%22+platformname%3A%22Sentinel-3%22+timeliness%3A%22Near+Real+Time%22+footprint%3A%22Intersects%28POLYGON+%28%28-133.0000000000000000+12.0000000000000000%2C+-133.0000000000000000+44.0000000000000000%2C+-165.0000000000000000+44.0000000000000000%2C+-165.0000000000000000+12.0000000000000000%2C+-133.0000000000000000+12.0000000000000000%29%29%29%22&rows=100&start=0&sort=ingestiondate+desc
```

@valgur :
You should not only check square brackets, but also curly brackets then.
