### ISSUE TITLE
deploy to PyPi via Travis-CI

### ISSUE THREAD

**Issue by Fernerkundung** [sentinelsat/sentinelsat#173]
We can streamline the publication of releases by automating the process with Travis-CI. I'd suggest we do this for tagged releases only, as it is now.

- [Travis docs on PyPi deployment](https://docs.travis-ci.com/user/deployment/pypi/)
- minimal working example from [mercantiles .travis.yml](https://github.com/mapbox/mercantile/blob/master/.travis.yml)

**Comment by valgur** [comment]
I would say this is not critical for v1.0 release?
