### ISSUE TITLE
geopandas is missed as dependency

### ISSUE THREAD

**Issue by skasberger** [sentinelsat/sentinelsat#176]
When executing to_geodataframe(), the geopandas package was not found on my aws instance. I checked and installed it via pip, and then looked in requirements.txt, where the entry was missing. So I guess this is the problem here, right?

```
geopandas==0.3.0
```

**Comment by valgur** [comment]
We have not included GeoPandas (or even Pandas for that matter) as a requirement since it is a fairly heavy one and is not required outside that single convenience function. In particular, it depends on GDAL, which can be a pain to install on Windows.

We do have [a small note](https://sentinelsat.readthedocs.io/en/stable/install.html#optional-dependencies) about this in the docs, but it can be easy to miss, I guess. Nevertheless, thanks for bringing up a possible issue. I appreciate it.

**Comment by Fernerkundung** [comment]
@valgur Maybe we should could a try/except block into these convenience functions to warn the user about the dependency? Or create an entry into `setup.py` with the dependencies similar to `test` - maybe called `all`?

Not including the dependencies for `to_dataframe` and `to_geodataframe` was a conscious decision by us. However, a small note might not be enough if users are missing it.

I'm reopening this for discussion.

**Comment by j08lue** [comment]
In other packages, I have mostly seen optional dependencies handled the same way as here - with notes in the docs (e.g. [`xarray`](http://xarray.pydata.org/en/stable/installing.html#optional-dependencies)), or maybe several sets of `requirements.txt`, like `requirements[_minimal].txt`, `requirements_full.txt`, `requirements_tests.txt`...

It would be great to find some systematic way of installing optional / lazy dependencies, like with `setup.py`. One problem is that you will hardly ever want to `pip install` `gdal` or `numpy` without having taken care of the libs first - neither on Windows nor on Linux. But that kinda rules out anything but some instructions in the docs...

**Comment by Fernerkundung** [comment]
> you will hardly ever want to pip install gdal or numpy without having taken care of the libs first

Good point.

How about something like this to make it more explicit?

```python
try:
    import geopandas
except ImportError:
    self.logger.warning("This function requires the optional dependency GeoPandas.")
```

**Comment by j08lue** [comment]
You will have to raise an exception, but yes, definitely wrap the `ImportError`.

**Comment by j08lue** [comment]
`pytest` has some decorator / flags for this kind of stuff (https://docs.pytest.org/en/latest/skipping.html#skipping-on-a-missing-import-dependency). Maybe a bit overkill, but we could make an `require_optional_dependencies` decorator that tries to import the names that are passed to it and fails with a good message. Then we can catch this even before entering the function.

**Comment by skasberger** [comment]
just to say: the error message was pretty descriptive itself. just did not read the note about it in the documentation, and am not used to have differentiated requirements for a package.
