### ISSUE TITLE
query returns 0 results

### ISSUE THREAD

**Issue by Artadys** [sentinelsat/sentinelsat#178]
Hi,

The line command should be different

I have a problem with `sentinelsat -u myusername -p mypassword -g map-2.geojson --sentinel 2 --cloud 30 --url "https://scihub.copernicus.eu/dhus" `

I built a map-2.geojson above Paris as hereafter (scroll down) file

and I get 0 products

which is not good

Here are the results

```bash
$ sentinelsat -u myusername -p mypassword -g map-2.geojson --sentinel 2 --cloud 30 --url "https://scihub.copernicus.eu/dhus"
Found 0 products
---
0 scenes found with a total size of 0.00 GB
```

Thanks for your attention

PS: map-2.geojson is like that

```
{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[1.3842773437499998,49.05227025601607],[2.43896484375,47.87214396888731],[3.71337890625,48.705462895790546],[2.4609375,49.33944093715546],[1.3842773437499998,49.05227025601607]]]}}]}
```

**Comment by Fernerkundung** [comment]
If you leave out a start date using the `-s` option it will query the last 24 hours only. If you add `-s` to your query it works fine, eg. using 2017-11-01 as start and the current date as end.

`sentinelsat -u myusername -p mypassword -g map-2.geojson --sentinel 2 --cloud 30 --url https://scihub.copernicus.eu/dhus -s 20171101`

```bash
Found 29 products
Product cf121829-6703-491f-a25a-9d963ac88554 - Date: 2017-12-02T10:54:21.026Z, Instrument: MSI, Mode: , Satellite: Sentinel-2, Size: 794.43 MB
Product e6161d21-f0c1-4bf5-8e65-1db89e4e2494 - Date: 2017-11-30T11:04:09.027Z, Instrument: MSI, Mode: , Satellite: Sentinel-2, Size: 602.99 MB
...
Product ab4070b2-9b39-45e3-847e-2c94d0261ade - Date: 2017-11-04T10:42:09.027Z, Instrument: MSI, Mode: , Satellite: Sentinel-2, Size: 685.38 MB
---
29 scenes found with a total size of 20.77 GB
```

**Comment by Artadys** [comment]
Great, Thanks I agree….great stuff I learn..

Now I am going to download them.

Thanks




Cristian BEZA <https://www.linkedin.com/in/CristianBeza> | 

Chief Executive Action Officer ✈️ ☞ ARTEDYS  | 🛩 ☞ ARTADYS <https://artadys.com/> | 

🛰 Satellites, 🚀 Rockets, 🛫 Drones 🛬 🚁 |  open full-stak 🛰 satellites 🔭 platforms  📡  images and videos 🚀  | 
 
🗼Human Digital Landscapes  |  Behavior, Personality, Attitudes, Loyalty, and Trend Tracking on the Internet | Strategy and Research

ARTADYS <https://artadys.com/> & Buzz Analytics | Paris & Washington, DC |

https://www.artadys.com <https://artadys.com/>

+ 33 (0) 6 23 53 04 34 Cell 
 
LinkedIn: https://www.linkedin.com/in/CristianBeza <https://www.linkedin.com/in/CristianBeza>
  
"A plan without action is not a plan. It's a speech."

Thomas Boone Pickens (Consultant milliardaire )

**Comment by Artadys** [comment]
Thanks got it.

Please another question.

The files where they are ? How to display them ? Thanks




Cristian BEZA <https://www.linkedin.com/in/CristianBeza> | 

Chief Executive Action Officer ✈️ ☞ ARTEDYS  | 🛩 ☞ ARTADYS <https://artadys.com/> | 

🛰 Satellites, 🚀 Rockets, 🛫 Drones 🛬 🚁 |  open full-stak 🛰 satellites 🔭 platforms  📡  images and videos 🚀  | 
 
🗼Human Digital Landscapes  |  Behavior, Personality, Attitudes, Loyalty, and Trend Tracking on the Internet | Strategy and Research

ARTADYS <https://artadys.com/> & Buzz Analytics | Paris & Washington, DC |

https://www.artadys.com <https://artadys.com/>

+ 33 (0) 6 23 53 04 34 Cell 
 
LinkedIn: https://www.linkedin.com/in/CristianBeza <https://www.linkedin.com/in/CristianBeza>
  
"A plan without action is not a plan. It's a speech."

Thomas Boone Pickens (Consultant milliardaire )

**Comment by Fernerkundung** [comment]
As per the documentation (https://sentinelsat.readthedocs.io/en/stable/cli.html) the files will be downloaded to your shells working directory unless you specify a download path with the `--path` option.

Regarding the display and manipulation of the data I suggest taking a look at the Sentinel Toolboxes: https://sentinel.esa.int/web/sentinel/toolboxes/sentinel-2

**Comment by Artadys** [comment]
Thanks Kersten,

I am on Mac OS X terminal and I want to download the files in my path

sentinelsat -u artadys -p Negoescu1 -g map-2.geojson --sentinel 2 --cloud 30 --url https://scihub.copernicus.eu/dhus -s 20171101 --path /Users/artedys/sentinel

I have difficulties tu get them in my computer - only with terminal command because later I want to build my own code to do that

I took a quick look at the documentation and here they are NOT in my computer - (I put —path option)





Cristian BEZA <https://www.linkedin.com/in/CristianBeza> | 

Chief Executive Action Officer ✈️ ☞ ARTEDYS  | 🛩 ☞ ARTADYS <https://artadys.com/> | 

🛰 Satellites, 🚀 Rockets, 🛫 Drones 🛬 🚁 |  open full-stak 🛰 satellites 🔭 platforms  📡  images and videos 🚀  | 
 
🗼Human Digital Landscapes  |  Behavior, Personality, Attitudes, Loyalty, and Trend Tracking on the Internet | Strategy and Research

ARTADYS <https://artadys.com/> & Buzz Analytics | Paris & Washington, DC |

https://www.artadys.com <https://artadys.com/>

+ 33 (0) 6 23 53 04 34 Cell 
 
LinkedIn: https://www.linkedin.com/in/CristianBeza <https://www.linkedin.com/in/CristianBeza>
  
"A plan without action is not a plan. It's a speech."

Thomas Boone Pickens (Consultant milliardaire )

**Comment by Fernerkundung** [comment]
That would be because you are missing the `-d` option to actually download the data - as listed in the documentation.

**Comment by Artadys** [comment]
Thanks…Bravo :) is downloading …..All The Best there :)




Cristian BEZA <https://www.linkedin.com/in/CristianBeza> | 

Chief Executive Action Officer ✈️ ☞ ARTEDYS  | 🛩 ☞ ARTADYS <https://artadys.com/> | 

🛰 Satellites, 🚀 Rockets, 🛫 Drones 🛬 🚁 |  open full-stak 🛰 satellites 🔭 platforms  📡  images and videos 🚀  | 
 
🗼Human Digital Landscapes  |  Behavior, Personality, Attitudes, Loyalty, and Trend Tracking on the Internet | Strategy and Research

ARTADYS <https://artadys.com/> & Buzz Analytics | Paris & Washington, DC |

https://www.artadys.com <https://artadys.com/>

+ 33 (0) 6 23 53 04 34 Cell 
 
LinkedIn: https://www.linkedin.com/in/CristianBeza <https://www.linkedin.com/in/CristianBeza>
  
"A plan without action is not a plan. It's a speech."

Thomas Boone Pickens (Consultant milliardaire )
