### ISSUE TITLE
md5 checksum problem after download

### ISSUE THREAD

**Issue by ewirth** [sentinelsat/sentinelsat#182]
First I try to download only one product with following code:

```
footprint = geojson_to_wkt(read_geojson('d://bitbucket//lcm-cnn//velence.geojson'))
products = api.query(
    footprint,
    date = ('20171219', '20171224'),
    platformname = 'Sentinel-2',
    cloudcoverpercentage=(0,0.35))
```

And after the download, the md5 checksumming  slows down every time so much, so I can't wait for it.
(See the attached image)
https://ufile.io/svyfa

Do you have any idea to solve this?
https://ufile.io/4thyt

You can download the geojson file here:

**Comment by Fernerkundung** [comment]
MD5 should not noticeably slow down your system or the download and usually makes up less than 1% of the time used for query and download.

Can you include your system details - OS Version, CPU, RAM, etc.?

If this is an issue with your system you could always skip the MD5 check while downloading with using the argument `checksum=False` in the [`download` function](https://sentinelsat.readthedocs.io/en/stable/api.html#sentinelsat.SentinelAPI.download).

I attached the image of your error to this issue:
![md5_checksumming](https://user-images.githubusercontent.com/1621864/34363421-4a7542f8-ea7c-11e7-9ac9-3e787f6e77dd.png)

**Comment by Fernerkundung** [comment]
@ewirth any update on this?

**Comment by Fernerkundung** [comment]
@ewinter7 Can you include your system details - OS Version, CPU, RAM, etc.?

I'd still like to get to the bottom of this error but I can't reproduce it with this litte information.

**Comment by Fernerkundung** [comment]
Closed due to not enough information to reproduce this error.

If you can provide more information or also encounter this error please reply and I'll reopen this issue.

**Comment by ewirth** [comment]
Here again after almost 3 years, facing the same problem with my notebook.
md5 checksum was almost stopped at 53%, so I gonna switch it off by checksum=False you wrote.

The same thing happened like years ago. Started to download the tile with 3 MB/sec, and it slowed down continuously till 300 KB/s at finish.

Notebook hardware (ASUS X55C):
6 GB RAM, Intel Core i3-2350M CPU @ 2.30 GHz

Software:
Windows 7,
I call the script in Python 3.7.6 Shell

**Comment by ewirth** [comment]
@Fernerkundung 

Seems I fixed the problem, which was due to that I run the script in IDLE.
By calling in terminal it was smooth and fast, tested on another, new tile as well :)
