### ISSUE TITLE
Remove list of valid producttypes from CLI

### ISSUE THREAD

**Issue by Fernerkundung** [sentinelsat/sentinelsat#183]
Currently the sentinelsat CLI has a list of valid values for the option `--producttype` implemented with

`click.Choice(['SLC', 'GRD', 'OCN', 'RAW', 'S2MSI1C', 'S2MSI2Ap'])`

This list is only complete for the Copernicus Open Access Hub but is missing the all available producttypes for the S3 PreOps-Hub.

With the upcoming merge of S3 into the regular hub as well as new missions like S5P I propose to remove the click choice and let users type any product type they like.

The list of products is a nice guide but makes the option unuseable for any DHuS instance with product types other than the ones defined in the OpenHub.

To help users what they can enter in the field I'd say we can include a list of known product types into the documentation or link to an official list (if it exists).

edit:

This would entail a small refactoring in `cli.py` regarding the `producttype` option and is a good first issue / suitable for beginners.

**Comment by j08lue** [comment]
I'm all for it. 👍

**Comment by lenniezelk** [comment]
i'd like to work on this

**Comment by mathagician** [comment]
@j08lue is this issue still open. If yes I would like to work on this.

**Comment by Fernerkundung** [comment]
@mathagician This has been done by @lenniezelk in #190 - unfortunately we haven't gotten around to merge it yet (hence why this issue is still open).

**Comment by Fernerkundung** [comment]
Closed with #190
