### ISSUE TITLE
Download speed

### ISSUE THREAD

**Issue by G00FYDUDE** [sentinelsat/sentinelsat#187]
Hi all,

Kinda new to all this as in i think it took me many hours to even use your idiot proof guide on how to install and use sentinelsat. But i did get it going in the end and it has been pulling down 1000s of images for me. However the download speed fluctuates arround 2-3MB/s meaning that 24h is about 350images rather slow. 
Is there any way to make it faster in short? or does it work like ftp so its at the maximum rate of esa's push?
very limited understanding of these things
PC is running win10 64 bit and sentinelsat v0.12.1 gigabit ethernet connection and fiber direct into building >gigabit

any advice would be greatly appreciated

**Comment by j08lue** [comment]
> download speed fluctuates arround 2-3MB/s

That is what I am getting, too. 3 **Megabyte per second** (24 Mbps) is actually pretty decent, I'd say. 

If you have multiple downloads at the same time (max 2 per user), the combined speed will be somewhat higher.

I don't think we can do anything to increase the speed.

Downloading from AWS (e.g. with [sentinelhub](https://github.com/sentinel-hub/sentinelhub-py)) can be faster, but in my experience not much if you need the full `.SAFE` structure.

**Comment by G00FYDUDE** [comment]
Thanks for that now I know we are both getting roughly the same speed I guess I am asking is there any limit imposed on the download speed by sentinelsat its self? If there is not then i can ask esa if there is anything they can do.

**Comment by valgur** [comment]
You can also check out the [national mirrors](https://github.com/Fernerkundung/awesome-sentinel#data-hubs-and-national-mirrors) to SciHub. They work identically to SciHub, you just have to specify the `--url` parameter of the mirror in sentinelsat. The speeds I get from the Finnish mirror, for example, are limited entirely by the bandwidth at my side at 20 MB/s or so. One caveat though: the national mirrors often only contain a subset of the entire archive available in SciHub.

**Comment by j08lue** [comment]
According to [this SO thread](https://stackoverflow.com/questions/16694907/how-to-download-large-file-in-python-with-requests-py), the current method we use for pulling the files might not be optimal in terms of speed:

i.e. chunked download like we do here:

https://github.com/sentinelsat/sentinelsat/blob/9f58af55a1719f45a7e9f79cc6ee3375bfdd503a/sentinelsat/sentinel.py#L743

could be slower than `response.raw` combined with `shutil.copyfileobj` (like in [this answer](https://stackoverflow.com/a/39217788)).

It would be great if you could verify that. To do so, get some download links using the API like `api.get_product_odata(id)['url']` and then download the link with the `shutil`-based method mentioned above or a command line tool like `wget` or `curl` and see if it is faster.

`sentinelsat` needs to use the chunked download to have a progress bar and the function to continue partial downloads. But that is why we have the Python API - so you can try different methods.

**Comment by G00FYDUDE** [comment]
Thanks for the mirror tip the UK mirror is SEDAS and luckily this project only requires UK coverage but the whole catalogue of it. However I am not sure that sentinelsat will work with this mirror as I cannot seem to find a url to use for their api.

**Comment by G00FYDUDE** [comment]
https://geobrowser.satapps.org/api/ I think but I will have to try it tomorrow

**Comment by j08lue** [comment]
SEDAS is not based on [DHuS](http://sentineldatahub.github.io/DataHubSystem/), so no, you cannot use `sentinelsat` against that API.

You would have to write your own client based on [their docs](https://geobrowser.satapps.org/docs/).

**Comment by Fernerkundung** [comment]
When I tested the download speed ca. 6 months ago comparing python requests, urllib, wget, curl, pycurl I achieved identical speeds from the Copernicus Open Access Hub. I suspect they or their storage provider impose a limit per user or something similar.

The [Annual Data Access Report](https://scihub.copernicus.eu/twiki/pub/SciHubWebPortal/AnnualReport2016/COPE-SERCO-RP-17-0071_-_Sentinel_Data_Access_Annual_Report_2016_v1.2.pdf) only mentions the restriction of 2 concurrent downloads per user but no imposed bandwidth limitations. According to them the network now should operate at 20Gbps (i.e. 2.5 GB/s) - that is however split between all hubs (Open Access, Collaborative, etc.).

I contacted the Copernicus Support Office, hopefully they can provide a definitve answer.

**Comment by Fernerkundung** [comment]
Got the answer for my Copernicus Support Ticket CDS-48549:

Q: "I was wondering if the Copernicus Open Access Hub imposes any bandwidth limits per user or download."
A: "The technical team have confirmed that there is no limitation on bandwidth."

The only way to get faster downloads then is to move closer to the DHuS endpoint from a network perspective. This means either using a national mirror or for instance using a server located close to the Copernicus Open Access Hub, which is in Frankfurt afaik.

The only short term solution for you would be to chose a different DHuS endpoint. `sentinelsat` is not the limiting factor in the download speed.

I'll close this issue as this is nothing we can solve with code changes to `sentinelsat`. If you have further questions please comment again and I'll reopen.

**Comment by Shelomoh1** [comment]
Using CNES PEPS website to download Sentinel 2 data increased the download speed to a few megabytes (3mb/s). Better than downloading directly from the sentinel hub which was max. 10kb/s.
