### ISSUE TITLE
Accessing national mirrors

### ISSUE THREAD

**Issue by fri-end** [sentinelsat/sentinelsat#199]
Hi,

Is it possible to use sentinelsat functionality to access the Australian mirror of Sentinel data: https://copernicus.nci.org.au/?
I tried something like this: api = SentinelAPI('my_email', 'my_password', 'https://copernicus.nci.org.au/'), but getting the following error: "The requested URL /search was not found on this server."
I'd appreciate any help.

Cheers, Yuri

**Comment by Fernerkundung** [comment]
Sentinelsat can be used for any mirror that is based on ESA's [Datahub Software (DHuS)](https://sentineldatahub.github.io/DataHubSystem/).

The Australian and French mirrors are based on [rocket](http://mapshup.com/projects/rocket/#/home) and can not be accessed with sentinelsat.
