### ISSUE TITLE
Connection error while downloading 

### ISSUE THREAD

**Issue by hiraksarkar** [sentinelsat/sentinelsat#204]
Hi I am getting this error for past few hours now, but it does not look like HTTP 500/501. Is the connection blocked from my end. 
`sentinelsat -u hirak -p nowornever -g '/home/hsarkar/dataset/toy_dataset/sample1.geojson'`

```
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='scihub.copernicus.eu', port=443): Max retries exceeded with url: /apihub/search?format=json&rows=100&start=0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1465cd5438>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
```

**Comment by hiraksarkar** [comment]
This was an issue with the proxy from my end. Closing.

**Comment by bonnieWeng** [comment]
Hi Hirak! I am getting the same error as you. May I please ask how did you resolve your issue? I was able to download Sentinel 2 images via sentinelAPI. However, this evening, I suddenly got this error. If this is a problem with the proxy setting on my laptop, could you please provide more details how I should fix it? Thanks!

**Comment by Gxmg** [comment]
> Hi Hirak! I am getting the same error as you. May I please ask how did you resolve your issue? I was able to download Sentinel 2 images via sentinelAPI. However, this evening, I suddenly got this error. If this is a problem with the proxy setting on my laptop, could you please provide more details how I should fix it? Thanks!

hello, I also encountered the same problem, how do you solve it？

**Comment by j08lue** [comment]
SciHub is down today #364
