### ISSUE TITLE
Reconnect when drop to minimal speed

### ISSUE THREAD

**Issue by c040340** [sentinelsat/sentinelsat#215]
Hi just found that for bad network circumstance, the server is going to stop responding and the downloading procedure will stuck. 

To handle this I just made some modification on your code, I added an "timeout" flag to your downloading session in https://github.com/sentinelsat/sentinelsat/blob/fea079487dce41ccfe049a6e856a8287b77d8fe3/sentinelsat/sentinel.py#L741 and use "while" function to make _download() function running again and again. 

This worked very will for bad network circumstance.

**Comment by Fernerkundung** [comment]
How do you detect a timeout - i.e. what is the cut-off when a download is considered to be timed out vs. running as expected?

**Comment by c040340** [comment]
Since you have already set the chuck size to 2*20 (2MB or 1MB, in line 745), you can just set "timeout" to 2000 (unit is second) and this means when the download speed is lower than 1KB/s we are going to re-download the chunk. 

I just found this is very helpful for my network. 

Cheers,

**Comment by Fernerkundung** [comment]
That does sound like a reasonable default for a lower boundary. Would you mind preparing a pull request for this?

I think it would be useful to set this as an parameter of the `SentinelAPI` class so users with faster/slower connections can set it accordingly. What's your take on this @valgur @j08lue ?

**Comment by c040340** [comment]
Yeah, I am glad to do that. Do you need to invite me to the group before I make the changes?

**Comment by j08lue** [comment]
> I think it would be useful to set this as an parameter of the SentinelAPI class so users with faster/slower connections can set it accordingly.

Sounds like the perfect solution for this. This will be a good addition, @c040340, thanks.

**Comment by j08lue** [comment]
The change we envisioned above has been implemented in #259. I am taking the liberty to close this.
