### ISSUE TITLE
Query fails when GeoJSON polygon is not WGS84

### ISSUE THREAD

**Issue by mdoubko** [sentinelsat/sentinelsat#218]
Hello all,

I am running following script that used to work just a month ago:
```python
footprint = geojson_to_wkt(read_geojson('C:\DATA_raw\shapefiles\Fields\Field011_32633.geojson'))
products = api.query(footprint,date=('20180401', '20180417'),producttype='S2MSI2Ap',
                 platformname = 'Sentinel-2',cloudcoverpercentage = (0, 100),)
```

Unfortunately, I am getting following error:
`TypeError: int() argument must be a string or a number, not 'NoneType'`
that follows another error:

`File "C:\Users\Marcela\Anaconda2\envs\PESSL_27\lib\site-packages\sentinelsat\sentinel.py", line 287, in _load_subquery
    total_results = int(json_feed['opensearch:totalResults'])`

Why are the totalResults None?

thanks a lot for your help,
Marcela

**Comment by valgur** [comment]
That happens when the server is a syntax error or an unsupported parameter is used in the query. This should not ever happen with the way you are using the `query()` method, though.
What sentinelsat version are you using? This exception should be handled [more gracefully](https://github.com/sentinelsat/sentinelsat/blob/v0.12.2/sentinelsat/sentinel.py#L283) by the latest versions. Maybe upgrading to the latest version fixes your issue?

**Comment by mdoubko** [comment]
I updated. Now, I am using 0.12.2. Still following error occurs:

  File "C:\Users\Marcela\Anaconda2\envs\PESSL_36\lib\site-packages\sentinelsat\sentinel.py", line 284, in _load_subquery
    'Invalid query string. Check the parameters and format.', response)
sentinelsat.sentinel.SentinelAPIError: HTTP status 200 OK: Invalid query string. Check the parameters and format.
when calling following:
products = api.query(footprint,date=('20180401', '20180417'),cloudcoverpercentage = (0, 100),platformname = 'Sentinel-2', producttype='S2MSI2Ap')

thanks!

**Comment by Fernerkundung** [comment]
@mdoubko Sorry for being unclear - as an attachment to a comment posted on GitHub. Alternatively you could also paste the content to pastebin/gist or any other plain text pasting service.

**Comment by mdoubko** [comment]
Here comes the JSON file inside:

{
"type": "FeatureCollection",
"name": "Field011subset_32633",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::32633" } },
"features": [
{ "type": "Feature", "properties": { "id": 1 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 525852.43409210734535, 5203419.928216612897813 ], [ 525860.020372478989884, 5203408.859709185548127 ], [ 525869.720862134359777, 5203415.824163297191262 ], [ 525865.243713062605821, 5203425.897748708724976 ], [ 525865.243713062605821, 5203425.897748708724976 ], [ 525852.43409210734535, 5203419.928216612897813 ] ] ] } }
]
}

**Comment by valgur** [comment]
Thanks for including the footprint file. That clears it up: you need to transform the footprint polygon's coordinates to WGS84 for the query to work, since that's what the server expects.

I see that we are currently not mentioning this fact anywhere in the documentation. This is something we can certainly improve.

**Comment by Fernerkundung** [comment]
Not using WGS84 is a direct violation of the [GeoJSON RFC](https://tools.ietf.org/html/rfc7946).

> The coordinate reference system for all GeoJSON coordinates is a
   geographic coordinate reference system, using the World Geodetic
   System 1984 (WGS 84) [WGS84] datum, with longitude and latitude units
   of decimal degrees.

I've experienced ArcGIS violating this. I think the best place to document this would be in ["common issues"](https://github.com/sentinelsat/sentinelsat/blob/master/docs/common_issues.rst), potentially with a list of software that produces non-standard GeoJSON.
