### ISSUE TITLE
bug in querying on area 

### ISSUE THREAD

**Issue by jajcayn** [sentinelsat/sentinelsat#220]
I recently came across a bug, where the footprint of the file is actually the subtracted part of the globe [see attached files]. 

downloaded NO2 file
<img width="880" alt="screen shot 2018-07-27 at 2 44 56 pm" src="https://user-images.githubusercontent.com/6525217/43321677-ee06d422-91ac-11e8-99db-94142a109316.png">
its footprint, dumped as `geojson`
<img width="1423" alt="screen shot 2018-07-27 at 2 44 46 pm" src="https://user-images.githubusercontent.com/6525217/43321679-ee264c30-91ac-11e8-9e21-8d6b0d18aaec.png">

My code works as follows:
```
area_of_interest = geojson_to_wkt(read_geojson(gj_filename))
api = SentinelAPI(username, password, url)
products = api.query(area=area_of_interest,
                         area_relation='Intersects',
                         date=(config['date_from'], config['date_to']),
                         platformname='Sentinel-5 Precursor',
                         processingmodeabbreviation=config['timeline'],
                         processinglevel='L2',
                         producttype=PRODUCT_TABLE[config['product']])
```
The problem is, this downloads a lot of products that are actually outside the footprint [again as seen on the attached files].
I think this is not an expected behaviour. Is there any way around it?

Cheers!

**Comment by valgur** [comment]
Interesting problem. Could include it here or upload the GeoJSON file somewhere, please?

**Comment by jajcayn** [comment]
the geojson I am including as area (`gj_filename` in my snippet) is here: https://www.dropbox.com/s/7f47g28nku5k4tx/Prague_rectangle.geojson?dl=0
the footprint of the S5P file [screenshot above] is here: https://www.dropbox.com/s/yxhnc1b73ucchhe/0a2050ef-6214-4152-b651-154fe1d9b27d.geojson?dl=0

**Comment by j08lue** [comment]
Interesting study area - there is very little of the world you are not querying for. Things might work slightly better if the polygon was not wrapped at 180E?

**Comment by jajcayn** [comment]
no, no, no.
the opposite actually: I am querying only for a very small rectangle around one city (Prague, Czech republic), file here: https://www.dropbox.com/s/7f47g28nku5k4tx/Prague_rectangle.geojson?dl=0; screenshot:
<img width="860" alt="screen shot 2018-07-30 at 5 38 31 pm" src="https://user-images.githubusercontent.com/6525217/43407615-8266e502-941f-11e8-8b88-9778661fb0be.png">
So in the query, the polygon is not wrapped at 180E, because the span is something like 100km (~1degree)

the problem is, when I query for this location, the API downloads a lot of unrelated files, i.e. with a different footprint. I was digging into why is this happening and then I found out the footprint problem described above. That is, the `sentinelapi` downloader downloads the file because it 'thinks' it covers the area I want, however, the file actually covers the inverse area over the globe.

**Comment by j08lue** [comment]
> the opposite actually

Ah, got it.

**Comment by Fernerkundung** [comment]
You are importing the `producttype` and `date` from a config file. Could you include the actual values into this issue? The issue might be specific to how the DHuS handles patial queries on the dataset.

**Comment by j08lue** [comment]
> The issue might be specific to how the DHuS handles patial queries on the dataset.

Good bet! Could be it ignores the region of interest on such a query. Like when you search for Sentinel 2 data by product name.

**Comment by jajcayn** [comment]
Dear @Fernerkundung, thanks for your reply.
I tried different products and different dates, however, I always tried to download the new Sentinel-5P data. This particular example, as you can see on the first screenshot I shared, is nitrogen dioxide, hence `producttype  = L2__NO2___` and for the dates, I tested with more different dates, specifically, the example is between 2018-04-25 and 2018-04-26...
Do you think that this might be solely Sentinel-5P connected issue?

**Comment by j08lue** [comment]
I'll close this here. It is a weird issue, specific to Sentinel 5P queries against Copernicus Open Access Hub that Sentinelsat cannot fix. We do not override area queries when other properties (like product type or so) are set.

If this issue persists (upstream)(, a workaround is to manually filter the query results by intersecting them with the AOI afterwards, which is a one-liner with GeoPandas.
