### ISSUE TITLE
HTTP authentication required

### ISSUE THREAD

**Issue by elmerehbi** [sentinelsat/sentinelsat#222]
I am facing the same issue as in a previous [issue](https://github.com/sentinelsat/sentinelsat/issues/45)

My account was created in October 2017 on the Scihub platform. What might be the problem?

`sentinelsat -s 20150101 -e 20151231 -d --producttype SLC -q "orbitdirection=Descending"`

Also, if I set `<poly.geojson>` or `search_polygon.geojson` it complains that it does not exist.

If I use the filename as in the [documentation](https://sentinelsat.readthedocs.io/en/stable/cli.html#sentinel-1) it complains with the same error as above:
`sentinelsat -d --name S1A_EW_GRDM_1SDH_20151224T154142_20151224T154207_009186_00D3B0_C71E`

However If I try `sentinelsat -d --uuid a9048d1d-fea6-4df8-bedd-7bcb212be12e` it replies with `Will download 0 products`.

**Comment by Fernerkundung** [comment]
This issue is closed due to lack of activity. Please comment below if you want it reopened.

**Comment by GloryPassarello** [comment]
Is this solved? 

It seems I have experienced the same error: 

`sentinelsat.sentinel.SentinelAPIError: HTTP status 401 Unauthorized: 
# HTTP Status 401 - Full authentication is required to access this resource

 **type** Status report

 **message** _Full authentication is required to access this resource_

 **description** _This request requires HTTP authentication._

* * *

### Apache Tomcat/8.0.36`

**Comment by Fernerkundung** [comment]
> Is this solved?

It was closed due to inactivity. Can you answer the questions and provide more information, so we can try to find the source of the issue you are seeing?

**Comment by GloryPassarello** [comment]
I created a new account yesterday on https://scihub.copernicus.eu, and I starting using sample code present on quickstart https://sentinelsat.readthedocs.io/en/stable/api.html. 

I had the issue reported before. I made my account almost 24 hour ago.

**Comment by GloryPassarello** [comment]
I can log in using https://scihub.copernicus.eu/dhus/#/home

**Comment by Fernerkundung** [comment]
in the example queries you can try setting the `url` parameter: `https://scihub.copernicus.eu/dhus`

**Comment by GloryPassarello** [comment]
Yes, 
I got this error back: 


```
raise api_error
sentinelsat.sentinel.SentinelAPIError: HTTP status 401 Unauthorized: 
# HTTP Status 401 - Full authentication is required to access this resource

 **type** Status report

 **message** _Full authentication is required to access this resource_

 **description** _This request requires HTTP authentication._

* * *

### Apache Tomcat/8.0.36
```

**Comment by ThomasJames** [comment]
I am experiencing an identical issue.
