### ISSUE TITLE
NRT vs Offline datasets

### ISSUE THREAD

**Issue by OxygenLithium** [sentinelsat/sentinelsat#226]
I am using this package to download data from Sentinel 5P and was wondering whether there is a way I can specify just NRT or offline data using the api.query() function?

**Comment by j08lue** [comment]
> whether there is a way I can specify just NRT or offline data using the api.query() function

Sure, anything you can search for on the DHUS portal (in this case https://s5phub.copernicus.eu/dhus/#/home) you also can in the API. 

When I don't know how things are called behind the scenes, I usually submit a query on the portal and then have a look at the query string that is generated:

![image](https://user-images.githubusercontent.com/3404817/44528496-01f21300-a6ea-11e8-8268-391e33157ce0.png)

So this means you can do:

```python
api.query(..., processingmode='Near real time')
```

**Comment by OxygenLithium** [comment]
Brilliant, thanks!
