### ISSUE TITLE
Error no file or directory "search_polygon.geojson"

### ISSUE THREAD

**Issue by Overature** [sentinelsat/sentinelsat#227]
I am trying to install the sentinet sat api as per [these](https://sentinelsat.readthedocs.io/en/stable/ in) instructions. 

However the code is exactly the same as the powerful api section from that link with my password and username, But I get:

Error no file or directory "search_polygon.geojson"

as a error, can anyone help? 

Seems to be working fine from the command line. 

Thanks

**Comment by j08lue** [comment]
The example in the docs is **not** self-contained. It expects that you have a file `search_polygon.geojson` in the directory you are running from.

```python
footprint = geojson_to_wkt(read_geojson('search_polygon.geojson'))
```

If you instead point to a real GeoJSON file, e.g. one you make on http://geojson.io, it will work.

```python
footprint = geojson_to_wkt(read_geojson('/path/to/my/map.geojson'))
```

**Comment by Overature** [comment]
thanks for your help, if i download a product it works fine.

**Comment by j08lue** [comment]
Please close this issue then. That is usually the original poster's privilege. 😄
