### ISSUE TITLE
Download S2MSI2Ap by tile

### ISSUE THREAD

**Issue by chupakamcd** [sentinelsat/sentinelsat#231]
Hi, 

I want to download S2MSI2Ap (level 2 product) from Sentinel 2. Right now I'm using the example provided in the web. If I use producttype S2MSI1C, there is no problem and I can find the images and download it, but if I use S2MSI2Ap, then can't find anything. 

I'm windows 7 user. Any have this problem?
Thank in advance
Rubén

```python
from collections import OrderedDict
from sentinelsat import SentinelAPI

api = SentinelAPI('XXXX', "XXX")
tiles = ['30TVN']
#product type: S2MSI2Ap, S2MSI1C
query_kwargs = {
        'platformname': 'Sentinel-2',
        'producttype': 'S2MSI1C',
        'date': ('2017-01-01T00:00:00.000Z', 'NOW')}

products = OrderedDict()
for tile in tiles:
    kw = query_kwargs.copy()
    kw['tileid'] = tile  # products after 2017-03-31
    pp = api.query(**kw)
    products.update(pp)

imgs=api.download_all(products, directory_path="H:\\sentinel\\")
```

**Comment by j08lue** [comment]
`tileid` seems not to be in the metadata for `S2MSI2Ap`. Your only option is then to search by `filename`:

```
 kw['filename'] = '*_T{}_*'.format(tile)
```

But it might be that other query parameters are overriden when you search for `filename`, so do some testing and adapt the name pattern if needed.

**Comment by valgur** [comment]
A small tip: you can take advantage of some undocumented search syntax features to combine the separate queries into one.

For querying by `tileid`:
```python
kw['tileid'] = '(' + ' OR '.join(tiles) + ')'
```

For querying by `filename` or `identifier` (the `/.../` denotes a regular expression):
```python
kw['identifier'] = '/.+_T({})_.+/'.format('|'.join(tiles))
```

You can experiment with these, they may or may not make the querying faster and more convenient.

**Comment by Fernerkundung** [comment]
@valgur did you find these by experimentation or are they just not documented by SciHub but part of the underlying SolR/OpenSearch? In any case I think we should include them into our docs as examples - those are great finds :+1:

**Comment by valgur** [comment]
These search features are not officially documented by SciHub, but they are part of the [Apache Lucene query syntax](http://elastic.co/guide/en/elasticsearch/reference/6.0/query-dsl-query-string-query.html#query-string-syntax), which SciHub is using. I first noticed them when working on this issue: https://github.com/sentinelsat/sentinelsat/issues/169#issuecomment-340433778

Even the obscurest Lucene features are supported, like keyword boosting with `^` to change ordering (`&orderby=` with no value must be set explicitly for this to work). Compare:
* [`producttype:S2MSI1C (*_T43QED_*^2 OR *_T30TVN_*)`](https://scihub.copernicus.eu/apihub/search?format=json&rows=5&start=0&q=producttype:S2MSI1C+(*_T43QED_*^2+OR+*_T30TVN_*)&orderby=)
* [`producttype:S2MSI1C (*_T43QED_*^0.5 OR *_T30TVN_*)`](https://scihub.copernicus.eu/apihub/search?format=json&rows=5&start=0&q=producttype:S2MSI1C+(*_T43QED_*^0.5+OR+*_T30TVN_*)&orderby=)

**Comment by j08lue** [comment]
@chupakamcd Did our suggested solutions work for you? If so, then please close the issue.
