### ISSUE TITLE
Sentinel 3 Level 2 images

### ISSUE THREAD

**Issue by geom16011** [sentinelsat/sentinelsat#234]
Is it possible to search using a query in eumetsat.int and download the relevant images (Sentinel 3 level 2)? 
I am interested in Sentinel 3 Level 2 OLCI so i can not use Copernicus Open Access Hub. I only can use https://codarep.eumetsat.int/.

**Comment by geom16011** [comment]
Thank for your answer. I can download from eumetsat using a point featue. But when i give it multiple points  when some images are already downloaded  it gives me the followinhg error: 

Traceback (most recent call last):
  File "E:\seo_dwarf\chl_scripts\tedd.py", line 91, in <module>
    api.download(url,checksum=False)
  File "C:\Python27\lib\site-packages\sentinelsat\sentinel.py", line 421, in download
    product_info = self.get_product_odata(id)
  File "C:\Python27\lib\site-packages\sentinelsat\sentinel.py", line 387, in get_product_odata
    _check_scihub_response(response)
  File "C:\Python27\lib\site-packages\sentinelsat\sentinel.py", line 890, in _check_scihub_response
    raise api_error
SentinelAPIError: HTTP status 502 Proxy Error: 
# Proxy Error

The proxy server received an invalid response from an upstream server.  
The proxy server could not handle the request _[GET
/odata/v1/Products('6cb54dc9-0a68-43ae-
ae70-c00cde638972')](/odata/v1/Products\('6cb54dc9-0a68-43ae-
ae70-c00cde638972'\))_.

Reason: **Error reading from remote server**

* * *
Any ideas?

**Comment by j08lue** [comment]
Hmm. `api.download` does not take a URL but a product UUID like `6cb54dc9-0a68-43ae-
ae70-c00cde638972`. But I don't know if that is the origin of this error.

We need what is called a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example). The least amount of code and other information (besides your credentials) necessary to reproduce the problem.

**Comment by geom16011** [comment]
I give several points (116851 points) to the code and i get this error. When i give only the point that it is supposed to give the error (point having longitude 24.5966167, latitude 36.13845444	and Date_s 20171008 and Date_e 20171009) i don t get any error. 

why is that?
 
The error i get is  
Traceback (most recent call last):
  File "E:\seo_dwarf\chl_scripts\downloading_images_Sentinel_3.py", line 49, in <module>
    products = api.query(footprint, date=(str(date_s[i]), str(date_e[i])),producttype='OL_2_WFR___')
  File "C:\Python27\lib\site-packages\sentinelsat\sentinel.py", line 134, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)
  File "C:\Python27\lib\site-packages\sentinelsat\sentinel.py", line 242, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)
  File "C:\Python27\lib\site-packages\sentinelsat\sentinel.py", line 272, in _load_subquery
    _check_scihub_response(response)
  File "C:\Python27\lib\site-packages\sentinelsat\sentinel.py", line 890, in _check_scihub_response
    raise api_error
SentinelAPIError: HTTP status 502 Proxy Error: 
# Proxy Error

The proxy server received an invalid response from an upstream server.  
The proxy server could not handle the request _[POST /search](/search)_.

Reason: **Error reading from remote server**

* * *

Apache/2.2.31 (CentOS) Server at codarep.eumetsat.int Port 443


The code i am using is: 
import sentinelsat
from sentinelsat import SentinelAPI, read_geojson, geojson_to_wkt
import os
import pandas as pd
import numpy as np
import geojson
from geojson import Point, Feature,FeatureCollection, dump
import urllib
import urllib2
import requests
import requests
from requests.auth import HTTPBasicAuth
#E:\seo_dwarf\validation\platforms\MED\maria_Kremezi\nc\FLU2_PRES

path='E:/seo_dwarf/validation/platforms/MED/maria_Kremezi/nc/'
os.chdir(os.path.expanduser(path))

data = pd.read_table(path+'FLU2_DEPTH.txt',delimiter='\t')

LON=data[:]['Lon'].values.tolist()
LAT=data[:]['Lat'].values.tolist()
date_s=(data[:]['Date_s'].values.tolist())
date_e=(data[:]['Date_e'].values.tolist())
ID=(data[:]['Profile_ID'].values.tolist())
#st=(data[:]['Name_Station'].values.tolist())

result_filename=[]
result_id=[]
result_lon=[]
result_lat=[]
Name=[]
results=[]
st=[]
for i in range(0,len(LON)):
    print LON[i]
    print LAT[i]
    print date_s[i]
    print date_e[i]
    if date_s[i]<20171129:
        api_url='https://codarep.eumetsat.int/'
    else:
        api_url='https://coda.eumetsat.int/'
    print api_url
    my_point = geojson.Point((LON[i],LAT[i]))
    with open('myfile.geojson', 'w') as f:
        dump(my_point, f)
    footprint = geojson_to_wkt(read_geojson('myfile.geojson'))
    api = SentinelAPI(***, ****, api_url, show_progressbars=True)
    products = api.query(footprint, date=(str(date_s[i]), str(date_e[i])),producttype='OL_2_WFR___')
    
    if products!={}:
        print ID[i]
        products_df = api.to_geodataframe(products)
        temp = np.array(products_df)
        #api.download_all(products,checksum=False)
        link=products_df['link'].values
        filename=products_df['filename'].values
        id1=products_df['uuid'].values
       
        temp=np.column_stack([link,filename])

        result_filename.append(filename)
        result_id.append(id1)
        result_lon.append(LON[i])
        result_lat.append(LAT[i])
        #temp=str(str(date_s[i])+'_'+str(ID[i]))
        Name.append(ID[i])
        os.remove("myfile.geojson")

**Comment by Fernerkundung** [comment]
That is a lot of requests you are performing. If the script is failing at the same point, but the point in isolation can be queried I would guess you are running into usage limits here.

Can you isolate how many requests you perform before the script fails or maybe revert the order of your points and check if it fails at a new point.

Performing 116k requests I would be surprised if you *didn't* run into any usage rate limit or DDOS prevention mechanism.

Is there any particular reason you are querying 116k points and linking them to a list of product names associated to that location? Performing this many queries does not look like the optimal solution to whatever your specific problem is.

**Comment by j08lue** [comment]
Maybe you can group the points into polygons? Or you put a `time.sleep(1)` in the loop and after 30 hours you can collect your results. 😄

**Comment by geom16011** [comment]
My point is that i have a several points in different locations and times. After i find the images i want to join want the name of the them to the point so i can find the difference between the satelite passes and the time of the in situ measurements and  decide which one i am going to download.

**Comment by Fernerkundung** [comment]
In that case it might make more sense to query the complete study area with a polygon and create a locally stored GeoDataframe. This contains the metadata you are looking for and performing the spatial query locally is orders of magnitude faster than querying each point individually.

**Comment by geom16011** [comment]
But imagine my study area is different areas in the  mediterenean sea.

**Comment by Fernerkundung** [comment]
Querying all scenes of type `OL_2_WFR___` for the *wider mediterranean* results in 2950 products. Querying them once and downloading the metadata will be faster than 80x the amount of queries. Even querying all scenes in Europe is considerably less than your number of individual point queries.
