### ISSUE TITLE
Check for longitudes outside [-180, 180] in geojson_to_wkt

### ISSUE THREAD

**Issue by j08lue** [sentinelsat/sentinelsat#236]
@valgur's suggestion in https://github.com/sentinelsat/sentinelsat/issues/232#issuecomment-420934957:

> I suggest we add a check in geojson_to_wkt() for coordinates outside the -180...180 range and throw an exception. This would be quite helpful since the response from server is totally useless in this case.

**Comment by Andrey-Raspopov** [comment]
Good morning!

I'd like to solve this issue, and will send you a PR in a couple of hours.

**Comment by j08lue** [comment]
This will also fix #218 in many cases, so please [`Close`](https://help.github.com/articles/closing-issues-using-keywords/) that with your PR.
