### ISSUE TITLE
Sentinel_3_cloudcoverage

### ISSUE THREAD

**Issue by geom16011** [sentinelsat/sentinelsat#243]
Is there any field that i could use like in Sentinel 2 cloudcoverage to sort out the relevant Sentinel 3 images (level 2 WFR products)?

**Comment by j08lue** [comment]
The generic answer is: If you can search for that on your DHUS of choice (e.g. https://scihub.copernicus.eu/dhus), then you also can with `sentinelsat`. Just do a query through the web interface and see from the query string what the key is called.

**Comment by j08lue** [comment]
This question is kind of out of scope of `sentinelsat` issues, since it is not a question of using or improving `sentinelsat` but concerning a particular database you are querying. 

I think a better recipient would be EUMETSAT support - maybe here https://www.eumetsat.int/website/home/ContactUs/index.html?

I hope you don't mind me closing this here, but I encourage the other maintainers to still comment if they by chance know an answer to your question.

**Comment by geom16011** [comment]
So in order to do that  in python (do a qeury and export the results in geojson) is the following correct 
I use a txt to read a geojson file and date to start (Date_s) looking to date end (Date_e) looking. 


import sentinelsat
from sentinelsat import SentinelAPI, read_geojson, geojson_to_wkt
import os
import pandas as pd
import numpy as np
import geojson
from geojson import Point, Feature,FeatureCollection, dump
import urllib
import urllib2
import requests
import requests
from requests.auth import HTTPBasicAuth
#E:\seo_dwarf\validation\platforms\MED\maria_Kremezi\nc\FLU2_PRES

path='E:/seo_dwarf/validation/platforms/MED/footprint_2016_2018/'
os.chdir(os.path.expanduser(path))

data = pd.read_table(path+'eikones.txt',delimiter='\t')
ID=(data[:]['ID'].values.tolist())
geojson=(data[:]['file'].values.tolist())
date_s=(data[:]['Date_s'].values.tolist())
date_e=(data[:]['Date_e'].values.tolist())


result_filename=[]
result_id=[]
result_lon=[]
result_lat=[]
Name=[]
results=[]
st=[]

for i in range(0,len(geojson)):
    print date_s[i]
    print date_e[i]
    if date_s[i]<20171129:
        api_url='https://codarep.eumetsat.int/'
    else:
        api_url='https://coda.eumetsat.int/'
    footprint = geojson_to_wkt(read_geojson(geojson[i]))
    api = SentinelAPI('giannismac', 'GvgDu2T9', api_url, show_progressbars=True)
    products = api.query(footprint, date=(str(date_s[i]), str(date_e[i])),producttype='OL_2_WFR___',cloudcoverpercentage=(0,80))
    t=api.to_geojson(products)
    with open(str(ID[i])+'.geojson', 'w') as f:
        dump(t, f)

**Comment by j08lue** [comment]
man, you posted your password.

**Comment by Fernerkundung** [comment]
@geom16011 We can't tell you if that is "correct", since we do not know what your expected outcome is.

In any way - as this is not a technical issue of the underlying `sentinelsat` software I would kindly ask you to seek help in a more general forum, e.g. https://gis.stackexchange.com/

**Comment by geom16011** [comment]
Thanks for your answer. My expected outcome is to get the footprint and do some spatial joins after. Also what i show is that when you use the field cloudverage (0,100) you get less footprints in comparison when you don t use it. This doesn t make sense in my mind.
