### ISSUE TITLE
Improve VCR recording - do not record bad responses?

### ISSUE THREAD

**Issue by j08lue** [sentinelsat/sentinelsat#247]
Thanks to @anujkumar93 for pointing out a way to delete bad vcrpy recordings (https://github.com/sentinelsat/sentinelsat/pull/86#issuecomment-435121322).

This issue is just to formally raise the question whether we should implement something like this - or not for now.

I have not experienced any problems with recording bad responses. But I have not been using vcrpy too much, just occasionally when writing new tests and then there were no problems. So from my experience, this is not needed right now.

What do you think, @valgur and @Fernerkundung?

**Comment by Fernerkundung** [comment]
I haven't had any problems with failed tests as well as my workflow was usually to ensure all tests pass and then record new cassettes.

Maybe we wait until kevin1024/vcrpy#205 is implemented?

If it is more of an issue than I have encountered I also don't see a lot of harm in including the proposed patch (i.e. it does not entail a lot of code complexity and technical debt).

**Comment by valgur** [comment]
From my experience, I'd say that the recordings are still very useful even when the tests fail. The query and response content usually stay the same even after fixing the test, but the cassettes speed up the test runs. I delete and re-record the affected cassette before committing. #453 also adds `clean_cassettes.sh` and speed ups the live test runs, so re-recording all cassettes is also a fairly convenient option now.
