### ISSUE TITLE
Rename product when downloading

### ISSUE THREAD

**Issue by AidanFNQ** [sentinelsat/sentinelsat#250]
Hi 

I am using the sample found online to search download Sentinel 2 products by tile.  I want to be able to rename the products when downloading to be just the tile id and the date e.g. 52JFS_20181119.  
From the documentation it looks like the file names on the server are used for the downloaded files.  Is it possible to rename the file in this example? 

Thankyou

```python
from collections import OrderedDict
from sentinelsat import SentinelAPI

api = SentinelAPI('???', '????')   

tiles = ['52JFS']   

query_kwargs = {
        'platformname': 'Sentinel-2',
        'producttype': 'S2MSI1C',
        'date': ('NOW-5DAYS', 'NOW')}    

products = OrderedDict()
path='???'    
for tile in tiles:   
    kw = query_kwargs.copy()
    kw['tileid'] = tile  # products after 2017-03-31
    pp = api.query(**kw)
    products.update(pp)

api.download_all(products,path)
```

**Comment by Fernerkundung** [comment]
Is there any particular reason for *not* renaming the files after their download?

**Comment by AidanFNQ** [comment]
Not particularly.  If it can be written in to the same script to rename the files after the download is completed that would be great.
Please forgive my ignorance, I am a complete beginner at this :)

**Comment by j08lue** [comment]
`api.download_all` returns a dictionary where the values are also dictionaries of product info. One of that info is the path and the rest is a lot of metadata. So it should be easy to do change your last line to

```python
import shutil
downloaded = api.download_all(products,path)

for item in downloaded.items():
    newpath = _construct_filename_from_metadata(item)
    shutil.move(item['path'], newpath)

```

**Comment by Fernerkundung** [comment]
@AidanFNQ Did the suggestion by @j08lue solve your issue?

**Comment by AidanFNQ** [comment]
@Fernerkundung and @j08lue thank you for your help.  I could not get your solution to work for me but I also figured out that renaming the files will not make my workflow much easier.  What I actually need to do is extract the .jp2 files and store them in a new folder.
