### ISSUE TITLE
Sentinel 3 SLSTR data access

### ISSUE THREAD

**Issue by SylvainLan** [sentinelsat/sentinelsat#251]
Hello, 

I am new to the world of satellites data and I am having quite a difficult time to investigate which solution is better for my need. 

I don't want to use a GUI to download my data as I will have to get some new quite often. I found satinelsat which I found very convenient and easy to understand. 

Therefore I wanted to get some data from SLSTR satellite as I am interested in the Land Surface Temperature data for my work purpose. 

However when I use the sentinelsat CLI, I can only get data from OCLI or SLAR products. 

Is this a normal behavior ? 

Thanks

**Comment by Fernerkundung** [comment]
Sentinel-3 SLSTR data is currently distributed via the S3 Pre-Ops Hub. You can query this with `sentinelsat`. A minimal example for a SLSTR data for the last day intersecting with Munich:

```python
from sentinelsat import SentinelAPI

api = SentinelAPI('s3guest', 's3guest', 'https://scihub.copernicus.eu/s3')
products = api.query(area="POINT (11.2836 48.0858)",
                     date=("NOW-1DAY", "NOW"),
                     instrumentshortname="SLSTR")

print(products)
```

**Comment by SylvainLan** [comment]
Thanks a lot @Fernerkundung for the answer, I could download some data. 

However I am having a hard time loading them on python, I have tried NetCDF4 or xarray but I get the following error : 
```
OSError: [Errno -101] NetCDF: HDF error
```
followed by the name of the file. 

Do you happen to know a good framework to open and manipulate sentinel 3 SLSTR data ? I am kind of lost in the jungle of libraries and acronyms to be honest.

**Comment by Fernerkundung** [comment]
For any geospatial data I would start out with GDAL. If that doesn't work SNAP should be able to read/convert/manipulate the data to your requirements.

**Comment by j08lue** [comment]
The S3 NetCDF data you should definitely reproject with SNAP/GPT and export to a more GIS-friendly format. They basically come as point data and the coordinates are in separate files - terrible to work with, even with a proper netCDF tool like `xarray`.

**Comment by SylvainLan** [comment]
Thanks a lot, I will try this out !

**Comment by georgeboldeanu** [comment]
Hey guys! I am new on Github so if my comment isn't in the appropiate topic i'll apologize from now. I try to make a script to download Sentinel-3, "SL_1_RBT__*" products.(example code below).

All clean and running good but i got a issue. I want to query everytime( e.g 30 days from now later) by yesterday date between certain times some like : "NOWT08:00:00-1, NOWT16:00:00-1". (i need only day thermal products).

Is there possibile? I mention that i am still learning .

``` python 
import sys
from sentinelsat import SentinelAPI, read_geojson, geojson_to_wkt
from datetime import date

api = SentinelAPI('s3guest', 's3guest', 'https://scihub.copernicus.eu/s3')

footprint = geojson_to_wkt(read_geojson('E:/Vectori/JSON/test1.geojson'))
products = api.query(footprint,
                     date=('NOW-1DAY', 'NOW'),
                     platformname='Sentinel-3',
                     producttype='SL_1_RBT___*',
                     instrumentshortname='SLSTR',
                     )```

**Comment by SylvainLan** [comment]
Hi, you can use the dates you want by specifying `date=('20181201', '20181202')` in your query, if you want e.g. data for the 1st of December, 2018.

**Comment by georgeboldeanu** [comment]
I knew this. What i want to mean above in my comment is that i will need to query only yesterday dates (if we are on 3 march of 2019 i still need to query the yesterday time) and i dont want everytime to write the date. When i use "now-1" the sentinel sat identifies automatically the date of the system and only queries yesterday.
