### ISSUE TITLE
how to make recurrent query for certain time of day?

### ISSUE THREAD

**Issue by j08lue** [sentinelsat/sentinelsat#254]
> Hey guys! I am new on Github so if my comment isn't in the appropiate topic i'll apologize from now. I try to make a script to download Sentinel-3, "SL_1_RBT__*" products.(example code below).
> 
> All clean and running good but i got a issue. I want to query everytime( e.g 30 days from now later) by yesterday date between certain times some like : "NOWT08:00:00-1, NOWT16:00:00-1". (i need only day thermal products).
> 
> Is there possibile? I mention that i am still learning .

``` python 
import sys
from sentinelsat import SentinelAPI, read_geojson, geojson_to_wkt
from datetime import date

api = SentinelAPI('s3guest', 's3guest', 'https://scihub.copernicus.eu/s3')

footprint = geojson_to_wkt(read_geojson('E:/Vectori/JSON/test1.geojson'))
products = api.query(footprint,
                     date=('NOW-1DAY', 'NOW'),
                     platformname='Sentinel-3',
                     producttype='SL_1_RBT___*',
                     instrumentshortname='SLSTR',
                     )
```

_Originally posted by @georgeboldeanu in https://github.com/sentinelsat/sentinelsat/issues/251#issuecomment-456715192_

**Comment by georgeboldeanu** [comment]
@j08lue Thanks for moving this. Sorry once again!

**Comment by j08lue** [comment]
No worries. So you want to query "yesterday between 08:00 and 16:00 UTC", right?

**Comment by georgeboldeanu** [comment]
Exactly. But i want to query everyday without changing the date (code). I want to automatize the process (at least to try).

**Comment by j08lue** [comment]
```python
import datetime
now = datetime.datetime.utcnow()
start = (now - datetime.timedelta(days=1)).replace(hour=8, minute=0, second=0, microsecond=0)
```

same for end date and then pass `date=(start, end)`

**Comment by j08lue** [comment]
or
```python
import datetime
now = datetime.datetime.utcnow()
date = [(now - datetime.timedelta(days=1)).replace(hour=h, minute=0, second=0, microsecond=0) for h in (8, 16)]
```
😄

**Comment by georgeboldeanu** [comment]
Thank you mate! Saved my day, I will remain gratefull! Cheers!

**Comment by georgeboldeanu** [comment]
close

**Comment by georgeboldeanu** [comment]
close #254

**Comment by Fernerkundung** [comment]
Closing since OP did not include further questions. Please comment if this should be reopened.
