### ISSUE TITLE
Error 503 Service unavailable: The retrieval of off line data is temporarily unavailable

### ISSUE THREAD

**Issue by andretheronsa** [sentinelsat/sentinelsat#255]
Thank you for the great package for me to integrate into my programs.

I am getting the error: "download failed with error HTTP status 503 Service Unavailable: ExpectedException : The retrieval of offline data is temporary unavailable, please try again later. Stopping run.

When I run api.download()

For the file File S1A_IW_SLC__1SDV_20160101T172537_20160101T172605_009303_00D708_1A22 product ID: 5464b5cf-e823-4c43-bd75-8369f9ec02cf

Sentinelsat gives this debug info: https://scihub.copernicus.eu:443 "GET /dhus/odata/v1/Products('5464b5cf-e823-4c43-bd75-8369f9ec02cf')/$value HTTP/1.1" 503 242

What does this mean and how can I fix it?

**Comment by valgur** [comment]
It's a server-side error and the error message means exactly what it says: the DataHub server is not currently not fully available, try again later. The best you can do is wait, keep an eye on the [news](https://scihub.copernicus.eu/news/) and consider using an [alternative data hub](https://github.com/Fernerkundung/awesome-sentinel#data-hubs-and-national-mirrors) in the mean time.

**Comment by andretheronsa** [comment]
Thank you and sorry for what looks like a lazy question from my side. 

I did not realise I can use any datahub with Sentinelsat! That is valuable knowledge for me to play with, thank you for the reply.
