### ISSUE TITLE
CLI tests fail due to changed reporting of product times

### ISSUE THREAD

**Issue by Fernerkundung** [sentinelsat/sentinelsat#262]
Timestamps of products queried with the CLI now report miliseconds instead of just seconds, breaking some of our CLI tests.

old: `Date: yyyy-MM-ddTHH:mm:ssZ`
new: `yyyy-MM-dd HH:mm:ss.SSS`

example for new format: `Product 44620814-8f51-4872-ac0e-bacc4d51db40 - Date: 2015-12-27T14:09:32.029Z, Instrument: MSI, Mode: , Satellite: Sentinel-2, Size: 316.33 MB`

example for failing test: `python -m pytest -v --vcr disable tests/test_cli.py::test_cloud_flag_url`

**Comment by valgur** [comment]
Should be fixed with #390.
