### ISSUE TITLE
Sentinel 5p support

### ISSUE THREAD

**Issue by craigmillernz** [sentinelsat/sentinelsat#269]
I would like to be able to download Sentinel-5p data from the TropOMI sensor, e.g. the product L2__SO2____.

Can support for this new data stream be added ?

**Comment by j08lue** [comment]
You can download any product using the Python API. 

But you are right, we should probably support Sentinel 5 through the CLI also.

**Comment by craigmillernz** [comment]
Thanks for the reply.  However when I try the following I get an empty OrderedDict.

```
api = SentinelAPI('username', 'password', api_url='https://scihub.copernicus.eu/apihub')
footprint = footprint = geojson_to_wkt(read_geojson('H:/TropOMI/NorthIsland.geojson'))
products = api.query(area = footprint, date = "[NOW-20DAYS TO NOW-19DAYS]", platformname='Sentinel-5p')
```
products
Out[15]: OrderedDict()

If I leave out the platformname arguement I get data returned in the orderedDict as expected (Sentinel 2 and 3 information only though).  If platformname=Sentinel-2 or Sentinel-3 then I also get data, but if platformname = Sentinel-5 (or Sentinel-5p) then I get nothing.

Can someone please point out what i'm doing wrong for Sentinel 5p products?
Thanks

**Comment by j08lue** [comment]
Sentinel 5 is only available from the pre-ops hub, I believe. So try with `SentinelAPI(user='s5pguest', password='s5pguest', api_url='https://s5phub.copernicus.eu/dhus')`.

**Comment by craigmillernz** [comment]
great, that works!  thank you.

**Comment by Fernerkundung** [comment]
Closed, as question of OP appears solved.

Please comment if this issue should be reopened.
