### ISSUE TITLE
Question about api.download_all(products)

### ISSUE THREAD

**Issue by sjdqbyitr178crs813tgbr8gsdufygeuy53** [sentinelsat/sentinelsat#274]
Does `api.download_all(products)` support asynchronous downloads or just load the scenes one by one?

**Comment by valgur** [comment]
`api.download_all(products)` does not have support for asynchronous programming using `asyncio` or even parallel downloads, for that matter.
I suppose you could create a custom version of `download_all()` if you have a need for this. It essentially does just
```python
for product_id in products:
    product_info = self.download(product_id, directory_path)
```
