### ISSUE TITLE
Searching based on place names

### ISSUE THREAD

**Issue by valgur** [sentinelsat/sentinelsat#276]
This is a feature idea I have had for some time but have not got around to implementing.

I propose we add a `--location` argument to the CLI that takes a natural-language place name as input. So instead of doing
```
sentinelsat -u <user> -p <password> -g <search_polygon.geojson> --sentinel 2 --cloud 30
```
you could do something like
```
sentinelsat -u <user> -p <password> --location Berlin --sentinel 2 --cloud 30
```

I would implement this by using one of the services supported via [geopy](https://github.com/geopy/geopy).

I would use intersection with the bounding box of the highest-ranked result as a search term in the SciHub API search query. Bounding box makes more sense for place names of larger regions, such as countries.
Maybe also support simple `lon,lat` or `lat,lon` directly, without a geocoding lookup. Which format to support is not a too obvious choice. Most geocoders use the `lat,lon` form but `lon,lat` would be more consistent with most GIS formats, including the GeoJSON files and WKT strings, so I'm leaning towards this one.

I would also add a small note of the location that was matched (e.g. its full place name) and its coordinates to the CLI output.
Adding this functionality to the sentinelsat's Python API as a separate function would make sense as well.

This feature would make sentinelsat much more straightforward to use for simple queries that only need products overlapping with some specific locations and would make it easier to provide examples in the readme and docs by not requiring a GeoJSON file to be created first.

**Comment by Fernerkundung** [comment]
This proposal would definitely steer `sentinelsat` towards more user friendliness. I like it! :+1: 

The requirements added by `geopy` appear to to only be `geographiclib`, so we should be fine on the front of an easy install process on all plattforms and minimal technical debt.

Regarding point location coordinates I would use the `lon,lat` format to stay consistent with GIS formats and also to make parsing into a POINT WKT easier.

I would also add that exposing this to the Python API would be good, e.g. in the form of a function `wkt_from_location_name`.

**Comment by j08lue** [comment]
Great enhancement idea.

Should we make the `geopy` and `geographiclib` dependencies optional, like we do with `geopandas`? Many API users might never need them. `geopy` is obviously much less heavy of a dependency than `geopandas`/`pandas`/`numpy`/`shapely`/whatnot, but still. Or would that get too complicated?

I also second the `wkt_from_location_name` idea.

**Comment by dwlsalmeida** [comment]
I could lend a hand if you guys give some steering along the way.

**Comment by Fernerkundung** [comment]
Please, do go ahead with this issue :+1: 

If you have any questions along the way either post them here, the linked Gitter channel or prepare a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) to discuss your changes.

**Comment by vlohiatest** [comment]
Hi!
Is work active on this one? Would love to contribute.

**Comment by dwlsalmeida** [comment]
@vlohiatest Not on my side, no. Unfortunately I have been pretty busy :/

_Sent from my Redmi Note 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vlohiatest** [comment]
So what i understood from the original proposal is : 

1. The user has the option to enter the natural name of the place/region and then we translate it through geopy to get the bounding box's (lat, lon) extents.
2. We query the Hub using these rectangular extents as the POLYGON footprint.
3. We get the results as JSON dictionary from the Hub and for each product: extract its POLYGON coordinates and calculate the intersection extent with the original bounding box (maybe use dice coefficient?) and rank the products accordingly.

If i have understood it right, can we use [shapely](https://shapely.readthedocs.io/en/latest/) as it supports intersection and union function over complex polygons?

**Comment by j08lue** [comment]
Ad 3 - do we need the ranking by intersection area? The query should only return results that do intersect in the first place and we could use the ranking part to power users.

In fact, not much "power" is needed. I guess when you get the query results as GeoDataFrame, you can just do like

```python
geom = sentinelsat.new_function_for_resolving_name_to_geometry('Luxemburg')
products = api.query(area=geom)
gdf = api.to_geodataframe(products)
gdf['intersecting_area'] = gdf.intersection(geom).area
```

or so...

**Comment by Fernerkundung** [comment]
> do we need the ranking by intersection area? The SciHub query should only return results that do intersect in the first place

The default query returns all products that intersect. For larger geographies the option to use "contains" as search strategy might be helpful.

Ranking by intersection area (point 3) will not be necessary. It also might not be very helpful, since the polygons returned by the SciHub refer to the full area of the product, including no-data areas. Meaning, that a larger intersection polygon does not necessarilz mean more valid pixels for the target region.

**Comment by vlohiatest** [comment]
Okay!
I will try to implement basic 'search by name' method on my fork and let you know.

**Comment by hk1997** [comment]
Hi, 
Can I help with this issue?

**Comment by j08lue** [comment]
Thanks, we have a PR on this (#310). Do you want help on fixing the latest review comments, @vlohiatest? Don't know whether that gives Hacktober-credits, though, @hk1997. 😉

**Comment by hk1997** [comment]
Haha..
Yup, I would love to to help in fixing those

**Comment by thomasyoung-audet** [comment]
Hello,
I've implemented a basic search by name inspired by vlohia's closed branch and created a PR. Could someone take a look at it?
