### ISSUE TITLE
parameter change between Dec,1 2016 to March, 31 2017 Not working properly

### ISSUE THREAD

**Issue by Fa7C0n** [sentinelsat/sentinelsat#277]
In sentinelsat api 0.13 (and also in 0.12) the [parameter change](https://sentinelsat.readthedocs.io/en/stable/api.html#search-sentinel-2-by-tile) between `Dec,1 2016 to March, 31 2017` is not working properly. (i.e) the api is not finding products when searched with `tileid` parameter but instead finds product when searched with `filename` parameter for the time period from `01-April-2017` to `16-May-2017`. It looks like the end date for [parameter change](https://sentinelsat.readthedocs.io/en/stable/api.html#search-sentinel-2-by-tile) is kind of rolling over to a month and a half after documented end date.

Also the end date for parameter change vary between tiles

tileid | ('20170406', '20170426') | ('20170426', '20170516')
------- | ----------------------- | --------------------------------
44QND | `tileid` :red_circle:   <br> `filename` :heavy_check_mark:    |  `tileid` :red_circle:   <br> `filename` :heavy_check_mark:
43QHD |  `tileid` :red_circle:   <br> `filename` :heavy_check_mark:  |  `tileid` :heavy_check_mark:    <br> `filename` :red_circle: 

## Parameters used

<details>
<summary> Query parameters not working</summary>

       param1 =  {
        'platformname': 'Sentinel-2', 
        'date': ('20170406', '20170426'), 
        'tileid': '44QND'
        }
       param2 = {
        'platformname': 'Sentinel-2', 
        'date': ('20170426', '20170516'), 
        'tileid': '44QND'
       }
</details>

<details>
<summary> Query parameters working</summary>

       param1 =  {
        'platformname': 'Sentinel-2', 
        'date': ('20170406', '20170426'), 
        'filename': '*_T44QND_*'
        }
       param2 = {
        'platformname': 'Sentinel-2', 
        'date': ('20170426', '20170516'), 
        'filename': '*_T44QND_*'
       }
</details>

## Questions

1) What is the exact end date for change between `tileid` and `filename`?
2) Does this change between tiles?

**Comment by j08lue** [comment]
@Fa7C0n Thanks for the detailed documentation of the issue. The dates I put in the docs for when the SciHub metadata changes and supports one or the other search pattern are just from my own experience and certainly not official in any way. It is an arbitrary inconsistency in the SciHub catalogue than we are trying to handle in some way.

I can imagine that this also differs from tile to tile, depending on whether SciHub production folks re-processed some of them later or not.

So I am afraid there is no official answer to when which pattern works for which tiles, so you have to keep testing until you find something that works for you.

We should note that in the docs, though.

**Comment by valgur** [comment]
Looks like a more reliable way of finding all matching older products might be to combine both queries:
```python
kw['raw'] = 'tileid:{tileid} OR filename:*_T{tileid}_*'.format(tileid=tile)
pp = api.query(**kw)
```
So, something like this https://scihub.copernicus.eu/apihub/search?q=tileid:43QHD%20OR%20filename:*_T43QHD_*&format=json
