### ISSUE TITLE
No 'Online' key in Collaborative Ground Segment OData response breaks _parse_odata_response

### ISSUE THREAD

**Issue by viktorbahr** [sentinelsat/sentinelsat#281]
I noticed that some Collaborative Ground Segments (i.e. https://collaborative.asi.it) do not return an `Online` key in their OData response.

Since #264 this key is required, otherwise [`_parse_odata_response`](https://github.com/sentinelsat/sentinelsat/blob/6a23ebfd53ca80634fb691fb9b887dd37964f934/sentinelsat/sentinel.py#L1128) will raise a `KeyError`.

This effectively breaks OData interaction with respective mirrors (`get_product_odata`, `download` etc).

After briefly looking over it, I would assume that a simple

```python
if 'Online' in product:
```

in `_parse_odata_response` could fix this.

Any thoughts on this? Should I create a PR?

**Comment by valgur** [comment]
Should replace `product['Online']` with `product.get('Online')` so it returns `None` if missing.
A PR is always welcome, sure.

**Comment by viktorbahr** [comment]
Okay, will submit a PR later.

**Comment by viktorbahr** [comment]
I'd like to create a test for this, too.
Can anyone point out a clever way to do this? My problem is:
- Only some collaborative ground segments return no `Online` key in OData response (ESA SentinelHub should __always__ contain it)
- So, recording a response from ESA SentineHub is out of the question, correct?
- Should I instead record a new casette using a different mirror (i.e. add an additional `api_kwargs` with different `api_url` that I'll only use for my `test_product_odata_short_with_missing_online_key` test)?
- The latter approach would require registering an account at this mirror using the `DHUS_USER`, `DHUS_PASSWORD` variables stored at Travis CI, right?
- Retention time for products at Collaborative Ground Segment mirrors is significantly shorter than at ESA SentinelHub. What happens if the product is dropped? Do we just pick a different product?

**Comment by j08lue** [comment]
Maybe you could also monkey-patch a SciHub response. Removing that one key should be simple enough. Maybe VCR.py even has a function for that, so it is easily repeatable. Too dirty?

**Comment by viktorbahr** [comment]
It was quite easy to remove the key-value pair from a prerecorded response using pyVCRs `before_record_response` hook.
Thanks for pointing me in this direction!

**Comment by Fernerkundung** [comment]
Closed after merging #282
