### ISSUE TITLE
S2MSIL2A in query_kwargs

### ISSUE THREAD

**Issue by diogocaribe** [sentinelsat/sentinelsat#288]
Is there possibility to search metadata from Sentinel 2 with S2MSI2A and S2MSI1C as product type as the same time?

See the third line of code below:
```python
query_kwargs = {
        'platformname': 'Sentinel-2',
        'producttype': '???', 
        'cloudcoverpercentage': (0, 100),
        'date': ('20160101', '20191201')} 

tiles = ['24LVJ']
products = OrderedDict()
for tile in tiles:
    kw = query_kwargs.copy()
    kw['tileid'] = tile 
    pp = api.query(**kw)
    products.update(pp)
```

**Comment by Fernerkundung** [comment]
What is the use case of searching both at the same time? You could search for both one after the other:

```python
query_kwargs = {
        'platformname': 'Sentinel-2',
        'cloudcoverpercentage': (0, 100),
        'date': ('20160101', '20191201')} 

tiles = ['24LVJ']
types = ['S2MSI2A', 'S2MSI1C']
products = OrderedDict()
for tile in tiles:
    for prodtype in types:
        kw = query_kwargs.copy()
        kw['tileid'] = tile 
        kw['producttype'] = prodtype
        pp = api.query(**kw)
        products.update(pp)
```

**Comment by diogocaribe** [comment]
I coded a script to forest monitoring in my state (https://github.com/diogocaribe/harpia). The script is able to run sentinel safe file from S2MSI1C, however I would like to change to S2MSI2A. In order to do it I need to look for both files yet. When routine works with 2A level, I will remove S2MSI1C. 

I run the code that you proposed and it didn't work. It returned one products for S2MSI2A empty. See product in picture. It hasn't nothing. It only work with Level 1C.

![image](https://user-images.githubusercontent.com/7991205/57414474-abbcf580-71ce-11e9-97eb-ac0774f17dea.png)

**Comment by j08lue** [comment]
@Fernerkundung's code works fine for me:

![image](https://user-images.githubusercontent.com/3404817/57435105-cc239900-723c-11e9-8699-2f7d24f323c4.png)

Please check whether you implemented it correctly.

**Comment by Fernerkundung** [comment]
> I run the code that you proposed and it didn't work. It returned one products for S2MSI2A empty. 

That is because for the tile '24LVJ' there are no L2A products. `sentinelsat` is behaving as expected and returning no products, because the search does not return any L2A products.

![Screenshot from 2019-05-09 09-58-30](https://user-images.githubusercontent.com/1621864/57437026-33dbe300-7241-11e9-8cf5-2a3a6a1cf4e7.png)

**Comment by diogocaribe** [comment]
If I look for 2A with polygon it return many files as 2A. As far as I know all Sentinel 2 is available as 2A products. Is it a kind of bug?

![image](https://user-images.githubusercontent.com/7991205/57441288-fdda3700-721f-11e9-94b2-87668c23f7f7.png)

**Comment by diogocaribe** [comment]
> > I run the code that you proposed and it didn't work. It returned one products for S2MSI2A empty.
> 
> That is because for the tile '24LVJ' there are no L2A products. `sentinelsat` is behaving as expected and returning no products, because the search does not return any L2A products.
> 
> ![Screenshot from 2019-05-09 09-58-30](https://user-images.githubusercontent.com/1621864/57437026-33dbe300-7241-11e9-8cf5-2a3a6a1cf4e7.png)

If I look for 2A with polygon it return many files as 2A. As far as I know all Sentinel 2 is available as 2A products. Is it a kind of bug?

![image](https://user-images.githubusercontent.com/7991205/57441779-03844c80-7221-11e9-9335-90cdf0918ce8.png)

**Comment by j08lue** [comment]
Not a bug as such, but the SciHub data catalogue is veery inconsistent. So searching by tile name might work sometimes and sometimes not. Your safest option is to search by geometry instead, like you do above.

**Comment by diogocaribe** [comment]
> Not a bug as such, but the SciHub data catalogue is veery inconsistent. So searching by tile name might work sometimes and sometimes not. Your safest option is to search by geometry instead, like you do above.

Ok. What a pity! Thanks for your attention and help me.

**Comment by matthew-gaddes** [comment]
I just stumbled upon this thread and found it immensely helpful; perhaps the gist of it could be added to the documentation somewhere?  I was searching by tileid and processing level (or producttype) with calls like this and only finding 1C data, despite the 2A data being on SciHub:

<code> 
test1 = api.query(tileid = tile, platformname = 'Sentinel-2', processinglevel = 'Level-1C') <p>
test2 = api.query(tileid = tile, platformname = 'Sentinel-2', processinglevel = 'Level-2A')
</code>

At the suggestion of this thread, I switched to searching using a geojson file (simply set to the lon lat of the centre of the tile of interest), and was able to successfully download both the 1C and the 2A data:

<code>
footprint = geojson_to_wkt(read_geojson('./test2.geojson'))    <p>
products = api.query(footprint, platformname='Sentinel-2', producttype ='S2MSI2A')
</code>

Anyhow, thanks j08lue!
