### ISSUE TITLE
Check query length in CLI and warn user

### ISSUE THREAD

**Issue by Fernerkundung** [sentinelsat/sentinelsat#290]
Warn users of the CLI that complex polygons might cause uncertain responses/crashes from SciHub. This entails minor additions to the CLI and the documentation.

* check if the query exceeds the proposed length limit with [api.check_query_length()](https://sentinelsat.readthedocs.io/en/stable/api.html#sentinelsat.SentinelAPI.check_query_length)
* provide a warning to the user that the query is complex and might cause a bad SciHub response
* extend documentation for issues caused by too complex polygons in queries (probably under [common issues](https://sentinelsat.readthedocs.io/en/stable/common_issues.html))

As proposed by @valgur in #289 after the report by @drnextgis.

**Comment by t-williamss** [comment]
I am interested in solving this

**Comment by t-williamss** [comment]
In python:
while api.check_query_length(query) != 1.0:
    pass
print("Query is complex and may cause a bad SciHub response.")

**Comment by j08lue** [comment]
Thanks @t-williamss. but no, that is certainly not how to do this. Is this a joke?

**Comment by j08lue** [comment]
Thanks, @ipbrennan90, please do take it.

**Comment by t-williamss** [comment]
Are there any other issues I can help out on?

**Comment by hk1997** [comment]
Hi,
I am interested in solving this issue.

**Comment by j08lue** [comment]
@ipbrennan90, are you working on this already?

**Comment by ipbrennan90** [comment]
I have not. I apologize for the delay. If someone has more time on there
hands and is interested  they may take it.

**Comment by j08lue** [comment]
Fine, thanks @ipbrennan90. You are welcome go take it, @hk1997.
