### ISSUE TITLE
For sentinel 2 product, the footprint of product is not corresponding to the valid pixel range

### ISSUE THREAD

**Issue by zhangbin0917** [sentinelsat/sentinelsat#292]
For sentinel 2 product, why the footprint of product is not corresponding to the valid pixel range?
for example,  the footprint of the prroduct S2A_MSIL1C_20160110T051202_N0201_R019_T44RMV_20160110T051323 is  'MULTIPOLYGON (((79.95601097 30.64062679, 81.10185964 30.64477874, 81.10292414 31.63550563, 79.94510301 31.63118915, 79.95601097 30.64062679)))', but the valid pixel range is very small.

**Comment by Fernerkundung** [comment]
What do you mean by "valid pixel range"? The area of non-masked pixels? Something from the metadata manifest.xml?

**Comment by zhangbin0917** [comment]
I mean that "valid pixel range" is bottom right corner of this image I show you. 
And the black pixels in the image is invalid pixels, which is invalid information.
Why the footprint of product is not corresponding to the valid pixel range?

![无标题](https://user-images.githubusercontent.com/34292687/58298984-16e20b00-7e10-11e9-8c1d-b6690e569b1d.png)

But in another product, the footprint of product is corresponding to the valid pixel range. I want to ask why.

![无标题2](https://user-images.githubusercontent.com/34292687/58299400-b05dec80-7e11-11e9-971a-140548f3b896.png)

**Comment by j08lue** [comment]
I guess it is a matter of which processing baseline the product has. Old products (like the upper 2016 one) just have a box. Newer ones have something actually useful.

**Comment by Fernerkundung** [comment]
I re-checked both products. The footprint rendered by `sentinelsat` is the one provided in the metadata. 

Nothing we can do on our side. You can reach Copernicus support at eosupport@copernicus.esa.int to ask ,if they can provide more info on or fix this inconsistency.
