### ISSUE TITLE
Download fail from colhub

### ISSUE THREAD

**Issue by ingararntzen** [sentinelsat/sentinelsat#294]
I'm using sentinelsat to download products from a Norwegian collaborative hub (https://colhub.met.no) and download is now failing because the sentinelsat code expects query responses to include the 'Online' property. It seems my Norwegian hub has not yet upgraded to include this field. Would it perhaps be possible to relax the requirement?

 from 

```python
'Online': product['Online'],
``` 
to 

```python
'Online': product.get('Online', True),
``` 
Here is the error message

```
KeyError                                  Traceback (most recent call last)
<ipython-input-9-01076acaceca> in <module>
----> 1 api.download(uuid)

/miniconda3/envs/sentinelsat/lib/python3.7/site-packages/sentinelsat/sentinel.py in download(self, id, directory_path, checksum)
    491             If the MD5 checksum does not match the checksum on the server.
    492         """
--> 493         product_info = self.get_product_odata(id)
    494         path = join(directory_path, product_info['title'] + '.zip')
    495         product_info['path'] = path

/miniconda3/envs/sentinelsat/lib/python3.7/site-packages/sentinelsat/sentinel.py in get_product_odata(self, id, full)
    426                                     timeout=self.timeout)
    427         _check_scihub_response(response)
--> 428         values = _parse_odata_response(response.json()['d'])
    429         return values
    430 

/miniconda3/envs/sentinelsat/lib/python3.7/site-packages/sentinelsat/sentinel.py in _parse_odata_response(product)
   1126         'footprint': _parse_gml_footprint(product["ContentGeometry"]),
   1127         'url': product['__metadata']['media_src'],
-> 1128         'Online': product['Online'],
   1129         'Creation Date': _parse_odata_timestamp(product['CreationDate']),
   1130         'Ingestion Date': _parse_odata_timestamp(product['IngestionDate']),

KeyError: 'Online'

```

**Comment by j08lue** [comment]
Sorry about thinking SciHub only and breaking your stuff. That is a good fix. Will you make a PR for that @ingararntzen?

**Comment by Fernerkundung** [comment]
This should be fixed with #282.

Could you please test with the current master branch

```bash
git clone https://github.com/sentinelsat/sentinelsat.git
cd sentinelsat
pip install .
```

**Comment by j08lue** [comment]
I used `sentinelsat` with `colhub.met.no` in the last weeks and it worked fine with current `master`. Closing this.

**Comment by mstrahl** [comment]
I am not sure if it really works as I got still this mistake with the newest git pulled in version:
(/smartmet/data/conda/s2m) [who@mosaiikki.fmi.fi sat]$ sentinelsat --url https://colhub.met.no/ -u mstrahl -p XXX -g fp-pta-s1-grd-mosaic.geojson -s 20190821 -e 20190831 -q 'orbitdirection=Ascending' --producttype GRD -d
Querying products: 100%|████████████████████████████████████████████████████████████████████████████████| 305/305 [00:01<00:00, 196.54 products/s]
Found 305 products
Will download 305 products using 2 workers
Traceback (most recent call last):
  File "/smartmet/data/conda/s2m/bin/sentinelsat", line 10, in <module>
    sys.exit(cli())
  File "/smartmet/data/conda/s2m/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/smartmet/data/conda/s2m/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/smartmet/data/conda/s2m/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/smartmet/data/conda/s2m/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/smartmet/data/conda/s2m/lib/python3.7/site-packages/sentinelsat/scripts/cli.py", line 168, in cli
    product_infos, triggered, failed_downloads = api.download_all(products, path)
  File "/smartmet/data/conda/s2m/lib/python3.7/site-packages/sentinelsat/sentinel.py", line 690, in download_all
    raise next(iter(x.exception() for x in dl_tasks if x.exception()))
  File "/smartmet/data/conda/s2m/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/smartmet/data/conda/s2m/lib/python3.7/site-packages/sentinelsat/sentinel.py", line 761, in _download_online_retry
    if self.is_online(product_info['id']):
  File "/smartmet/data/conda/s2m/lib/python3.7/site-packages/sentinelsat/sentinel.py", line 457, in is_online
    raise SentinelAPIError('Could not verify whether product {} is online'.format(id), r)
sentinelsat.sentinel.SentinelAPIError: HTTP status 500 Internal Server Error: Could not verify whether product 248794a6-c8c2-4a64-9d04-dfcccd40d463 is online

**Comment by mstrahl** [comment]
It is relevant to use colhub with Sentinel 1 data, not just any data, to make this appear. Did J08lue get Sentinel 1 data?

**Comment by j08lue** [comment]
@mstrahl `Could not verify whether product <id> is online` is a different issue, already raised under #311 for a different hub. The issue mentions a little hack that you can use until we fixed this.
