### ISSUE TITLE
Enforce automatic code formatting

### ISSUE THREAD

**Issue by Fernerkundung** [sentinelsat/sentinelsat#295]
Should we enforce automatic code formatting for `sentinelsat` code contributions and the existing code base?

This discussion is sparked by the [code review](https://github.com/sentinelsat/sentinelsat/pull/287#discussion_r280974158) of PR #287. 

As I see it the  inclusion of an automatic code formatter into our CI pipeline would be the best option to have a consistent code base. Further potential improvements are smaller diffs, no formatting discussion on PRs and easier integration of PRs.

On the technical side we would need to discuss which code style to follow and which autoformatter to include into the Travis CI pipeline. Popular options would be:
- [black](https://github.com/python/black)
- [flake8](https://github.com/PyCQA/flake8)
- [autopep8](https://github.com/hhatto/autopep8)
- [yapf](https://github.com/google/yapf)

As far as requirements go, I would argue that it should adhere closely to PEP8, allow numpy docstrings, be able to include into multiple editors and has to be able to integrate into Travis CI.

**Comment by j08lue** [comment]
Yes. I opt for default `flake8` / PEP8 with line length 100. We can make it a check on PRs that runs before all the tests so it fails right away. Whether people use `black` to match the style is up to them. I don't think we should auto-format code as part of CI (if that at all is possible).

**Comment by j08lue** [comment]
done
