### ISSUE TITLE
footprint = geojson_to_wkt(read_geojson('map.geojson'))

### ISSUE THREAD

**Issue by rohitsharma1415** [sentinelsat/sentinelsat#298]
File "C:\Users\IDR\AppData\Local\Programs\Python\Python37\lib\site-packages\sentinelsat\sentinel.py", line 885, in read_geojson
    with open(geojson_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'map.geojson'

Any Idea?
I am having map.geojson in the same folder

**Comment by j08lue** [comment]
> I am having map.geojson in the same folder

In which folder? Your current working directory? 

If you want to use relative paths (without the full path like `C:\path\to\my\data`), you have to make sure Python's working directory is where you think it is. Check

```python
import os
print(os.getcwd())
```

and if you want Python to always be where your script file is, try

```python
import os
os.chdir(os.path.dirname(__file__))
```

or invoke your script from that directory, like

```cmd
cd C:\path\to\my\data
python my-script.py
```
