### ISSUE TITLE
Error please help

### ISSUE THREAD

**Issue by rohitsharma1415** [sentinelsat/sentinelsat#299]
from sentinelsat.sentinel import SentinelAPI, read_geojson, geojson_to_wkt
from: can't read /var/mail/sentinelsat.sentinel

**Comment by j08lue** [comment]
Are you kidding me? `/var/mail`? 😄

Ah, I get it. You are typing this right into your terminal. You need to run this code in Python.

Or, if you want a command-line interface, type `sentinelsat --help` (assuming that you installed it first with `pip install sentinelsat`, perhaps `pip install --user sentinelsat`).
