### ISSUE TITLE
  from . import __version__ as sentinelsat_version

### ISSUE THREAD

**Issue by rohitsharma1415** [sentinelsat/sentinelsat#300]
File "/home/rohit/Downloads/sentinelsat-master/sentinelsat/sentinel.py", line 24, in <module>
    from . import __version__ as sentinelsat_version

ImportError: cannot import name '__version__' from '__main__' (/home/rohit/Downloads/sentinelsat-master/sentinelsat/sentinel.py)

**Comment by valgur** [comment]
Are you trying to run `python sentinel.py` directly? That won't work. Do `pip install .` in the root directory and then use `sentinelsat` command instead.

**Comment by rohitsharma1415** [comment]
Worked Thank you I tried but it was the error due to corrupt file
