### ISSUE TITLE
Empty Geo Data Frame 

### ISSUE THREAD

**Issue by rohitsharma1415** [sentinelsat/sentinelsat#301]
```python
products = api.query(footprint, date = ('20181216', date(2018, 12, 16)),platformname = 'Sentinel-2',cloudcoverpercentage = (0, 30))
api.download_all(products)
Out[12]: (OrderedDict(), OrderedDict(), set())api.to_geojson(products)
Out[13]: {"features": [], "type": "FeatureCollection"}api.to_geodataframe(products)
Out[14]: Empty GeoDataFrame
Columns: []
Index: []
```

IDE: pycharm 
Not able to download the Zip files 
Can you also explain syntax of the product ID to enter in command 
api.get_product_odata(<product_id>)

**Comment by j08lue** [comment]
>  Not able to download the Zip files

Which zip files? `products` appears to be empty, which means your query did not return any results. Probably because your start and end date is the same. Just different formatting (why tho??). Change the second date to `20181217` and then before you continue, check that `products` is not empty.

**Comment by Fernerkundung** [comment]
@rohitsharma1415 please consider using https://gitter.im/sentinelsat for help on the usage of `sentinelsat`. Opening several Github issues for your questions is not the intended use case of Github.
