### ISSUE TITLE
Error when trying to download from Norweigan mirror: SentinelAPIError: HTTP status 404 Not Found: InvalidKeyException

### ISSUE THREAD

**Issue by bro076** [sentinelsat/sentinelsat#302]
Hi,

I am trying to download the Sentinel 2 images over an area of Western Norway. Since the ESA archive is very slow, I am trying to use the Norwegian mirror for Sentinel instead (https://colhub.met.no/#/home).

I manage to get an excel file of the images suitable using the following code (username & password taken out):

    from sentinelsat import SentinelAPI, read_geojson, geojson_to_wkt
    import pandas as pd
    import logging

    logging.basicConfig(format='%(message)s', level='INFO')
    api = SentinelAPI('username', 'password', 'https://colhub.met.no/#/home')
    dates = '[2018-01-01T00:00:00.000Z TO 2019-07-01T00:00:00.000Z]'
    orbit = '117'
    footprint = geojson_to_wkt(read_geojson("P:\Ben\hordaland_outline_simp.json"))
    cloud = '[0 TO 50]'

    products = api.query(footprint, dates,platformname='Sentinel-2',cloudcoverpercentage = cloud, producttype = 'S2MSI1C')

    # convert to Pandas DataFrame
    products_df = api.to_dataframe(products)
    ##products_df_sorted = products_df.sort_values(['beginposition', 'orbitdirection'], ascending=[True, True])

    file_name = r"G:\Data\Raw\Sentinel\Sentinel2\1_Raw_L2A\Sentinel2_images.xlsx"
    # Create a Pandas Excel writer using XlsxWriter as the engine.
    writer = pd.ExcelWriter(file_name, engine='xlsxwriter')
    # Convert the dataframe to an XlsxWriter Excel object.
    products_df.to_excel(writer, sheet_name='Sheet1')
    # Close the Pandas Excel writer and output the Excel file.
    writer.save()
    print "Excel file with images to be processed has been written to " + file_name

Then I try to download using

    api.download_all(products_df)

But I get the error:

        Traceback (most recent call last):
      File "C:\Users\bro076\AppData\Roaming\Python\Python27\site-packages\sentinelsat\sentinel.py", line 602, in download_all
        product_info = self.download(product_id, directory_path, checksum)
      File "C:\Users\bro076\AppData\Roaming\Python\Python27\site-packages\sentinelsat\sentinel.py", line 493, in download
        product_info = self.get_product_odata(id)
      File "C:\Users\bro076\AppData\Roaming\Python\Python27\site-packages\sentinelsat\sentinel.py", line 427, in get_product_odata
        _check_scihub_response(response)
      File "C:\Users\bro076\AppData\Roaming\Python\Python27\site-packages\sentinelsat\sentinel.py", line 1027, in _check_scihub_response
        raise api_error
    SentinelAPIError: HTTP status 404 Not Found: InvalidKeyException : Invalid key (processinglevel) to access Products
    There was an error downloading processinglevel

**Comment by Fernerkundung** [comment]
Related to #294.

This seems to be related to Norwegian Hub using an older version of the DHuS software. We need to figure out a way to handle the differences in the DHuS versions employed by the hubs.

In the meantime you could try using an older version of `sentinelsat`, which was tested against older DHuS versions. You can install a specific version with e.g. `pip install sentinelsat==0.12`.

**Comment by bro076** [comment]
Ah that fixed it at least, thank you very much!

**Comment by rubenfv** [comment]
I looks like the 'Online' field in OData is missing in the Norweigian mirror and this raises an error. 
Apparently this was resolved by setting the defaults to True in a recent bug: #281

**Comment by Fernerkundung** [comment]
Great catch @rubenfv - I completely forgot about the fix.

@bro076 You could test if the error can be removed by using the current master branch.

```bash
git clone https://github.com/sentinelsat/sentinelsat.git
cd sentinelsat
pip install .
```

**Comment by bro076** [comment]
I already have my 1000 images downloading at lightning speed, but I will try this afterwards. Thank you for the feedback!
