### ISSUE TITLE
request to codarep.eumetsat.int fails with complex polygon

### ISSUE THREAD

**Issue by geom16011** [sentinelsat/sentinelsat#303]
Trying to download images from 'https://codarep.eumetsat.int/' using sentinelsat getting the following error 
```
  File "F:\seo_dwarf\test\scripts\code_1\seo_dwarf.py", line 457, in finding_footprint
    products = api.query(footprint, date=(str(Date[0][0]), str(Date[0][1])), producttype='OL_2_WFR___')
  File "C:\Python_27_1\lib\site-packages\sentinelsat\sentinel.py", line 134, in query
    response, count = self._load_query(query, formatted_order_by, limit, offset)
  File "C:\Python_27_1\lib\site-packages\sentinelsat\sentinel.py", line 242, in _load_query
    products, count = self._load_subquery(query, order_by, limit, offset)
  File "C:\Python_27_1\lib\site-packages\sentinelsat\sentinel.py", line 272, in _load_subquery
    _check_scihub_response(response)
  File "C:\Python_27_1\lib\site-packages\sentinelsat\sentinel.py", line 890, in _check_scihub_response
    raise api_error
sentinelsat.sentinel.SentinelAPIError: HTTP status 502 Bad Gateway: 
# Bad Gateway

The proxy server received an invalid response from an upstream server.  

* * *

Apache/2.2.31 (CentOS) Server at codarep.eumetsat.int Port 443
```

Any ideas?

**Comment by j08lue** [comment]
If you don't mind, please share the full query (including your footprint geometry or another one that fails), so we can try to reproduce the issue.

**Comment by geom16011** [comment]
The geojson using is the following 
[aoi.zip](https://github.com/sentinelsat/sentinelsat/files/3442783/aoi.zip)

The dates i am interested is the following from '20160429'  to  '20161210'. and the quey is the following            
 footprint = geojson_to_wkt(read_geojson(aoi))
  products = api.query(footprint, date=('20160429'  ,  '20161210'), producttype='OL_2_WFR___')

**Comment by Fernerkundung** [comment]
Your AOI is a too complex polygon. Most instances of SciHub fail when you provide an AOI with more than 500 vertices.

Simplify your polygon to include the coastal area and try again.

**Comment by j08lue** [comment]
> Your AOI is a too complex polygon.

Thought so...
