### ISSUE TITLE
conda-forge submission

### ISSUE THREAD

**Issue by Thingus** [sentinelsat/sentinelsat#306]
Hi maintainers
I'm putting a library up on Conda-Forge, and it contains this library as a dependency. Are you alright with my using conda skeleton to submit this repository to conda-forge? I'm happy to list myself as the maintainer, and it includes all references back to this repository.
The library in question:
https://github.com/clcr/pyeo
The conda forge pull request:
conda-forge/staged-recipes#8972

**Comment by j08lue** [comment]
With such a simple library as ours, what is the benefit of adding it to `conda-forge`? In `conda` environments, you can specify `pip` dependencies - can't you do that for `conda` packages, too?

**Comment by Thingus** [comment]
For standard environment.yml files, yes; and this is exactly what I was doing. But for adding a library to conda-forge so that it can be installed via `conda install`, all the dependencies must also be on conda-forge - at least, as far as I can tell from the docs.

**Comment by j08lue** [comment]
Right, I can see that https://conda-forge.org/docs/maintainer/adding_pkgs.html#avoid-external-dependencies.

> Are you alright with my using conda skeleton to submit this repository to conda-forge?

Sure, I don't see any reason not to do that. Great initiative! Don't you agree, @Fernerkundung and @valgur?

**Comment by Fernerkundung** [comment]
Of course, go ahead. Our License explicitly permits such reuse and dependency scenarios. Thanks for asking though!

**Comment by Thingus** [comment]
Much obliged!
