### ISSUE TITLE
Sentinel 2 Query Only Returns L1C Products?

### ISSUE THREAD

**Issue by sscullen** [sentinelsat/sentinelsat#313]
Using sentinelsat.query with the following parameters:

{
"platformname": "Sentinel-2",
"date":   ('20190904', '20190905'),
"tileid": '32UPV',
}

Yields only L1C products. After trying to verify the products returned in the Open Access hub web interface, I determined, if you use the `tileid` parameter, only L1C products are returned there. So I can confirm it's not a bug in sentinelsat, its behaviour inherited from the Copernicus API. A work around is to search using `filename:f'*_T{tile}_*'`.

I'm posting this issue because I'm not sure where I would post this so that the API is fixed. If anyone has any recommendations for where to report this behaviour I'd appreciate it.

**Comment by j08lue** [comment]
Thanks for reporting.

> I'm posting this issue because I'm not sure where I would post this so that the API is fixed.

You can send an email to eosupport@copernicus.esa.int . I don't suppose it is something they can/will fix, though.
