### ISSUE TITLE
Downloads corrupt/invalid zip files

### ISSUE THREAD

**Issue by goriliukasbuxton** [sentinelsat/sentinelsat#314]
after download getting errors unzipping zip files:
"Can not open the file as [zip] archive
Is not archive"

sentinelsat version 0.13
data: Sentinel5p

**Comment by j08lue** [comment]
Please see #270. The Sentinel 5 files are not actually zip files, but netCDF. Rename them to `<name>.nc` and you can read them. Subscribe to the other issue to get notified when we fixed this.
