### ISSUE TITLE
Failed authenitcation for coda.eumetsat.int

### ISSUE THREAD

**Issue by nishadhka** [sentinelsat/sentinelsat#315]
Getting message related to failed authentication for url https://coda.eumetsat.int, such as 
```
sentinelsat.sentinel.SentinelAPIError: HTTP status 401 Unauthorized: 
# HTTP Status 401 - Full authentication is required to access this resource

 **type** Status report

 **message** _Full authentication is required to access this resource_

 **description** _This request requires HTTP authentication._

* * *

### Apache Tomcat/8.0.36
```
However scihub url works perfectly, https://scihub.copernicus.eu/dhus. Contrary to scihub, eumetsat web browser (login page) access always directed through eumetsat environmental observation portal.  such as the link url is https://eoportal.eumetsat.int/userMgmt/login.faces?goto=http://codarep.eumetsat.int/#/home.

Is this some service need to be enabled for my account or something else, many thanks.

**Comment by j08lue** [comment]
Your SciHub account does NOT work on CODA - if that is what you are trying to do. You need to create a separate account on CODA, then queries against `--url https://coda.eumetsat.int` will work.

**Comment by nishadhka** [comment]
Thanks for the reply, I have a separate account with eumetsat apart from scihub. Actually I am not able to access the link ```https://coda.eumetsat.int``` directly as in the case of ```https://scihub.copernicus.eu/dhus``` even in web browser. I get redirection to eumetsat page for authentication 
/home/bulbul/Pictures/eumetsat1.png
/home/bulbul/Pictures/eumetsat2.png

I can't make a account specifically in CODA as well

**Comment by j08lue** [comment]
The EUMETSAT account was the one I meant. So if that one works when you log in on the page you show in the screen dump, it should also work when using the API. The redirect you see in the browser is not a problem.

**Comment by nishadhka** [comment]
But API gives the error, the code being used is as follows, the error raised only for https://coda.eumetsat.int/https://codarep.eumetsat.int/, not for https://scihub.copernicus.eu/dhus.
tried with using http and still same error. 
```
from sentinelsat.sentinel import SentinelAPI, read_geojson, geojson_to_wkt
from datetime import date

# connect to the API
#api = SentinelAPI('username', 'password', 'https://scihub.copernicus.eu/dhus')
api = SentinelAPI('different-username', 'different-password', 'https://coda.eumetsat.int')

#api = SentinelAPI('username', 'password', 'https://codarep.eumetsat.int/')
# # download single scene by known product id
# api.download(<product_id>)

# # search by polygon, time, and Hub query keywords

# footprint='POLYGON((0 0,1 1,0 1,0 0))'
# products = api.query(footprint,
#                  date=('20180901', date(2018, 9, 5)),
#                  area_relation='Intersects',
#                  platformname='Sentinel-2',
#                 cloudcoverpercentage=(0, 10))



footprint='POLYGON((72.77 1.6 ,86.84 13.56, 72.77 13.56,72.77 1.6 ))'
products = api.query(footprint,
                 date=('20190928', '20190929'),
                 area_relation='Intersects',
                 platformname='Sentinel-3')
```

**Comment by j08lue** [comment]
If you are sure that your credentials are correct and yet rejected by the endpoint, consider [writing to CODA/EUMETSAT](https://www.eumetsat.int/website/home/ContactUs/index.html) and asking what is going on. Not much else we can do...

**Comment by nishadhka** [comment]
Strangely certain characters in API password affecting the API access. Account password change solved the error. Need to edit the code with product name to avoid related error, as follows.
```
from sentinelsat.sentinel import SentinelAPI, read_geojson, geojson_to_wkt
from datetime import date
# connect to the API
api = SentinelAPI('different-username', 'simple-different-password', 'https://coda.eumetsat.int')
footprint='POLYGON((72.77 1.6 ,86.84 13.56, 72.77 13.56,72.77 1.6 ))'
products = api.query(footprint,
                 date=('20190928', '20190929'),
                producttype='OL_2_WFR___')
```
This solves the issue, thanks

**Comment by j08lue** [comment]
> Strangely certain characters in API password affecting the API access.

😨

**Comment by nishadhka** [comment]
This is not concern of sentinelsat. The error is same in accessing using aria2c, based on this https://coda.eumetsat.int/manual/CODA-user-manual.pdf

**Comment by Fernerkundung** [comment]
Page 56 of the CODA user manual:

> Password must NOT contain any of the following special characters: ~ ! @ # $ % ^ & * _ - + = ` | \ ( ) { } [ ] : ; " ' < > , . ? /

They have to be kidding?! :confused:
