### ISSUE TITLE
Problem querying Sentinel-2 partial coverage tiles using footprint

### ISSUE THREAD

**Issue by gthuser** [sentinelsat/sentinelsat#316]
I want to query all images for a certain tile, including those partly covered with image data (for example, sometimes only part of the tile is covered with an image from the adjacent orbit and the rest of the tile is black background). I use a geojson file to define the query. The polygon is shown below:
 
![Untitled](https://user-images.githubusercontent.com/55988040/65886862-c07c6e80-e3a5-11e9-83e7-3894e53fba0e.png)

The problem is that when I set the 'area_relation' keyword to 'Contains' these partly covered products are not retrieved. When I set the 'area_relation' keyword to 'Intersects' they are retrieved but in addition to them, the query returns the adjacent tile to the east.       
My code is:
```
footprint = geojson_to_wkt(read_geojson('D:\\Box.geojson'))
products = api.query(footprint,
                     date=('20171015', '20180615'),
                     platformname='Sentinel-2',
                     cloudcoverpercentage=(0, 100),
                     producttype='S2MSI2A',
                     area_relation='Contains',
                     order_by='beginposition')

products_df = api.to_dataframe(products)
print(products_df)
```
How can I fix this?

**Comment by valgur** [comment]
You could try filtering the query further by `tileid`, perhaps, where the tile ID is the `Txxxxx` part at the the end of the product name.

**Comment by j08lue** [comment]
There is not much for us to change about what the API returns for your query, I am afraid. But you could follow @valgur's advice or get the metadata as geodataframe and then filter like

```python
gdf = api.to_geodataframe(products)
gdf = gdf[gdf.intersects(your_query_geometry)]
```

**Comment by gthuser** [comment]
@j08lue I tried with:
```
gdf = api.to_geodataframe(products)
gdf = gdf[gdf.intersects(footprint)]
```
but get this error message:
```
Traceback (most recent call last):
  File "sentinelsat_data_download_v2.py", line 31, in <module>
    gdf = gdf[gdf.intersects(footprint)]
  File "C:\Anaconda3\envs\geo\lib\site-packages\geopandas\base.py", line 404, in intersects
    return _binary_op('intersects', self, other)
  File "C:\Anaconda3\envs\geo\lib\site-packages\geopandas\base.py", line 90, in _binary_op
    raise TypeError(type(this), type(other))
TypeError: (<class 'geopandas.geodataframe.GeoDataFrame'>, <class 'str'>)
```
Maybe the "footprint" variable which I get with "geojson_to_wkt" in the first post is not the right type?

Ant also, @valgur, how to filter the query by tileid?

**Comment by j08lue** [comment]
Your `footprint` must be a `shapely` geometry. Try `shapely.geometry.shape(json.loads(footprint))`, if your `footprint` is a GeoJSON string or google around for how to read from WKT.

**Comment by valgur** [comment]
Actually, both swaths probably share the same tile ID here so my initial suggestion would not help anyway. Specifying the relative orbit number (by adding `relativeorbitnumber=x`) might work instead. Check the products' metadata for a suitable value.

**Comment by gthuser** [comment]
@j08lue, I tried what you suggested and get this error message:
```
Traceback (most recent call last):
  File "sentinelsat_data_download_v2.py", line 37, in <module>
    geom = shapely.geometry.shape(gj)
  File "C:\Anaconda3\envs\geo\lib\site-packages\shapely\geometry\geo.py", line 46, in shape
    raise ValueError("Unknown geometry type: %s" % geom_type)
ValueError: Unknown geometry type: featurecollection
```

**Comment by gthuser** [comment]
@valgur, I need data for one tile only (T34TGP) but these data should be acquired from both relative orbits/swaths, 93 and 50, which, partly or completely cover the tile. When I use, for example relativeorbitnumber=50 I do get my tile data from orbit 50, but in addition I get unwanted data for tile (T35TLJ). So, using the relativeorbitnumber keyword cannot help. Instead, is there a way to filter the imperfect query result and and select only records which contain the string T34TGP in the product name?

**Comment by j08lue** [comment]
> ValueError: Unknown geometry type: featurecollection

I'll leave that for you to figure out. Hint: a `shapely` geometry can only be created from the `geometry` part of a single feature, e.g. `feature_collection['features'][0]['geometry']`.

**Comment by valgur** [comment]
The sentinelsat API does not explicitly support filtering by multiple values of the same property yet but it can be achieved by using the [raw query syntax](https://scihub.copernicus.eu/userguide/FullTextSearch) directly. For example
```python
orbits = [50, 93]
api.query(..., raw=' '.join('relativeorbitnumber:{}'.format(x) for x in orbits))

**Comment by gthuser** [comment]
@j08lue, the code is now working, thanks. After filtering the original dataframe with the shapely geom now I have only the data that I need:
```
from sentinelsat import SentinelAPI, read_geojson, geojson_to_wkt
import shapely.geometry

print('Enter your name:')
username = input()
print('Enter your password:')
pas = input()

api = SentinelAPI(username, pas, 'https://scihub.copernicus.eu/dhus')

footprint = geojson_to_wkt(read_geojson('D:\\Box.geojson'))

products = api.query(footprint,
                     date=('20171015', '20180615'),
                     platformname='Sentinel-2',
                     cloudcoverpercentage=(0, 100),
                     producttype='S2MSI2A',
                     area_relation='Intersects',
                     order_by='beginposition')


products_df = api.to_dataframe(products)
print(products_df) #original search results

gj = read_geojson('D:\\Box.geojson')
geom = shapely.geometry.shape(gj['features'][0]['geometry'])
gdf = api.to_geodataframe(products)
gdf = gdf[gdf.intersects(geom)]

print(gdf) # filtered search results
```
It remains one last step -downloading the data. Can I use the geodataframe gdf with the filtered search results like this:
```
api.download_all(gdf)
```

**Comment by gthuser** [comment]
OK, it will not work this way. For downloading we need to pass download_all a list of product IDs. But how to get the IDs from the geodataframe?

**Comment by j08lue** [comment]
`api.download_all(list(gdf.index))`

**Comment by gthuser** [comment]
@j08lue, thank you.
