### ISSUE TITLE
Add support for searching for multiple values of the same property in Python API

### ISSUE THREAD

**Issue by valgur** [sentinelsat/sentinelsat#317]
Searching for multiple values of the same property simultaneously can be quite useful, e.g. for relative orbit numbers as discussed in https://github.com/sentinelsat/sentinelsat/issues/316#issuecomment-536984451.

We could add a better support for this by considering `api.query()` parameters of `set()` type as a set of allowed values. This avoids ambiguity with `tuple`/`list` with length of two that we interpret as a value range.

The set of values can then be translated to the raw query syntax using
```python
'{}:({})'.format(
    property_name, 
    ' OR '.join(map(str, sorted(values)))
)
```
So `api.query(relativeorbitnumber={50, 93})` produces `relativeorbitnumber:(50 OR 93)`, for example. The latter is equivalent to `relativeorbitnumber:50 OR relativeorbitnumber:93`, as described [here](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/query-dsl-query-string-query.html#_field_names).

**Comment by OlgaCh** [comment]
@j08lue hello!
I'd like to work on this one as an hacktoberfest contribution.
Could you please assign me?

**Comment by j08lue** [comment]
Thanks, @OlgaCh, I will. Please wait a day or two before you start hacking, though. We are just about to merge #296 that touches a lot of code and PRs branching off before that might cause some nasty merge conflicts.

**Comment by OlgaCh** [comment]
Will do. Thank you for the headsup @j08lue

**Comment by AmirM69** [comment]
> Searching for multiple values of the same property simultaneously can be quite useful, e.g. for relative orbit numbers as discussed in [#316 (comment)](https://github.com/sentinelsat/sentinelsat/issues/316#issuecomment-536984451).
> 
> We could add a better support for this by considering `api.query()` parameters of `set()` type as a set of allowed values. This avoids ambiguity with `tuple`/`list` with length of two that we interpret as a value range.
> 
> The set of values can then be translated to the raw query syntax using
> 
> ```python
> '{}:({})'.format(
>     property_name, 
>     ' OR '.join(map(str, sorted(values)))
> )
> ```
> 
> So `api.query(relativeorbitnumber={50, 93})` produces `relativeorbitnumber:(50 OR 93)`, for example. The latter is equivalent to `relativeorbitnumber:50 OR relativeorbitnumber:93`, as described [here](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/query-dsl-query-string-query.html#_field_names).

I think this improvement enables me to download images for multiple time intervals by one request. right? I see that this feature has already been added and users just need to introduce multiple time/date intervals in a dict. However, when I use this format, it only download images for one of the introduced intervals. here is my code:


from sentinelsat import SentinelAPI, read_geojson, geojson_to_wkt
from datetime import date

# connect to the API
api = SentinelAPI('xxxxx', 'xxxxx', 'https://apihub.copernicus.eu/apihub')

# search by polygon, time, and Hub query keywords
footprint = geojson_to_wkt(read_geojson('search_polygon.geojson'))
products = api.query(footprint,
                     date = {('20201229', '20201230'),('20201228', '20201229')},
                     platformname = 'Sentinel-3',
                     producttype = 'OL_1_EFR___',
                     limit = 1) #'S2MSI1C'

# download all results from the search
api.download_all(products)


This code just downloads the images for the first date/time interval, while I expect images for both intervals according to documentation.
