### ISSUE TITLE
Not identifying .netrc on WSL

### ISSUE THREAD

**Issue by juansebastianl** [sentinelsat/sentinelsat#323]
Hello y'all, 

I am running python 3 on WSL. I have the standard query: 

    api = SentinelAPI("username", "password")

and it works. 

However, whenever I use a `.netrc` file in my home directory I get the authentication error. I used `pathib` to check that I had the right home directory, and I also tried putting it my working directory, but none of the above worked. i am not sure if it is an issue with WSL or if anyone else is able to reproduce the problem.

**Comment by j08lue** [comment]
`.netrc` support works fine for me on WSL with Ubuntu 18.04. Your error could be because you formatted the file wrongly?

```
machine scihub.copernicus.eu
user <you>
password <youpw>
```

e.g. when you have colons `:` after the keys, it won't work...

**Comment by juansebastianl** [comment]
The file was formatted correctly, but interestingly `get_netrc_auth` was not able to find any credential either (it just returned none).

**Comment by j08lue** [comment]
> The file was formatted correctly

And to make the API request `.netrc`, you, do this, right?

```python
api = SentinelAPI(None, None)
```

**Comment by j08lue** [comment]
Never found out whether this actually was a bug. Please feel free to re-open when you made sure you got the usage right and it still fails.
