### ISSUE TITLE
Search is slow

### ISSUE THREAD

**Issue by ninsbl** [sentinelsat/sentinelsat#329]
sentnielsat is a great tool and simplifies interaction with ESAs data significantly.

What I noticed however, is that searching the archives with sentinelsat is significantly slower than doing so online in the web interface of the same data hub.
A search that takes a few seconds to complete in the webinterface, takes up to 10 min with sentinelsat (even with just dates as filter criteria)...

Is this a known issue or am I doing something wrong?

**Comment by j08lue** [comment]
I think one difference is that `sentinelsat` downloads and parses *all* results of your query right away. The web interface on the other hand only displays a few results at a time. In particular when you issue a very broad query, the results might come in several pages that `sentinelsat` requests in sequence, which can take a long time, in particular against a slow host. 

Would be nice if someone benchmarked how long time it takes to retrieve the results vs to process them. Processing should, ideally, be negligible. If it is not, there is something for us to improve.

**Comment by ninsbl** [comment]
Thanks for you rswift reply @j08lue .

I investigated a bit more and the problem seems to be with adding the dates to the query:
`sentinelsat --user ninsbl --password falk_2019 --sentinel 2 --cloud 10 --url https://colhub.met.no` returns something like:
`Querying products:  72%|????????   | 2100/2923`

But if I add a date (e.g. for start (-s)):
`sentinelsat --user XXXX --password XXXX --sentinel 2 --cloud 10 -s 20191012 --url https://colhub.met.no`
returns something like:
`Querying products:  13%|??         | 9800/76597`

So, by adding that filter the number of returned records is actually increased by times 25.

**Comment by j08lue** [comment]
> So, by adding that filter the number of returned records is actually increased by times 25.

That one is easy to explain: The default time period for the command-line interface is latest 24 hours:

https://github.com/sentinelsat/sentinelsat/blob/1ebb26a1e39c11ecc4fd08498a5ea5d6b1805436/sentinelsat/scripts/cli.py#L59-L68
