### ISSUE TITLE
'get_product_odata' return InvalidKeyException for S2B products

### ISSUE THREAD

**Issue by spatialhast** [sentinelsat/sentinelsat#332]
I have already downloaded Sentinel-2 scenes (SAFE folders inside folder with product UUID in name) and I want to receive metadata information for scenes by UUID of the product using 'get_product_odata' API method. But receive the next error message:
```
    scene_metadata = api.get_product_odata(scene_id)
  File "/home/opengeo/.local/lib/python2.7/site-packages/sentinelsat/sentinel.py", line 427, in get_product_odata
    _check_scihub_response(response)
  File "/home/opengeo/.local/lib/python2.7/site-packages/sentinelsat/sentinel.py", line 1027, in _check_scihub_response
    raise api_error
sentinelsat.sentinel.SentinelAPIError: HTTP status 404 Not Found: InvalidKeyException : Invalid key (d610106e-733f-400d-bb12-c91f42f8873b) to access Products
```
This API method successfully works for 'S2A' products. How I can receive product metadata by UUID for 'S2B' products?
Examples UUID: d84844eb-14cc-4700-918e-9f95aea37e51, d610106e-733f-400d-bb12-c91f42f8873b, f25196eb-584e-4bdf-af56-8ff3b58f1c7e

Thanks!

**Comment by Fernerkundung** [comment]
Are you sure these product IDs are correct and exist on the DHuS endpoint you query?

I just checked with a random S2B product ID over Munich and it works fine.

```Python
scene_id = "7c9defac-3e8a-43cf-94aa-383c6617b820"
scene_metadata = api.get_product_odata(scene_id)
print(scene_metadata)
```

**Comment by j08lue** [comment]
I am downloading loads of S2A and S2B by UUID everyday, too, without problems. Could be a corruption above your area of interest, though. Please show a query that produces faulty UUIDs. And when you found it, please tell `eosupport` at `copernicus.esa.int`. Very unlikely that this has anything to do with `sentinelsat`.
