### ISSUE TITLE
api.query returns SentinelAPIError

### ISSUE THREAD

**Issue by paumillet** [sentinelsat/sentinelsat#333]
Hello,

I'm trying to send a query to Sentinelsat API and I got the following error message, not matter the parameters combination I'm requesting:

```
SentinelAPIError: HTTP status 500 Internal Server Error: RemoteSolrException : Error from server at http://172.30.175.85:8983/solr/dhus: non ok status: 414, message:Request-URI Too Long
```

I've been using sentinelsat before and I've never meet this issue before. I'm running `sentinelsat-0.13`

Thanks for your help

**Comment by j08lue** [comment]
> Request-URI Too Long

Could it be that your geometry is very complex? We just merged a fix to catch this type of error earlier, but it is not published yet. Anyways, to help you debugging this we need the full query - or a similar one that produces the same error.

**Comment by paumillet** [comment]
The geometry was a city shape, I simplified it (a lot) and it's now working, thanks for the hint.

It would be nice to add in the documentation that the length of the geometry object has a direct impact on the query.

**Comment by j08lue** [comment]
> It would be nice to add in the documentation that the length of the geometry object has a direct impact on the query.

As mentioned, the `sentinelsat` CLI now warns when your query string is very long. If you have the time, please test it. You can install it with `pip install https://github.com/sentinelsat/sentinelsat/archive/master.zip`.

But a note in the docs would perhaps also be nice. Will you submit a PR for that, @paumillet? 😄

**Comment by Fernerkundung** [comment]
>But a note in the docs would perhaps also be nice.

The warning implemented in master is already in the documentation: https://github.com/sentinelsat/sentinelsat/blame/a6d396b244a0bd2565e4ed2c2b1b9a5d5dd32a2e/docs/common_issues.rst#L38

**Comment by j08lue** [comment]
well then... ¯\_(ツ)_/¯

**Comment by bugsuse** [comment]
Same error to me. Any sugesstions for using complex geometry?

**Comment by Fernerkundung** [comment]
The only way to work with a complex geometry is to simplify it. The server flat-out rejects them by the way of queries being too long due to complex geometries.

**Comment by bugsuse** [comment]
Well, thanks so much! @Fernerkundung
