### ISSUE TITLE
'Triggering retrieval from long term archive' on downloading Sentinel-2 using CLI (or Python)

### ISSUE THREAD

**Issue by spatialhast** [sentinelsat/sentinelsat#334]
For geojson polygon I requested Sentinel-2 scenes uuid's. But when I try to download scene archive using CLI by uuid (or via Python) I received a message:

> Downloading 1a0d8728-bae9-4601-8ead-98f541031332 to ./S2A_MSIL1C_20170920T085631_N0205_R007_T35UQP_20170920T090324.zip
> Product 1a0d8728-bae9-4601-8ead-98f541031332 is not online. Triggering retrieval from long term archive.
> Accepted for retrieval
> 1/1 products downloaded

Examples uuid:

> 4f4edb56-20d8-4caf-85c8-4f04bcddd6ea
> 76fdb17c-a96a-4b2b-8faa-0ef19d3938b7
> 0ecd677e-7738-4635-a9bc-b301ea659008

API URL: 'https://scihub.copernicus.eu/dhus'

**Comment by j08lue** [comment]
And what behavior did you expect? @spatialhast

**Comment by spatialhast** [comment]
> And what behavior did you expect? @spatialhast

I expect to download scene by uuid. What is 'Product 1a0d8728-bae9-4601-8ead-98f541031332 is not online.' mean?

**Comment by j08lue** [comment]
Sorry for ruining your day: https://scihub.copernicus.eu/userguide/LongTermArchive

In short: SciHub now has a rolling archive: only recent data is available for immediate download. Older products have to be requested from long-term archive one-by-one and can be downloaded after some waiting time (hours).
