### ISSUE TITLE
All of Sentinel 2 are processed and able to download from ESA?

### ISSUE THREAD

**Issue by diogocaribe** [sentinelsat/sentinelsat#335]
My doubt is if Open Data Hub provides all of Sentinel 2 with level 2 of processing?

Why I am asking it? When I put my query as above:
```python
api.query(footprint, date=('20160101', 'NOW'), platformname='Sentinel-2',
 producttype='S2MSI2A', cloudcoverpercentage=(0, 5))
```
the last one date that it return is December 17, 2018. So there are many images that were collected and not return in this query.

**Comment by j08lue** [comment]
No, Open Data Hub does not provide all data Sentinel-2 in L2A. Only parts of the globe, parts of the time. I don't know what their official plan is for producing L2A, if they have one. Please share if you find out something on the interwebs.

And the data they do provide is online (ready to download) for the last 18 months, the rest is LTA https://scihub.copernicus.eu/userguide/LongTermArchive.

**Comment by Fernerkundung** [comment]
Global L2A processing started in December 2018
> From the mid-March 2018, the Level-2A became an operational product, beginning with coverage of the Euro-Mediterranean region. Global coverage started in December 2018.
https://earth.esa.int/web/sentinel/technical-guides/sentinel-2-msi/level-2a-processing
