### ISSUE TITLE
How to download only L1C product of sentinel-2 MSI (multi-spectral instrument (MSI)) 

### ISSUE THREAD

**Issue by palaiya** [sentinelsat/sentinelsat#337]
I couldn't find any example in the documentation to download only L1C satellite images of sentinel-2 MSI not L2A. Whereas if i try to the following

`sentinelsat -u USERNAME -p PASSWORD -g jsw-vijaynagar.geojson --producttype L1C  --sentinel 2 -s 20191101 -e 20191215  --cloud 20 -d`

It doesn't download any images.

@Fernerkundung @valgur

**Comment by Fernerkundung** [comment]
As stated in the [documentation](https://sentinelsat.readthedocs.io/en/stable/cli.html):

> Limit search to a Sentinel product type. List of valid product types can be found under producttype [here](https://scihub.copernicus.eu/twiki/do/view/SciHubUserGuide/FullTextSearch?redirectedfrom=SciHubUserGuide.3FullTextSearch).

You need to adapt your command to `--producttype S2MSI1C`.
