### ISSUE TITLE
download_all with LTA retrieval fails while failing

### ISSUE THREAD

**Issue by j08lue** [sentinelsat/sentinelsat#338]
I tried to use `download_all` for downloading a single product from SciHub LTA (passing a list of one item). It failed for some reason and I never got the real exception, because I hit a `StopIteration` exception in this line:

https://github.com/sentinelsat/sentinelsat/blob/5b3629020017d423eabfb1b1a4fadec77f9eea23/sentinelsat/sentinel.py#L771-L772

Turns out the single `Future` did not actually raise an exception, so `x.exception()` is None and the iterator is empty.

Looking into why the future is registered as failed when there is no exception.

**Comment by j08lue** [comment]
@gbaier maybe you can have a look, too? 

The product ID I am using is `c5a5be01-9923-4cd4-b919-ff61778fb18d` - don't think I triggered a retrieval yet.

**Comment by gbaier** [comment]
@j08lue #339 solves, at least for me, the issue by waiting for the triggering thread to finish. It turns out that programming with threads is indeed hard ;)

**Comment by j08lue** [comment]
Thanks a lot @gbaier
