### ISSUE TITLE
Drop support for Python 3.4

### ISSUE THREAD

**Issue by Fernerkundung** [sentinelsat/sentinelsat#345]
I propose to drop support for Python 3.4.

Python 3.4 is not supported by some of our extra dependencies and is now starting to cause issues with the standard dependencies as well.

see:
- https://github.com/sentinelsat/sentinelsat/blob/9fd9f0658f29e64505ed252cc5202f435e657a62/setup.py#L52
- PyYAML dependency for testing does not support Py3.4 https://travis-ci.com/sentinelsat/sentinelsat/jobs/282228957

Any objections to this? People dependant on Python 3.4 would still be able to install and use `sentinelsat` but would not be able to develop and test new features, so impact is minimal.

**Comment by j08lue** [comment]
Very much in favor of dropping. I hope not too many people out there are stuck with 3.4 anyways.

**Comment by valgur** [comment]
Indeed, this would only affect 0.1% of our users.
```
pypistats python_minor sentinelsat --last-month
```
| category | percent | downloads |
|----------|--------:|----------:|
| 3.7      |  38.04% |     1,565 |
| 3.6      |  26.79% |     1,102 |
| 3.8      |  13.98% |       575 |
| 2.7      |   8.85% |       364 |
| 3.5      |   7.66% |       315 |
| null     |   4.57% |       188 |
| 3.4      |   0.12% |         5 |
| Total    |         |     4,114 |

Date range: 2020-01-01 - 2020-01-31
