### ISSUE TITLE
autoblack?

### ISSUE THREAD

**Issue by j08lue** [sentinelsat/sentinelsat#349]
Since #296 our code is PSF/black-formatted and we check that submitted code is black-formatted.

Still, on some PRs we had to tell the contributor to please format their code and the initially committed code was sometimes far from black. We could help our contributors (and do away with the need to remind people) by adding a PR hook that black-formats and commits the code automatically. I just added a corresponding GitHub action to some of my projects and it works nicely.

I found this implementation to work nicely:

https://github.com/TheAlgorithms/Python/blob/master/.github/workflows/autoblack.yml

What do you think, @Fernerkundung and @valgur?

**Comment by Fernerkundung** [comment]
Absolutely in favor 👍 

If the black-ened code is not valid anymore our tests should catch that, but they are run after the commit - so should be no issue.

**Comment by j08lue** [comment]
> but they are run after the commit - so should be no issue

Yes. You can see the execution sequence in the linked PR - our Travis CI checks all the commits, both the original black-violating one and the one that the black bot pushed afterwards.

**Comment by j08lue** [comment]
After a few weeks of using the black-push action, I can say it can get pretty annoying. 😄 When you work on a local clone and start pushing some commits to the feature branch, you always have to pull before you work on, because the code will have changed in the remote... So this is not perfect, but for a project like this with loads of different contributors, the benefits still outweigh the hassle, I'd say.

**Comment by Fernerkundung** [comment]
You could solve this by adding a pre-commit hook to your local repo. This way you avoid running into autoblack.
