### ISSUE TITLE
CLI should support geometry input as string

### ISSUE THREAD

**Issue by Fernerkundung** [sentinelsat/sentinelsat#355]
Currently the `sentinelsat` CLI onyl supports input of search geometries as GeoJSON files.

**Proposal**
The CLI should accept strings of geometric objects, in addition to file paths. If the CLI supports direct input of WKT and/or GeoJSON strings, then you can chain it with any tool you like. (e.g. by chaining Fionas CLI fio (https://fiona.readthedocs.io/en/latest/cli.html) `fio info`, which returns a GeoJSON.) This would make the use of the CLI much more flexible and allow interconnection with different tools or the use in runtimes, where no "geometry" files can be created.

This was enhancement proposal was sparked by discussions in #343 .

**Design Considerations and Challenges**
Ideally the CLI accepts GeoJSON filepaths, GeoJSON strings or WKT Strings under the `-g, --geometry` flag.

The challenge is detecting the input format. In the API we have everything in place to parse GeoJSON filepaths or strings. WKT could be passed through without conversion.

**Comment by j08lue** [comment]
> The challenge is detecting the input format.

If we want to handle this with a single flag (`--geometry`), we could have the heuristics like this
1. check whether the value is an existing path
2. check whether parsing it as JSON succeeds
3. treat it as WKT

**Comment by Fernerkundung** [comment]
The Docs need an example of how to pipe WKT or GeoJSON strings from arbitrary sources into `sentinelsat`, e.g. by using [Fionas `fio info`](https://fiona.readthedocs.io/en/latest/cli.html#info).

**Comment by thomasyoung-audet** [comment]
It looks to me like `fio info` doesn't exactly output a GeoJSON, but just a JSON object with information about the dataset. `fio dump` is the command that outputs a GeoJSON. `fio` does have a paramter `bounds` thought that we could maybe use? That's all we really need right?

**Comment by thomasyoung-audet** [comment]
Anyone want to take a look at the pull request?

**Comment by valgur** [comment]
Implemented in #381.
