### ISSUE TITLE
Sentinel-5 support - download parameter

### ISSUE THREAD

**Issue by sarabarozzi2811** [sentinelsat/sentinelsat#356]
I would like to download Sentinel-5p data inserting as a parameter the orbit number using the API. I have tried many combinations but it seems it is not supported. 

```
keywords ={'platformname': 'Sentinel-5 Precursor',
                    'producttype': product_type,
                    'orbitnumber' : str(orbit) 
                     }

footprint = geojson_to_wkt(read_geojson(geojson))
products = api.query(footprint,
                     date=(date_init, date_end),
                     **keywords
                     )
```
Can support for the download of a specific orbit be added?

Thanks!

**Comment by j08lue** [comment]
Sentinelsat just sends all keyword arguments you pass to the query on to the DHuS API. So what ever the API supports, `api.query` supports.

I can verify that the parameter you are looking for is indeed called `"orbitnumber"`:

![image](https://user-images.githubusercontent.com/3404817/78649084-3d405600-78bd-11ea-881d-895ee71ed561.png)

so I do not know why this should not work. There should be no need to make it a string, though.

To clarify: What is the behavior you are seeing and what did you expect? Do you not get any results? Or do you get too many results, including orbit numbers you did not ask for?

If this comment does not help, please provide a fully working example with all the parameters you pass in, then we can look into it.

**Comment by sarabarozzi2811** [comment]
ok, thanks! I think I figured out. 
I actually need the filter for the 'relative orbit number', since the absolute orbit number always vary, but apparently it is not a search parameter. In fact, what I would like to do is to download many files from the same orbit, so that they overlap. 
Is it possible to do that?

Thanks

**Comment by j08lue** [comment]
> In fact, what I would like to do is to download many files from the same orbit, so that they overlap.

Don't you achieve that by querying for your given area of interest?

**Comment by sarabarozzi2811** [comment]
yes, but i have an area which is completly covered by one orbit, and partially covered by another and I assume both will be downloaded , right? So, i was wondering if there is the possibility to choose the one I am more interested in

**Comment by j08lue** [comment]
I see. One possible solution could then be that you manually filter the query results, e.g. to remove items that overlap your query region by less than 90% or so. This would be most easily achieved by getting the products as GeoDataFrame, something like this:

```python
aoi_area = shapely.wkt.
products = api.query(...)
gdf = api.to_geodataframe(products)
gdf[]

**Comment by sarabarozzi2811** [comment]
yes, you are right this is an interesting solution! 
I can try it!

Thanks for the precise and fast answers.
