### ISSUE TITLE
Error downloading from CODA -  'Online': product['Online'], KeyError: 'Online

### ISSUE THREAD

**Issue by dtlloyd** [sentinelsat/sentinelsat#357]
Hi,

I have found SentinelSat great for downloading level 1 Sentinel 3 data from Scihub. I am now interested in accessing level 2 Sentinel 3 data from CODA. When I run the following code:

```
api = SentinelAPI(<myusername>,<mypassword>, 'https://coda.eumetsat.int')

products = api.query(footprint,
                     date=('20200101', '20200102'),
                     platformname ='Sentinel-3',orbitdirection = 'Descending'\
                     ,producttype =  'SL_2_WST___')

api.download_all(products)
```
"products" is definitely not empty however the download fails.

I receive an error:

> There was an error downloading f7264790-1bea-42f2-b489-0e8cd3a00d46
>  line 602, in download_all
>    product_info = self.download(product_id, directory_path, checksum)
> 'Online': product['Online'],
> KeyError: 'Online'

I see that similar problems have arisen before with non Scihub data sources. However I couldn't work out what I needed to do to solve this problem. I have version 0.13 of SentinelSat.

Is there a simple fix for this problem?

Thanks,
David

**Comment by j08lue** [comment]
Yes, upgrade to latest master with `pip install --upgrade https://github.com/sentinelsat/sentinelsat/archive/master.zip`

**Comment by dtlloyd** [comment]
Thanks. Your suggestion helped. In addition I need to make the following change to initiate the download:

```
api = SentinelAPI(<myusername>,<mypassword>, 'https://coda.eumetsat.int')

products = api.query(footprint,
                     date=('20200101', '20200102'),
                     platformname ='Sentinel-3',orbitdirection = 'Descending'\
                     ,producttype =  'SL_2_WST___')

products_odata = [api.get_product_odata(product_id) for product_id in products]
api.download(products_odata[0]['id'])
```

This is a slightly different code to what I was using for downloading level 1 Sentinel 3 data from Scihub. Single product downloading from CODA seems to work now with these changes.

**Comment by j08lue** [comment]
Good to hear, thanks for letting us know.
