### ISSUE TITLE
Query on filesize?

### ISSUE THREAD

**Issue by ewirth** [sentinelsat/sentinelsat#359]
Is it possible to query on file size. 
E.g. what if I would like to download only full tiles, which are over 750 MB?

**Comment by j08lue** [comment]
> E.g. what if I would like to download only full tiles, which are over 750 MB?

For that I would use the footprint area. Something like this (not tested), in the case of Sentinel-2:

```python
import sentinelsat
import shapely.wkt

api = sentinelsat.SentinelAPI(**credentials)
aoi_geom = shapely.wkt.loads(aoi)
products = api.query(area=aoi, **query_parameters)
gdf = api.to_geodataframe(products).to_crs({"init": "epsg:3857"})  # get metadata in some UTM crs
cond = gdf.intersection(aoi_geom).area > 0.5e10  # only take scenes covering more than half a tile
api.download_all(gdf[cond])
```

**Comment by j08lue** [comment]
But to answer your original question:

> Is it possible to query on file size.

Have a look at the metadata that the query returns. Probably the file size is in there?

**Comment by valgur** [comment]
File size is available only from the OData API, unfortunately. You will have to query it for each product separately.
See https://sentinelsat.readthedocs.io/en/stable/api.html#odata-example

**Comment by ewirth** [comment]
> 
> 
> > E.g. what if I would like to download only full tiles, which are over 750 MB?
> 
> For that I would use the footprint area. Something like this (not tested), in the case of Sentinel-2:
> 
> ```python
> import sentinelsat
> import shapely.wkt
> 
> api = sentinelsat.SentinelAPI(**credentials)
> aoi_geom = shapely.wkt.loads(aoi)
> products = api.query(area=aoi, **query_parameters)
> gdf = api.to_geodataframe(products).to_crs({"init": "epsg:3857"})  # get metadata in some UTM crs
> cond = gdf.intersection(aoi_geom).area > 0.5e10  # only take scenes covering more than half a tile
> api.download_all(gdf[cond])
> ```

Hmm, gonna try this.

**Comment by ewirth** [comment]
@j08lue hmm, like you implementation.
There was a comment here about OData example (https://sentinelsat.readthedocs.io/en/stable/api.html#odata-example)
Gonna try to fetch File Size from that.

**Comment by valgur** [comment]
You can filter by file size, but it is not implemented well. The values are strings like `1.5 GB` and `653 MB` and they are handled as strings when trying to filter by this field as well.

The closest thing to what you are trying to achieve would be
```python
api.query(..., size="*MB")
```

The proper file size is only available from the OData API, unfortunately, and you will have to query it separately for each product.
See https://sentinelsat.readthedocs.io/en/stable/api.html#odata-example

**Comment by ewirth** [comment]
@valgur Trying it OData way what you wrote. 
But there are other problems as well:
```py
products_df = api.to_dataframe(products)
## this one does not work, Pandas way
filtered_products = products_df[products_df['size'] >= 400]
## the string type have to converted a lot ('772.39 MB')
filesize = products_df['size'][0]

**Comment by valgur** [comment]
You can do
```python
products_df['size'] = products_df['size'].str.split(' ').apply(lambda x: float(x[0]) * {'GB': 1e3, 'MB': 1, 'KB': 1e-3}[x[1]])
filtered_products = products_df.query('size >= 400')
```
to get only products >= 400 MB in size, for example.

**Comment by ewirth** [comment]
@valgur Cool, best workaround :)
