### ISSUE TITLE
Report query results in STAC format

### ISSUE THREAD

**Issue by kr-stn** [sentinelsat/sentinelsat#360]
Reporting the footprints of all queried images as a **S**patio-**T**emporal **A**sset **C**atalogue would allow users to populate their own metadata stores and tie in to the growing STAC/COG ecosystem.

What is STAC: https://stacspec.org/
inspired by: https://github.com/stac-utils/stac-sentinel

**Comment by j08lue** [comment]
Great idea and very relevant motivation.
