### ISSUE TITLE
Adding functionality for downloading quicklooks

### ISSUE THREAD

**Issue by milyra** [sentinelsat/sentinelsat#361]
In some cases, it is good to evaluate the quicklooks before proceeding to download all the images. This can help reduce the number of images ultimately downloaded.
As such, I'd like to request the functionality of a small flag in the command-line that sets `sentinelsat` to download the quicklooks, rather than the actual files. I propose `--quicklooks` and `-ql`.

**Comment by j08lue** [comment]
I agree that this would be a nice feature that might be of general interest, similar to the `--footprints` flag.

It is doable with a few lines of code - here is a script I hacked together:

```python
from pathlib import Path
import sentinelsat

api = sentinelsat.SentinelAPI(**credentials)
results = api.query(platformname="Sentinel-2", date=("NOW-1DAY", "NOW"), limit=10)

outdir = Path("./quicklooks")
outdir.mkdir(parents=True, exist_ok=True)

for data in results.values():
    url = data["link_icon"]
    r = api.session.get(url)
    
    # sanity checks
    r.raise_for_status()
    content_type = r.headers['content-type']
    if content_type != "image/jpeg":
        raise RuntimeError(f"Quicklook is not jpeg but {content_type}. Something went wrong.")
    
    # save to file
    path = outdir / "{identifier}.jpeg".format(**data)
    path.write_bytes(r.content)
```

If we name the files by their identifier or UUID, a user could sort out the bad quicklooks and just use the list of remaining file names for downloading the products they want...

**Comment by Fernerkundung** [comment]
I think this is a good addition :+1: . We might need to incorporate some error handling if quicklooks are missing for a product or an endpoint.

Are quicklooks available for all products and what is the server response if there are none available?

**Comment by milyra** [comment]
Based on the implementation hacked together by j08blue, just with the error handling commented out, I get a few files with this content:

`<?xml version='1.0' encoding='UTF-8'?><error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><code/><message xml:lang="en">Navigation failed (result is null)</message></error>`

**Comment by j08lue** [comment]
Yes, that is the kind of error (`Navigation failed`) we should catch. I guess we just issue a warning for failing products. That will also cover the case of no quicklooks available at all.

I'll submit a PR shortly.

What do you think about file naming? I suggested `{identifier}.jpeg` or `{uuid}.jpeg`. We could also take the original file name from the response headers under `"content-disposition"`:

```json
{
  "server": "Apache-Coyote/1.1",
  "pragma": "no-cache",
  "accept-ranges": "bytes",
  "content-disposition": "inline;filename=\"S2A_MSIL2A_20200505T081611_N0214_R121_T44XMN_20200505T092028-ql.jpg\"",
  "content-range": "bytes 0-9192/9193",
  "dataserviceversion": "2.0",
  "date": "Tue, 05 May 2020 13:20:00 GMT",
  "etag": "24949F8B8D28B8B463872B480E85A1BB",
  "expires": "Tue, 12 May 2020 13:20:00 UTC",
  "last-modified": "Tue, 05 May 2020 13:18:12 UTC",
  "content-type": "image/jpeg",
  "content-length": "9193",
  "access-control-allow-origin": ", ",
  "access-control-allow-credentials": "true"
}
```
But I'd rather not depend on this detail...

What do you think?

**Comment by Fernerkundung** [comment]
I'm 👍 for `{identifier}.jpeg`. These quicklooks are for human consumption and no-one thinks about their datasets in `{uuid}`.

**Comment by mackland** [comment]
Interested in picking this up since I've previous experience in remote sensing and Sentinel data in particular and want to get involved in open source projects this seemed like a good fit.

Is there a nearly finished PR for this issue or can I go ahead and build on @j08lue solution and add error handling for Navigation failed, using identifier for the file name?

**Comment by j08lue** [comment]
Great, your contribution is welcome. There is no PR yet, so please go ahead and start one.

**Comment by mackland** [comment]
Have a working example where I let cli log/warn about missing quicklook or unexpected content-type similar to how download_all returns failed_products and logs it.

Can submit the PR now if you want to review but I'm unable to reproduce the 'Navigation failed' error. Is this under <Quality Indicators><Failed Inspection> in the metadata xml?  @milyra do you have a filename/uuid where this occurred that I can look at?

**Comment by j08lue** [comment]
Great, please submit the PR and then we can take it from there. We can always add the extra error handling if a user encounters it.

**Comment by pedro-cf** [comment]
Is it possible to retrieve a preview of the TCI .jp2  in jpg/png format, that is correctly georeferenced without a black border.

**Comment by j08lue** [comment]
Not with our library. You would need to download the file and then transform it with GDAL/Rasterio or so. GDAL/Rasterio can write both JPG and PNG and also write a sidecar file with the georeference.

To make any nodata areas transparent (which may otherwise appear as black, if 0 is used as nodata value) is only possible with PNG because JPEG does not support transparency, to my knowledge. I have not tried writing PNGs with transparency with Rasterio, but perhaps GDAL does this natively if the `nodata` value is set correctly. 🤷

**Comment by j08lue** [comment]
https://sentinelsat.readthedocs.io/en/stable/api_overview.html#downloading-parts-of-products
