### ISSUE TITLE
NRTI data not always available

### ISSUE THREAD

**Issue by craigmillernz** [sentinelsat/sentinelsat#362]
I'm not sure if this is a sentinelsat issue or a scihub issue, but often NRTI data are not available using the sentinelsat api, yet when I search the https://s5phub.copernicus.eu/dhus/#/home page the data are there.  Has anyone encountered this issue?  I'm specifically interested in download the NRTI data as soon as it's available (usually 3-4 hours after acquisition), but often sentinelsat returns no data available, yet they are there for manual download. Even when I try to download 12 or 18 hours after acquisition sentinelsat returns no files.

**Comment by j08lue** [comment]
Which API URL are you using with `sentinelsat`?

**Comment by craigmillernz** [comment]
`api = SentinelAPI('s5pguest', 's5pguest',  api_url='https://s5phub.copernicus.eu/dhus')`

**Comment by j08lue** [comment]
So you are using the same endpoint for manual search on the web UI and with Sentinelsat. It sounds weird that you should be able to find the data via manual but not automated search, effectively against the same API. I do not see how Sentinelsat could be responsible for this.

Is the issue permanent - i.e. are some products never found via Sentinelsat but always via the UI?

**Comment by craigmillernz** [comment]
It appears to pretty random as to what products I can retrieve.  Some days I can get granules of a particular area and other days I can't even though it's the same area.  I'm not sure if the NRTI data are gauranteed to be available always, given that the s5p hub is in some "pre-operations" phase.

**Comment by j08lue** [comment]
You could try to contact the SciHub helpdesk about this. They are usually quite responsive. I'll close this here, since I am very sure it is not a Sentinelsat issue. But please reopen/share if you should gain new insights.

**Comment by craigmillernz** [comment]
I've investigated this further using the sentinel5dl library [https://sentinel5dl.emissions-api.org/home.html#](https://sentinel5dl.emissions-api.org/home.html#).  When i use that I can retrieve files, that sentinelsat doesn't find.  So this to me seems like a sentinelsat issue.  Sentinel5dl uses pycurl for downloading which seems to be the main differnce.  Is there a way I can test whether sentinelsat has properly connected to the scihub?  Extending the timeout parameter seems to have no effect.

**Comment by j08lue** [comment]
Great if you could compare their query parameterization https://github.com/emissions-api/sentinel5dl/blob/0bb156a354ccdd2e98ef28f110a00bd77933c886/sentinel5dl/__init__.py#L128 to ours and see whether there is a decisive difference.

**Comment by valgur** [comment]
Seems to be a server-side issue. Feel free to re-open, if you have any comments regarding this.
