### ISSUE TITLE
NRTI data not always available - part 2

### ISSUE THREAD

**Issue by craigmillernz** [sentinelsat/sentinelsat#363]
Following on from the previous issue (now closed).

I've investigated this further using the sentinel5dl library https://sentinel5dl.emissions-api.org/home.html#. When i use that library I can retrieve files that sentinelsat doesn't find. So this to me seems like a sentinelsat issue. Is there a way I can test whether sentinelsat has properly connected to the scihub? Extending the timeout parameter seems to have no effect.

**Comment by j08lue** [comment]
Let's take this back to #362 then
