### ISSUE TITLE
Timeout Between Requests

### ISSUE THREAD

**Issue by mustafateke** [sentinelsat/sentinelsat#365]
Hello, what is the number of requests we could make in a given time frame?
How much sleep time I should add, if I already downloaded the frame so that I may skip it.

Thanks in advance.
Mustafa

**Comment by mustafateke** [comment]
This is the error I get: You have sent too many requests in a given amount of time.

**Comment by j08lue** [comment]
What endpoint (URL) are you using? This sounds a lot like the message you can get when you use sentinelsat against `https://scihub.copernicus.eu/dhus`, which is not meant for machine access.

So if that is the case, use `/apihub` instead and then the issue should be gone.

**Comment by mustafateke** [comment]
https://scihub.copernicus.eu/dhus

**Comment by mustafateke** [comment]
Thanks a lot. 
1 more question I could not download any data, there is no proper error message, what it would be?

**Comment by j08lue** [comment]
😄 Please don't ask that kind of question. And not on a closed thread. It's one of the few general don'ts of discussions on GitHub (and most other places).

Open a new issue and be as specific as possible about it.

**Comment by mustafateke** [comment]
Thanks for the reminder. 
I noticed there was an open issue on error messages being specific. 
I am doing guesswork to understand generic error messages trying to figure out why I could not download data for a few hours....
