### ISSUE TITLE
Frame Coverage

### ISSUE THREAD

**Issue by mustafateke** [sentinelsat/sentinelsat#366]
Hello, Would you mind add frame coverage in metadata fields. I only want to download full frames. 
Some frames are partially covered, I check data size i.e. I download frames having size > 400MB
However, it would be nice if there is a more elegant way. 

Is it included in cloud ratio? If so it may be confusing.

**Comment by Fernerkundung** [comment]
Anything that can be queried in the metadata can be done with `sentinelsat`. 

Have you checked the official documentation of what is exposed to the OData interface? https://scihub.copernicus.eu/userguide/FullTextSearch

As far as I know the "no-data coverage" is not included and therefore not possible to query by. If you can find something in the docs please comment here and I will re-open so we can find a way to include the solution.

**Comment by j08lue** [comment]
I assume you are talking about Sentinel-2 here. Please be specific.

> Is it included in cloud ratio?

You mean whether cloud % is really "good data fraction of all pixels in full tile"? I do not think so. I think it is "cloudy pixels out of all data [as opposed to nodata] pixels". But please research this and report here.

> Would you mind add frame coverage in metadata fields

The metadata we get from DHuS and expose in Sentinelsat does contain the **footprint geometries**. You could compute the area of those (transform to UTM coordinates first!) and see whether it is less than you expect - or compare them with a full tile geometry you get from somewhere.
