### ISSUE TITLE
tileid parameter issue for April 2017

### ISSUE THREAD

**Issue by ENIAC-6** [sentinelsat/sentinelsat#368]
Thanks for such an amazing package. I had a question about your documentation and the tileid parameter. I see in your documentation that: "The tileid parameter only works for products from April 2017 onward due to missing metadata in SciHub’s DHuS catalogue. Before that, but only from December 2016 onward (i.e. for single-tile products), you can use a filename pattern instead." If I understand correctly, using the tileid parameter should be fine for imagery for any date in April of 2017.

However, I've come across a confusing issue where using the tileid parameter for April 2017 does not return all images from April 2017. For example, I've made two script tools using your package in order to download Sentinel-2 imagery. One uses tileid, the other uses a footprint. I ran a test for R070 & T11SKV for 20170401 to 20170514. The footprint returns the same products as the Copernicus Open Access Hub (4/7/17, 4/17/17, 4/27/17, and 5/7/17). However, the tileid version only returns 4/27/17 and 5/7/17.

I also tested the same time period for R127 & T11SQT and found a similar pattern: Copernicus and footprint methods return 4/1/17, 4/11/17, 4/21/17, 5/1/17, and 5/11/17, whereas the tileid method only returns 5/11/17.

All that to say, I'm wondering if you could point me in the direction of the resource that mentioned the missing metadata? I'm wondering if the issue lasted longer (say, through late April 2017).

Thank you!

**Comment by j08lue** [comment]
> I'm wondering if you could point me in the direction of the resource that mentioned the missing metadata?

Nope, this is not officially recorded anywhere. The time periods I stated in the docs were based on my own experience but I noticed that the timing actually varies with region. So you cannot rely on these time periods for your area of interest.

Hopefully you will find the file name pattern search to be more reliable for data across the whole archive. https://sentinelsat.readthedocs.io/en/stable/api.html#search-sentinel-2-by-tile

```python
kw['filename'] = '*_T{}_*'.format(tile)
```

**Comment by ENIAC-6** [comment]
Thanks so much for that clarification and your quick response. Yes, if it's not too much trouble to add a note as you mention in the docs eventually I think that would be helpful. The post-March 31st date sounded very authoritative and I thought there was a bug in my code! Thanks again for such a great package--really appreciate the work that's gone into this.

**Comment by j08lue** [comment]
Haha, turns out I already fixed that half a year ago c779b2bc26af70b198b341ab93a6e2235b70d44f, the docs were just not updated online yet.

**Comment by Fernerkundung** [comment]
Yes - the docs have been fixed with #370.

Only the master branch is of the docs is currently built successfully. https://sentinelsat.readthedocs.io/en/master/

Will make this a minor release soon so they are back in order.
