### ISSUE TITLE
Empty result on query on Sentinel-5p

### ISSUE THREAD

**Issue by pandafy** [sentinelsat/sentinelsat#371]
This is the code I am using to fetch all products from a footprint
```
api = SentinelAPI('s5pguest', 's5pguest', 'https://s5phub.copernicus.eu/dhus/')

footprint = geojson_to_wkt(read_geojson('map.geojson'))

products = api.query(footprint,date = ('20190225', '20200227'),platformname='Sentinel-5p')

products
```

This is my geojson file
```
{
    "type": "FeatureCollection",
    "features": [
      {
        "type": "Feature",
        "properties": {},
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
              [
                76.4208984375,
                27.877928333679495
              ],
              [
                77.926025390625,
                27.877928333679495
              ],
              [
                77.926025390625,
                29.19053283229458
              ],
              [
                76.4208984375,
                29.19053283229458
              ],
              [
                76.4208984375,
                27.877928333679495
              ]
            ]
          ]
        }
      }
    ]
  }
```
Is Sentinel-5p not supported?

**Comment by Fernerkundung** [comment]
Basic troubleshooting:

1. Can you query results on the web interface of DHuS with your region of interest and the time parameters?

2. [This documentation](https://scihub.copernicus.eu/userguide/FullTextSearch) indicates that it should be `platformname='Sentinel-5 Precursor'`.

3. Are you sure you want to download all available Sentinel-5P data? There is a very wide range of products and processing levels subsumed under that category.

**Comment by pandafy** [comment]
> 1. Can you query results on the web interface of DHuS with your region of interest and the time parameters?

Yes.

> 2. [This documentation](https://scihub.copernicus.eu/userguide/FullTextSearch) indicates that it should be `platformname='Sentinel-5 Precursor'`.

Changing this fixed it. Can a check be added so an error is generated if a parameter is not allowed? 

> 3. Are you sure you want to download all available Sentinel-5P data? There is a very wide range of products and processing levels subsumed under that category.

No, I don't. I know the query can be further trimmed down to specific products. I just wanted to test with a simple one.

**Comment by Fernerkundung** [comment]
> Can a check be added so an error is generated if a parameter is not allowed?

That would be an interesting addition indeed. Doing that could be quite tricky though, because the SciHub response does not indicate whether the query returns 0 products because the parameter name was wrong or the parameter was correct but there are 0 results available.

Any comments on the feasibility of this @j08lue @valgur @gbaier?

**Comment by j08lue** [comment]
> Any comments on the feasibility of this

Parameter option names change all the time, so I would not like to implement them on our end. Ideally, the API check and raise errors for something as decisive as the platform name, but it does not, so I do not think we can do anything here.
