### ISSUE TITLE
Sentinel-5 Precursor (S5P) query returns empty products dict

### ISSUE THREAD

**Issue by nazzacode** [sentinelsat/sentinelsat#385]
I would like to access Sentinel-5P's methane (CH4) satellite data. I have tried the following code (and many variations thereof) for the last couple days but it keeps returning `products` to me empty (and the 'querying products' progress bar never appears). I have concluded that I must be doing something terribly wrong!!

note: I can get it to work perfectly with almost identical code for Sentinel-2 data. 

```python
from sentinelsat import SentinelAPI

api = SentinelAPI(<username>, <password>, api_url='https://scihub.copernicus.eu/dhus')

# search by polygon, time, and SciHub query keywords
products = api.query(date=('NOW-3DAYS', 'NOW'),
                     platformname='Sentinel-5 Precursor',
                     producttype='L2__CH4',
                     )

# convert to Pandas DataFrame
products_df = api.to_dataframe(products)
```
Any help would be hugely appreciated as I'm very confused.

**Comment by Fernerkundung** [comment]
Are you querying `api_url='https://scihub.copernicus.eu/dhus'`? AFAIK S5P products are still only available via `api_url='https://s5phub.copernicus.eu/dhus/'.

**Comment by nazzacode** [comment]
Ok thanks, the additional 's5phub' did the trick. However, I'm now getting the following error: "# HTTP Status 401 - Full authentication is required to access this resource" similar to https://github.com/sentinelsat/sentinelsat/issues/45 despite the fact I can log in the webpage API and download other products. My account was created around 2 weeks ago, is this normal, and is there anything I can do?

**Comment by Fernerkundung** [comment]
S5phub is accessed with `s5pguest:s5pguest` and does not support account creation yet. How did you create an account for the Sentinel-5P Hub?

**Comment by nazzacode** [comment]
That sorted it for me- I never realized it was a separate account system. Thanks for clearing all of this up and I hope that other people find this if they have similar confusions. Feel free to close the issue thread.
