### ISSUE TITLE
API error json_feed "opensearch:totalResults" is None

### ISSUE THREAD

**Issue by MargaridaBSC** [sentinelsat/sentinelsat#393]
Dear Sentinelsat Team,

I would like to use the Sentinelsat API and used a GeoJSON file following the WGS84 format (with longitude and latitude units of decimal degrees), however the error json_feed appears. I send you some code and the geojson file at the bottom.

Thank you very much in advance.

Best regards,

Marga

```
>>> products = api.query(footprint, date = ("20180401", date(2018, 04, 30)), platformname = 'Sentinel-2',cloudcoverpercentage = (0, 5))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sentinelsat/sentinel.py", line 107, in query
    return self.query_raw(query)
  File "sentinelsat/sentinel.py", line 144, in query_raw
    response = self._load_query(query)
  File "sentinelsat/sentinel.py", line 162, in _load_query
    total_results = int(json_feed['opensearch:totalResults'])
TypeError: int() argument must be a string or a number, not 'NoneType'

```
```
>>> print(footprint)
LINESTRING (3.7792970 42.6824350, -11.4257810 45.2130040, -20.5664060 28.1495030, -14.9414060 27.2936890, -10.8984380 29.8406440, -8.9648440 34.7416120, -6.3281250 35.9602230, -1.4941410 36.5272950, 6.8554690 40.5137990, 4.2187500 42.8759640
```

```
{
  "type": "FeatureCollection",
  "features": [
    { 
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [ 
            3.779296875,
            42.68243539838623
          ],
          [ 
            -11.42578125,
            45.213003555993964
          ],
          [ 
            -20.56640625,
            28.14950321154457
          ],
          [
            -14.94140625,
            27.293689224852407
          ],
          [
            -10.8984375,
            29.84064389983441
          ],
          [
            -8.96484375,
            34.74161249883172
          ],
          [
            -6.328125,
            35.96022296929667
          ],
          [
            -1.494140625,
            36.527294814546245
          ],
          [
            6.85546875,
            40.51379915504413
          ],
          [
            4.21875,
            42.87596410238256
          ]
        ]
      }
    }
  ]
}
```

**Comment by j08lue** [comment]
I can see we handle this situation (`total_count` being `None`) better in the most recent version of the API. 

https://github.com/sentinelsat/sentinelsat/blob/4bf367a992a9e29a9fa10a56881d8519dd755af0/sentinelsat/sentinel.py#L405

Please update `sentinelsat` with `pip install --upgrade sentinelsat` or `pip install https://github.com/sentinelsat/sentinelsat/archive/master.zip` and your issue should go away.

**Comment by MargaridaBSC** [comment]
Hi @j08lue,

Great, now it works! Thank you very much for your help.

All the best,

Marga

**Comment by MargaridaBSC** [comment]
Hi @j08lue,

Sorry that I talked too soon, now the api.query works but the download gives an error like:
```
raise CancelledError()
concurrent.futures._base.CancelledError
```

Could this be a bug?

Thank you!

**Comment by j08lue** [comment]
> Great, now it works!

Good to hear!

> but the download gives an error

Please raise a new issue for this and include details on the version of Python, Sentinelsat and the OS (Windows, Linux, OS X, ...) you are on, together with the full error traceback.
