### ISSUE TITLE
[Question] sentinel sat and ESA snap/sentinel toolboxes

### ISSUE THREAD

**Issue by javierjsa** [sentinelsat/sentinelsat#395]
Hi,

Are Sentinelsat and snap/sentinel toolboxes related in any way? Does it make sense to use them together? It is my understanding that this project does not rely or relate to snap at all, but I'm also new to satellite imagery, so I'd appreciate some clarification.

Thank you

**Comment by j08lue** [comment]
No, not related at all. But SNAP works on Sentinel data, which you can download with Sentinelsat.

And for example the [ESA Sen-ET Toolbox for SNAP](http://esa-sen4et.org/) uses Sentinelsat for data download.
