### ISSUE TITLE
Expose fileobj api for downloading and streaming files

### ISSUE THREAD

**Issue by daniel-j-h** [sentinelsat/sentinelsat#396]
Hey there :wave: amazing project and thanks for what you are doing! :tada: :hugs: 

I have a small suggestion / some feedback. Right now the download functions take a directory and then will write a file there.

Would it be possible to expose an api taking a file-like object for writing so that users could e.g. pass `io.BytesIO` and don't have to go through the filesystem? Would it then also be possible to use this for streaming the data e.g. from the download function directly to a file store like s3? Otherwise users have to download gigabytes of files to disk, then upload them to a file store.

And while we're at it, is it possible to download partial files from the server? For example say I only want a specific band from Sentinel-2 for the last two years. Right now I could only find ways to download all the data at once and then filter locally which is quite wasteful in terms of disk space, bandwith, etc. This might be a server limitation though?

:satellite: :milky_way:

**Comment by j08lue** [comment]
Thanks a lot for the 💐 and the suggestion.

The file-on-disk logic makes up quite a large part of `api.download` and [`api._download`](https://github.com/sentinelsat/sentinelsat/blob/4bf367a992a9e29a9fa10a56881d8519dd755af0/sentinelsat/sentinel.py#L1095-L1125
) and IMO it would be overkill to make this configurable / replaceable. You could perhaps subclass `SentinelAPI` and change the two methods to your needs. But I think it will be easiest for you to just take the results from the query and process the download links as you want - stream them or copy them to S3 or so.

But if you can prove me wrong and propose an elegant way of exposing a fileobj, we are always open for PRs. ;-)

Please write one question per issue. But your second question already has one here: #291.

**Comment by daniel-j-h** [comment]
Gotcha! Thanks for the explanation, looking at the code it's more than just putting bytes into a buffer :thinking: Handling the download links from the query on my own is something I haven't thought of :ok_hand: I think we're good to close here, all good! :hugs:
