### ISSUE TITLE
[question] What does this error mean? "404...trying to get the DHuS version of APIHub?

### ISSUE THREAD

**Issue by javierjsa** [sentinelsat/sentinelsat#402]
Hi,

I requested an available, recent, Sentinel2 product via productid (the identifier that seens to be a hash), and I got a 404 error. On one occasion, it crashed my script. On a second occasion, SentinelSat seemed to be able to control the problem and logged the following:

This is from  **_req_dhus_stub** in **sentinel.py**
```
"Are you trying to get the DHuS version of APIHub?"
"Trying again after conversion to DHuS URL"
```

The thing is that I've been unable to reproduce & debug the issue. My attempts to reproduce it resulted in no problems whatsoever.  I assume this has to do with the server, but I have no clue. Anyone can explain why this happens?

Thank you

**Comment by Fernerkundung** [comment]
To clarify: The issue appears sometimes and then goes away or is it persisent with a URL/endpoint that you are trying? 

> The thing is that I've been unable to reproduce & debug the issue. My attempts to reproduce it resulted in no problems whatsoever.

Can you provide more information that would help someone else to debug your issue? If you can't reproduce it how should someone else be able to, who has less information?

**Comment by javierjsa** [comment]
I was unable to reproduce it and problem never happened again. Most likely it was related to ESA platform not operating correctly.

**Comment by Fernerkundung** [comment]
That's good to know @javierjsa. If you (or anyone else) encounters this problem again feel free to post a comment here and we'll reopen the issue.
