### ISSUE TITLE
Geometry option with GeoJSON FeatureCollection only queries first feature

### ISSUE THREAD

**Issue by daniel-j-h** [sentinelsat/sentinelsat#403]
Hey hey,

I just encountered the following issue
- I have a GeoJSON file containing a FeatureCollection with two Polygon Features
- I pass this to `sentinelsat` as a footprint in a Sentinel-2 query (e.g. via `geojson_to_wkt(read_geojson(geom))`
- I get results for the first feature, but not for both

This is unexpected.

What works is splitting the one file with two features into two files with one feature each.

Small self contained example below
- one polygon for Berlin and one for Munich
- see the query for both not returning the results of both individual queries

```
$ sentinelsat --sentinel 2 --producttype S2MSI2A --start 20200923 --end 20200924 --geometry ssat-both.geojson 
Found 2 products
Product 89ca339b-e61d-4754-a229-bc9e51269d94 - Date: 2020-09-23T10:16:49.024Z, Instrument: MSI, Mode: , Satellite: Sentinel-2, Size: 1.05 GB
Product fd0b442f-0e3b-4321-80f0-b2d15028a3e7 - Date: 2020-09-23T10:16:49.024Z, Instrument: MSI, Mode: , Satellite: Sentinel-2, Size: 1.06 GB
---
2 scenes found with a total size of 2.11 GB

$ sentinelsat --sentinel 2 --producttype S2MSI2A --start 20200923 --end 20200924 --geometry ssat-1.geojson 
Found 2 products
Product 89ca339b-e61d-4754-a229-bc9e51269d94 - Date: 2020-09-23T10:16:49.024Z, Instrument: MSI, Mode: , Satellite: Sentinel-2, Size: 1.05 GB
Product fd0b442f-0e3b-4321-80f0-b2d15028a3e7 - Date: 2020-09-23T10:16:49.024Z, Instrument: MSI, Mode: , Satellite: Sentinel-2, Size: 1.06 GB
---
2 scenes found with a total size of 2.11 GB

$ sentinelsat --sentinel 2 --producttype S2MSI2A --start 20200923 --end 20200924 --geometry ssat-2.geojson 
Found 2 products
Product 88ea0f6e-58f1-45ba-87dc-28925918d777 - Date: 2020-09-23T10:16:49.024Z, Instrument: MSI, Mode: , Satellite: Sentinel-2, Size: 808.77 MB
Product 3dbbcbbd-86a0-495d-bcdf-01e71dc090db - Date: 2020-09-23T10:16:49.024Z, Instrument: MSI, Mode: , Satellite: Sentinel-2, Size: 342.54 MB
```

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              13.379974365234373,
              52.55965567958739
            ],
            [
              13.331222534179686,
              52.51287794429001
            ],
            [
              13.430099487304688,
              52.46981513498167
            ],
            [
              13.48915100097656,
              52.53376701989025
            ],
            [
              13.379974365234373,
              52.55965567958739
            ]
          ]
        ]
      }
    }
  ]
}
```

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              11.614608764648438,
              48.22009793454488
            ],
            [
              11.466293334960938,
              48.156925112380684
            ],
            [
              11.517791748046875,
              48.06569093979212
            ],
            [
              11.704559326171875,
              48.09734324406965
            ],
            [
              11.614608764648438,
              48.22009793454488
            ]
          ]
        ]
      }
    }
  ]
}
```

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              13.379974365234373,
              52.55965567958739
            ],
            [
              13.331222534179686,
              52.51287794429001
            ],
            [
              13.430099487304688,
              52.46981513498167
            ],
            [
              13.48915100097656,
              52.53376701989025
            ],
            [
              13.379974365234373,
              52.55965567958739
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              11.614608764648438,
              48.22009793454488
            ],
            [
              11.466293334960938,
              48.156925112380684
            ],
            [
              11.517791748046875,
              48.06569093979212
            ],
            [
              11.704559326171875,
              48.09734324406965
            ],
            [
              11.614608764648438,
              48.22009793454488
            ]
          ]
        ]
      }
    }
  ]
}
```

**Comment by daniel-j-h** [comment]
Reading the `geojson_to_wkt` function, this looks like related to

https://github.com/sentinelsat/sentinelsat/blob/a070cc02919d50b661858a7b1b217fff7e8e6222/sentinelsat/sentinel.py#L1150-L1152

The doc string talks about MultiPolygon, but the feature collection is a collection of Polygons.

The API as is can very easily be mis-use - should we e.g.
- support multiple features in the feature collection
- not have a default index
- not support feature collections with multiple features

and especially adapt the `sentinelsat` command line tool?

Right now we silently drop all features except the first which makes it very easy to mis-use.

**Comment by Fernerkundung** [comment]
You are right, the docstring is confusign there since FeatureCollections != MultiPolygon. In fact - a feature collection can contain any number of features with any Geometry type, i.e. multiple MultiPolygon.

From a usage perspective I would say that a user providing a feature collection would most likely be interested in querying over all of them. The tricky part here is mostly detecting that a FC was provided and then looping over the list of Features in the Collection.

Do you want to take this or should we put this up as an issue that could be a good fit for Hacktoberfest?

**Comment by daniel-j-h** [comment]
Fixing it on the library level and then the cli benefiting from it automatically makes perfect sense! :+1: 

You can put it up as an issue for Hacktoberfest :hugs:

**Comment by naruto678** [comment]
hi @daniel-j-h , @Fernerkundung  i would like to work on this as a part of hacktoberfest. Could you give a explanation on what i would need to do here. 
Thanks

**Comment by j08lue** [comment]
It is indeed not clear what solution we prefer here. But the current status (wrong docstring and intransparent default behavior) is not good.

There are the following options:

1. Loop over all features in a FeatureCollection - requires a lot of extra code, either in the CLI or in `SentinelAPI.query`, where we would have to either support a list of `area`s, or move the GeoJSON to WKT conversion into `api.query` to have the loop there (yikes).
1. Not support FeatureCollection at all - maybe too harsh
1. User has to chose which feature should be selected - via a CLI flag like `--geometry-feature-number`.

I would actually prefer the third option, which leaves it up to the user to select one feature and loop somehow, if they have to. But there should be no default. So if the user's GeoJSON is a `FeatureCollection` and they did not specify the `--geometry-feature-number` flag, they get an error.

Python API users can already now easily loop, gather the query results, and then download them all together, so it is not like this is not doable.

@Fernerkundung, are you in line with this (Simple UX improvement by exposing and requiring the `feature_number` in a CLI flag)?

**Comment by daniel-j-h** [comment]
Quick thought: would it be possible to use something like shapely and union all features into a single shape? And then query for this one shape? Or can the WKT query only be a simple polygon?

**Comment by j08lue** [comment]
Yes, a union could produce a MultiPolygon and WKT as well as the DHuS API supports that. But it takes Shapely or the like to compute the union efficiently and realiably and we do not want to add that as a dependency. Again, this is up to the user to solve beforehand, e.g. using `ogr2ogr`, if they do not want to Python-script.

**Comment by valgur** [comment]
The server backend uses Spatial4j for parsing WKT and and any geometric operations. Its WKT parser [supports](https://locationtech.github.io/spatial4j/apidocs/org/locationtech/spatial4j/io/WKTReader.html) the `GeometryCollection` format, which seems to map pretty well to GeoJSON's `FeatureCollection`. So, I would suggest experimenting with that. Seems like a good fit.

**Comment by Fernerkundung** [comment]
>Loop over all features in a FeatureCollection - requires a lot of extra code, either in the CLI or in SentinelAPI.query, where we would have to either support a list of areas, or move the GeoJSON to WKT conversion into api.query to have the loop there (yikes).

I would argue that this is the preferable option. If a user conciously or unconciously provides multiple features as a FeatureCollection they obviously want to get results for all of them. A user that is interested in a single feature or to retain the mapping of feature to results would not provide an unfiltered collection but rather multiple files or loop through the collection themselves.

In pseudocode:
```
results = []
if FeatureCollection:
    for Feature in FeatureCollection
    query_geom = geojson_to_wkt(Feature)
    query_results = api.query(geom=query_geom)
    results.append(query_results)
```

If we can achieve the same result by having the server logic do the heavy lifting, as @valgur suggested, that would produce the same UX and be even better in my opinion.

**Comment by j08lue** [comment]
We actually already have an issue on this: #114
