### ISSUE TITLE
Unable to download Sentinel-1 by Tile

### ISSUE THREAD

**Issue by bszadman** [sentinelsat/sentinelsat#406]
Hello everyone.

I've trying to download sentinel-1 images using the following code:

```
from collections import OrderedDict
from sentinelsat import SentinelAPI

api = SentinelAPI('xxxx', 'xxxx') 
tiles = ['30UXC']

query_kwargs = {
        'platformname':'Sentinel-1',
        'date': ('20190601','20200630')}

products = OrderedDict()
for tile in tiles:
    kw = query_kwargs.copy()
    kw['filename'] = '*_T{}_*'.format(tile)
    pp = api.query(**kw)
    products.update(pp)

api.download_all(products)
```

The returned length of the product list is = 0

Help!

**Comment by j08lue** [comment]
Sentinel-1 data is not tiled but just chunked semi-randomly along the orbit path. You can use the Sentinel-2 / MGRS tile **geometry** as input to the query to find Sentinel-1 products intersecting your tile of interest.

You can download the tile geometries as KML from here https://sentinel.esa.int/web/sentinel/missions/sentinel-2/data-products and as GeoJSON here https://github.com/bencevans/sentinel-2-grid.
