### ISSUE TITLE
AttributeError: __enter__ when calling download_all()

### ISSUE THREAD

**Issue by Peter-L4ng** [sentinelsat/sentinelsat#418]
When calling api.download_all(products, './store') I get the following error, the products seem to print as geojson correctly but not download.

`File "/home/peter/.local/lib/python3.9/site-packages/sentinelsat/sentinel.py", line 807, in download_all                  
raise next(iter(x.exception() for x in dl_tasks if x.exception()))                                                    
File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run                                                   
result = self.fn(*self.args, **self.kwargs)                                                                           
File "/home/peter/.local/lib/python3.9/site-packages/sentinelsat/sentinel.py", line 883, in _download_online_retry       
 if self.is_online(product_info["id"]):                                                                                
File "/home/peter/.local/lib/python3.9/site-packages/sentinelsat/sentinel.py", line 531, in is_online                     
with self.session.get(url, auth=self.session.auth, timeout=self.timeout) as r:                                      
AttributeError: __enter__ `

**Comment by j08lue** [comment]
`self.session` is a `requests.Session` object created here

https://github.com/sentinelsat/sentinelsat/blob/faa745f7e0c3bb7512ff69edbdd8e572c4fe39c9/sentinelsat/sentinel.py#L83

Weird that that should not support being called as a context manager (i.e. has no `__enter__` attribute).

Which version of `requests` are you using (`python -c "import requests ; print(requests.__version__"`)? I wonder whether it ever did not support context and you are using a very recent Python version...

Perhaps upgrade requests with `python -m pip install --upgrade requests` and try again.

**Comment by j08lue** [comment]
No issues with Python 3.9 and our test suite - not that I expected any, but you never know... https://travis-ci.com/github/sentinelsat/sentinelsat/jobs/471928325

**Comment by Peter-L4ng** [comment]
It seems like it was an outdated version of requests, after updating it the downloads proceeded as expected.
