### ISSUE TITLE
setninel 1 GRD , download all method failing with exception (<type 'exceptions.AttributeError'>, AttributeError('__exit__',), <traceback object at 0x7fd6b62cc1b8>)

### ISSUE THREAD

**Issue by sanjivjha** [sentinelsat/sentinelsat#420]
Python version - 2.7 
download_candidate = api.query(self.footprint,
                                                date=(self.date_start, self.date_end),
                                                producttype=self.producttype,
                                                orbitdirection=self.orbitdirection,
                                                sensoroperationalmode=self.sensoroperationalmode)
api.download_all(download_candidate)

Sometime this work and some time it fails with the exception 

(<type 'exceptions.AttributeError'>, AttributeError('__exit__',), <traceback object at 0x7fd6b62cc1b8>)

Any suggestion. How we can make it more robust and consistent?

**Comment by j08lue** [comment]
Hey @sanjivjha, Python 2 is dead. 😉 Can you please try again with Python 3 and updated dependencies and open a new issue if you still get this error? If you do, please send the full traceback so we have a change of debugging it.
