### ISSUE TITLE
Download URL Redirected to landing page

### ISSUE THREAD

**Issue by kssvrk** [sentinelsat/sentinelsat#422]
Starting Feb 2 , 2021 , our automated downloading program at Indian Space Research Organisation from inthub2 has stopped with check sum mismatch error . Initially we suspected the maintenance activities at inthub to be the cause of the issue and waited. But even after the mainetnance window, we observed the error.

On further debugging , on why the checksum is not matching , we found the following.

1. - When we disable checksum matching and download a product, the file size is always 26.5kb.
2. - So we renamed the downloaded zip file to txt and we observe that the file is basically html response of  https://inthub2.copernicus.eu landing page.
3. - This indicates that our product download url through the Sentinelsat library , is being redirected to the inthub2 landing page.

The following is the sample [code stub ](https://gist.github.com/kssvrk/357f0a51a0b73ea2694c0398b208ea03) where we are facing the error. We offer the products on our portal https://bhoonidhi.nrsc.gov.in for various applications and since the last week , we are unable to just do that. Any help regarding this issue will be highly appreciated. Any indications of this being a client library side/server side issue would also help to take this with appropriate team at inthub.

**Comment by j08lue** [comment]
@kssvrk sorry for not picking up on this earlier. Has this issue resolved itself somehow or did you find a solution to prevent the redirects?

**Comment by kssvrk** [comment]
Thanks for the revert.
So we raised this issue to Inthub support team through mail, after one day the issue automatically fixed itself.

I didn't know what the core issue was, else i would have written the problem and solution and closed the issue then.

May be at backend, they restricted access from our Public ip address? I have no clue.

But what i feel is,sentinelsat should not be downloading the landing page perse, when the download gets redirected?

May be we can add a redirect warning and close the download function?

I'd be happy to submit a PR along this line, if the maintainers narrow down the cause.

**Comment by j08lue** [comment]
> But what i feel is, sentinelsat should not be downloading the landing page perse, when the download gets redirected?

Depends on the type and reason of redirect, I guess. Sometimes, following a redirect chain is important for authentication to work. 

I will close this issue for now, as it has been solved for you. We can pick it up again later, if necessary.
