### ISSUE TITLE
AOI with negative coordinates

### ISSUE THREAD

**Issue by andrepessina** [sentinelsat/sentinelsat#424]
Hi everyone!

I'm trying to download images of a small area in the south hemisphere with Sentinelsat 0.14 package in Python 3.8.5. But the "api.query" function returns me a empty "OrderedDict()".

When I try the same coordinate without the negative, it works.

Already tried different "area_relations", date ranges, a single point with the first polygon's coordinate, different polygons close to this one. And nothing worked.

If anyone solved this problem before I would be grateful for the help!

OS: Windows 10 Home 20H2 x64

```python
from sentinelsat import SentinelAPI

api = SentinelAPI('user', 'password', 'https://scihub.copernicus.eu/dhus')

footprint = 'POLYGON ((-22.686814 -48.574812, -22.687631 -48.572279, -22.691074 -48.574562, -22.689205 -48.577437, -22.686814 -48.574812))'
products = api.query(footprint,
                                   date=('NOW-14DAYS', 'NOW'),
                                   area_relation='Contains',
                                   platformname='Sentinel-2',
                                   processinglevel = 'Level-2A'
                                   )

print(products)
```

**Comment by j08lue** [comment]
There should be nothing special with negative coordinates - except maybe when they cross the date line, which is not the case here. But I am not sure SciHub has Sentinel-2 L2A products where you are looking. Please try out your query in the browser at https://scihub.copernicus.eu and see whether you get any results there.

**Comment by andrepessina** [comment]
> There should be nothing special with negative coordinates - except maybe when they cross the date line, which is not the case here. But I am not sure SciHub has Sentinel-2 L2A products where you are looking. Please try out your query in the browser at https://scihub.copernicus.eu and see whether you get any results there.

I got a "HTTP status 404 Not Found: Page not found"

**Comment by andrepessina** [comment]
> There should be nothing special with negative coordinates - except maybe when they cross the date line, which is not the case here. But I am not sure SciHub has Sentinel-2 L2A products where you are looking. Please try out your query in the browser at https://scihub.copernicus.eu and see whether you get any results there.

No results in the browser too.

**Comment by j08lue** [comment]
In an earlier announcement, the Copernicus people announced to cover the "Euro-Mediterranean region" with their L2A production. https://scihub.copernicus.eu/news/News00305. Maybe there is also an updated description somewhere of the region they officially cover.

**Comment by andrepessina** [comment]
> In an earlier announcement, the Copernicus people announced to cover the "Euro-Mediterranean region" with their L2A production. https://scihub.copernicus.eu/news/News00305. Maybe there is also an updated description somewhere of the region they officially cover.
> 
> So this is unfortunately not something we can fix and you have to either process the data yourself or find another distributor.
> 
> For example, Sinergise publishes L2A globally since 2017 in a requester-pays bucket on AWS https://registry.opendata.aws/sentinel-2/ (you pay for the data transfer) or maybe you can find the scenes you are looking for in CreoDIAS https://finder.creodias.eu/ and make use of the simple Python API client my team developed a little while ago https://github.com/DHI-GRAS/creodias-finder/.

Didn't work with other levels too.
