### ISSUE TITLE
to_geodataframe produces a deprecation warning

### ISSUE THREAD

**Issue by heyarne** [sentinelsat/sentinelsat#426]
Executing
``` python
gdf = api.to_geodataframe(products)
```
produces the following warning:
```
/opt/conda/lib/python3.8/site-packages/pyproj/crs/crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
```

Which I guess for now is fine but will probably fail in the future. Is there any ongoing effort to avoid this? Can I help? Thanks!

**Comment by j08lue** [comment]
Thanks for bringing this to our attention, @heyarne.

I think this happens inside Geopandas, actually. The only place we specify a CRS is in this line, I think:
https://github.com/sentinelsat/sentinelsat/blob/9c6269c9ec04e1d2f41ac671d75caf23077bbc25/sentinelsat/sentinel.py#L478

where we already use the new `<authority>:<code>` syntax.

So I trust that recent versions of Geopandas will use the new syntax towards Pyproj.

> Can I help?

Yes, please! Please tell us which versions of Geopandas and Pyproj you have installed when you get this error (you can use `conda list` to check). If you want, you can then try to update to the most recent version (`conda install geopandas pyproj`) and let us know whether the warning persists. Also, if you can trace where the old syntax gets introduced - whether it is in our code or in the dependencies - that would be very helpful.

**Comment by heyarne** [comment]
Thanks for the detailed response! I will update geopandas and pyproj as per your suggestion and report back. Meanwhile:

> Please tell us which versions of Geopandas and Pyproj you have installed when you get this error

```
import geopandas as gpd
import pyproj

gpd.__version__
# '0.8.1'

pyproj.__version__
# '2.6.1.post1'
```

**Comment by j08lue** [comment]
Ah, I forgot that you should of course use the `conda-forge` channel - `conda install -c conda-forge geopandas pyproj`. Alternatively, since you seem to be on Unix, you can also use `pip` for all the packages.

**Comment by j08lue** [comment]
I think this is beyond Sentinelsat and we can trust that this gets fixed in GeoPandas in time.
