### ISSUE TITLE
Corrupt zip file

### ISSUE THREAD

**Issue by heyarne** [sentinelsat/sentinelsat#427]
Hello, when trying to download Sentinel-2 products recovered from the LTA I occasionally receive corrupted zip files. An example is this particular product: https://scihub.copernicus.eu/apihub/odata/v1/Products('b0715f32-b213-420c-a2f4-34dca13072b5')/

It's far smaller than other downloads at around 20mb, even though other corrupted files were at times slightly over 100mb large (compare this to non-corrupted files containing starting at around 750mb). It raises a `BadZipFile` when trying to acces it using Python3's `zipfile` module and shows corruption warnings in various graphical tools.

The MD5 checksum matches, which makes me think it's probably a problem of the restoration process, rather than a problem of sentinelsat.

Just to make sure: Has this happened before? I have already read about previous cases of apparent zip file correction in the issues, but this seems to be another thing. The Sentinel-2 products are not misnamed, they are definitely zip-files. What is the recommended approach, am I still able to retrieve the products? Thanks!

**Comment by j08lue** [comment]
Yes, I encountered the same issues recently. 100s of files corrupted even though the checksum was fine. When I download the same product from the web interface, a new LTA retrieve gets triggered and the file I get is complete.

Would you perhaps hit up Copernicus EO Support <eosupport@copernicus.esa.int> about this and post their answer here?

Btw, I just switched to download from CreoDIAS instead...

**Comment by heyarne** [comment]
I have written an e-mail an I will share the response as soon as I receive it. Thanks for the advice about manual LTA retrieval, I'll give it a try. I identified the files using the following command:

``` bash
$  ls -rSsh target_dir
 16M S2A_MSIL2A_20180807T101021_N0208_R022_T33UUT_20180809T112302.zip
 17M S2A_MSIL2A_20190613T101031_N0212_R022_T33UUT_20190614T125329.zip
 18M S2A_MSIL2A_20180919T102021_N0208_R065_T33UUT_20180919T132226.zip
 21M S2A_MSIL2A_20190726T102031_N0213_R065_T32UPE_20190726T125507.zip
 40M S2A_MSIL2A_20190626T102031_N0212_R065_T33UUT_20190626T125319.zip
1.1G S2B_MSIL2A_20180822T101019_N0208_R022_T33UUT_20180822T161243.zip
1.1G S2A_MSIL2A_20190603T101031_N0212_R022_T33UUT_20190603T114652.zip
1.1G S2B_MSIL2A_20190701T102029_N0212_R065_T32UPE_20190701T134657.zip
1.1G S2A_MSIL2A_20190629T103031_N0212_R108_T32UPE_20190629T135351.zip
```

I just found out that I can copy the file name (without extension) and paste it into the search mask at https://scihub.copernicus.eu/dhus/ and initialize the retrieval.

**Comment by heyarne** [comment]
I have received the following response:

> Dear XXX,
> 
> Thank you for your email and for notifying the problem.
> 
> Please be informed that the technical team has already identified the problem on the Copernicus Open Access Hub and works are ongoing in order to solve the issue, we will let you know as soon as we receive their feedback.
> 
> In the meantime, if you need the products urgently, we would kindly  suggest to download the corrupted Sentinel products directly from DIAS providers, note that some products are distributed free of charge.    
> 
> The DIAS, or Data and Information Access Services are five cloud-based platforms providing centralized access to Copernicus data and information, as well as to processing tools.    
> 
> 
> The five DIAS online platforms allow users to discover, manipulate, process and download Copernicus data and information. All DIAS platforms provide access to Copernicus Sentinel data, as well as to the information products from Copernicus’ six operational services, together with cloud-based tools (open source and/or on a pay-per-use basis).    
> 
> Please note that all information on the DIAS five cloud-based platforms are available on the Copernicus webpage at: https://www.copernicus.eu/en/access-data/dias    
> 
> Please find here below the DIAS providers:    
> 
> • ONDA => More information on ONDA-DIAS can be found at: https://www.onda-dias.eu/cms/    
> • MUNDI => More information on MUNDI-DIAS can be found at: https://mundiwebservices.com/    
> • WEkEO => More information on WEkEO can be found at: https://www.wekeo.eu/offer    
> • CREODIAS => More information on CREODIAS can be found at: https://creodias.eu/    
> • Sobloo => More information on Sobloo can be found at: https://sobloo.eu/    
> 
> We hope this information has been of use.
> We will keep you informed as soon as we receive the technical team feedback. 
> 
> Kind Regards,
> XXXX

**Comment by j08lue** [comment]
> The five DIAS online platforms allow users to discover, manipulate, process and download Copernicus data and information.

If you need a Python client to download from CreoDIAS, you might want to have a look at this rudimentary client library that my team put together at some point: https://github.com/DHI-GRAS/creodias-finder/ and maybe there are also alternatives out there.

**Comment by i21510** [comment]
Hi,

Similar issue here when both triggering retrieval and downloading using Sentinelsat.

Regards

**Comment by j08lue** [comment]
Please let the Copernicus team know, also by filling out this: https://sentinels.copernicus.eu/web/sentinel/-/copernicus-sentinel-data-access-and-user-services-user-satisfaction-survey-2020

**Comment by heyarne** [comment]
I have received another response:

> Dear XXX,
>
> Thank you for your reply.
>
> In order to go ahead with the investigation, could you please provide us with the filenames of the products that you found corrupted?
>
> Thank you in advance for your feedback.
> Kind Regards,
>
> YYY

I have provided a link to this issue report in the original mail, which seems to not have found its way to the internal issue report to the operations team. So if anyone has any additional examples where this happened, I guess sending an issue report to eosupport@copernicus.esa.int including the exact products can help.

**Comment by jlandmann** [comment]
Hi all,
I got a reply from EoSupport today that the issue has been solved as of March 26th. I resumed downloading all data and there haven't been any extraction issues anymore. If others can confirm, I think this can be closed!?

**Comment by i21510** [comment]
I've switched to ESA's requester pays bucket for LTA products

**Comment by valgur** [comment]
Closing since this is a server-side issue and can't be fixed on the sentinelsat side.
