### ISSUE TITLE
Support for Orbit products download

### ISSUE THREAD

**Issue by avalentino** [sentinelsat/sentinelsat#436]
Recently the distribution of orbit files has been mover totally to SciHub (see the [ESA news](https://sentinel.esa.int/web/sentinel/-/access-to-copernicus-sentinel-1-orbit-auxiliary-files-update/1.0)).

The new endpoint shares the web API with the one use to access standard products, so it is easy to use sentinelsat to access orbit files.

I have developed a small class to support orbit files download (you can find it in this [gist](https://gist.github.com/avalentino/845001e0add89c85c338806ba50fddeb)).

My question is: would it make sense to include that class in sentinelsat? Would you accept a PR for that?
If yes, do you have any comment on the design used in the [gist](https://gist.github.com/avalentino/845001e0add89c85c338806ba50fddeb)?

See also the discussion in
* https://github.com/scottstanie/sentineleof/issues/6,
* https://github.com/scottstanie/sentineleof/pull/7 and
* https://github.com/scottstanie/sentineleof/pull/8

**Comment by j08lue** [comment]
Adding orbit file download functionality is definitely relevant. `sentinelsat` aims to be the Python client for SciHub and the GNSS data is of quite wide interest as the threads (and more on the STEP forum) show.

Where this code should go and how to expose it (API and CLI) is probably a bit related to general code structure and refactoring. Rolling out type annotations everywhere would be nice, too... 😉 

To get the discussion going - why do you link in a `SentinelAPI` instance into your GNSS downloader class, instead of sub-classing it?

**Comment by avalentino** [comment]
> To get the discussion going - why do you link in a SentinelAPI instance into your GNSS downloader class, instead of sub-classing it?

I thought that some of the features of SentinelAPI, e.g. the footprints, do not make too much sense for orbits.
Anyway I'm open to any suggestion.

**Comment by j08lue** [comment]
That makes sense. Perhaps we should isolate the core part of `SentinelAPI` into a core base class and then use that as common parent?

**Comment by avalentino** [comment]
> Perhaps we should isolate the core part of SentinelAPI into a core base class and then use that as common parent?

Yes, this is also my idea.
From a practical point of view I could start with an implementation in which we inheriting directly form SentinelAPI and then switch to a base class when the general refactoring of the module will be implemented.

**Comment by j08lue** [comment]
> From a practical point of view I could start with an implementation in which we inheriting directly form SentinelAPI and then switch to a base class when the general refactoring of the module will be implemented.

Perfect. Please go ahead with a PR while the iron is hot, if you have time. 😄

**Comment by j08lue** [comment]
Just received notice from Copernicus EO Support that the issue with redirect during GNSS requests should be fixed on their side:

> Thank you for your email and for reporting the issue.
> 
> We have been informed by the technical support team that the error has been rectified.
> 
> You should now be able to run your script correctly.
> 
> Should you need further information or assistance please do not hesitate to contact us.
> Kind Regards, 
> 
> Paola
> 
> SCI Team
> Copernicus Services Coordinated Interface ESA service operated by Serco
> Mail: EOSupport@copernicus.esa.int
> Portal: https://Spacedata.Copernicus.eu/

**Comment by valgur** [comment]
Thanks for the nice code sample for retrieving relevant orbit data, @avalentino. That's definitely useful, but I think it fits better into the scope of the sentineleof project, perhaps?
