### ISSUE TITLE
Sentinel 2 download not triggered 

### ISSUE THREAD

**Issue by jstoll1233** [sentinelsat/sentinelsat#443]
Hello, I am trying to download sentinel 2 data from the Copernicus Open Access Hub, with a python script and using the sentinelsat library. I know that the rate at which you can download data is limited: max 2 concomitant downloads. However, I seem to have problems when I try to download a higher quantity of data (10-20 queries) one after the other in a for loop, therefore not in concomitance. The command api.download(<product_id>) does not trigger the download.

As a side question, could anyone indicate the contact at copernicus that I could report my problem to?

EDIT: Sorry for not adding any code, here is what I tried. This just end up printing "should have downloaded" without downloading anything.

note: `survey_coordinates_corals` here is juste my data containing coordinates and date.

import time
for surveyid, row in survey_coordinates_corals.iterrows():
    
    time.sleep(15)    
    
    #location paramenters for query
    lat1 = row['lat_start']
    lon1 = row['lng_start']

    lat2 = row['lat_end']
    lon2 = row['lng_end']
  
    #coordinates = str(lat1) + ' , ' + str(lon1)
    survey_coordinates = 'POLYGON ((' + str(lon1) + ' ' + str(lat1) +',' + str(lon1) + ' ' + str(lat2) +',' + str(lon2) + ' ' + str(lat2) + ',' + str(lon2) + ' ' + str(lat1) + ',' + str(lon1) + ' ' + str(lat1) + '))'

    #correct format for date and time interval
    date_survey = survey_coordinates_corals.loc[surveyid]['surveydate']
    date = str(date_survey)
    year = date[0:4]
    month = date[4:6]
    day = date[6:8]
    interval_start = year + '-' +month + '-' + day + 'T00:00:00.000Z-40DAYS'
    interval_end = year + '-' +month + '-' + day + 'T00:00:00.000Z+40DAYS'
    Date = (interval_start, interval_end)
    
   
    #the query and conversion to dataframe
    products = api.query(survey_coordinates, date= Date, area_relation='Intersects', 
                     platformname='Sentinel-2', limit = 5)
    if products:
        products_df = api.to_dataframe(products)
        
        #select s2 product with minimal cloudcoverage and download
        ID_min_cloud = products_df[['cloudcoverpercentage']].idxmin()[0]
        api.download(ID_min_cloud, directory_path='../option3-Sentinel2-data')
        print('should have downloaded')
        
    else:
        print('was empty')

**Comment by j08lue** [comment]
You need to be specific when asking questions on the internet. Please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for your issue, including date range and geometry. State which version of Sentinelsat you are using.

Perhaps also try to use `api.download_all`, which will handle the concurrency for you.

This is not a question for the Copernicus support, since it is more about how to use our library. But if you ever need it, you can find their email address at https://scihub.copernicus.eu/,

**Comment by jstoll1233** [comment]
> You need to be specific when asking questions on the internet. Please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for your issue, including date range and geometry. State which version of Sentinelsat you are using.
> 
> Perhaps also try to use `api.download_all`, which will handle the concurrency for you.
> 
> This is not a question for the Copernicus support, since it is more about how to use our library. But if you ever need it, you can find their email address at https://scihub.copernicus.eu/,

Sorry, you are right, it was not clear. I added the code in my question. Also, `api.download_all()` is not what I am looking for since I want to download only one product per query.

**Comment by j08lue** [comment]
### Product ID

This line

```python
ID_min_cloud = products_df[['cloudcoverpercentage']].idxmin()[0]
```

Is not doing what you think it is. You want to find the product with the minimum cloud cover. 
This line gives you the **index** of the product with the minimum cloud cover. Like, if it is the 5th row, `ID_min_cloud` will be `4`, which you are passing to `api.download`.  

You want to pass the ID of the product instead:

```python
ID_min_cloud = products_df[products_df[['cloudcoverpercentage']].idxmin()]
```

or this 

```python
ID_min_cloud = products_df.sort_values(by='cloudcoverpercentage', ascending=True)[0]
```

or something similar. Try around until you get it.

### More hints

Btw, no need to convert dates to string back and forth, which is hard to read and error-prone. Something like this should work:

```python
date_survey = survey_coordinates_corals.loc[surveyid]['surveydate'].to_pydatetime()
start = f'{date_survey:%Y-%m-%d}-40DAYS'
start = date_survey - datetime.timedelta(40)  # alternatively
```

The bounding box polygon you can make with Shapely instead, something like this:

```python
import shapely.geometry

survey_coordinates = shapely.geometry.box(row['lng_start'], row['lat_start'], row['lng_end'], row['lat_end']).wkt
```

But this is going way beyond the "minimal" part of your working example... 😄

**Comment by jstoll1233** [comment]
@j08lue Thank you very much for your response. From what I understood printing stuff in my code, when I convert the products into a dataframe, it takes the product ID's as index. In fact the dataframes look like this: 

![Capture](https://user-images.githubusercontent.com/44365154/116387239-e59fc000-a81a-11eb-8f08-27c7909dffd5.PNG)

So when I execute the line that you mentioned `ID_min_cloud = products_df[['cloudcoverpercentage']].idxmin()[0]`, ID_min_cloud = '25d9467c-e8d2-46c6-ba7a-15d41c9ec491' for example.
Isn't that what `api.download(ID_min_cloud )` wants?

**Comment by j08lue** [comment]
Ok, then that line was not doing what *I* thought it was. 😄 

```python
import sentinelsat
api = sentinelsat.SentinelAPI("user", "pw")
api.download("25d9467c-e8d2-46c6-ba7a-15d41c9ec491")
```

Works fine for me with Sentinelsat `v0.14.0` on Linux, Python 3.6.

**Comment by jstoll1233** [comment]
@j08lue it works. The problem was that I was trying to download multiple times the same sentinel 2 product. Every time a new sentinel 2 product is asked to be downloaded, it does download, but when the same s2 product is asked to be downloaded again, it skips this step. Which makes sense. 
Thank you for your help!
