### ISSUE TITLE
Copernicus Open Access hub moves API Hub URL

### ISSUE THREAD

**Issue by j08lue** [sentinelsat/sentinelsat#444]
>Open Access Hub users are informed that the API Hub URL has changed from https://scihub.copernicus.eu/apihub/ to https://apihub.copernicus.eu/apihub/ as of 28 April 2021.
> The former URL will not be dismissed. An automatic redirection to the new URL is performed transparently. 

https://scihub.copernicus.eu/news/News00868

I am currently getting `401 Unauthorized` errors on any requests to the old `/apihub`.

**Comment by j08lue** [comment]
The new URL works, though.

I suggest we change this in all our code and docs.

**Comment by i21510** [comment]
They claim 'an automatic redirection to the new URL is performed transparently', but this doesn't look transparent to me. I've sent an email to eosupport.

**Comment by zi-dan** [comment]
After changing URL I've still get `401 Unauthorized `error on both (old and new) URL

**Comment by Squiccio** [comment]
I added --url "https://apihub.copernicus.eu/apihub/" in the sentinelsat command and it worked

**Comment by brwe** [comment]
> After changing URL I've still get `401 Unauthorized `error on new created account (today). Old one works with new URL

@zi-dan I think it takes a few days for new credentials to work: https://scihub.copernicus.eu/twiki/do/view/SciHubWebPortal/APIHubDescription

**Comment by EmanuelCastanho** [comment]
Thank you for sharing this url update information.

**Comment by MrChebur** [comment]
Closes https://github.com/sentinelsat/sentinelsat/pull/445

**Comment by valgur** [comment]
Fixed in #450.
