### ISSUE TITLE
handling 50000+  geometries (hi from sentinelrequest)

### ISSUE THREAD

**Issue by oarcher** [sentinelsat/sentinelsat#447]
Hi there !

Here is my use case:

I've got a shapefile  (cyclone tracks) with 50000+ geometries (points). Each geometry is timestamped +-30 mn, and I want to be able to check if there is a sentinel1 acquisition over those points.

Sometimes, few points in the past are changing, so I've got to redo the  request.

2 years ago, I wrote [sentinelrequest](https://github.com/oarcher/sentinelrequest) that is able to handle this use case 

It has two main features:

### request caching
The query is hashed, and the xml file content is stored locally. So If I do the same request latter, the answer will be very fast. (useful when few points has changed in my big shapefile)

### geometries aggregation

my time series is from 2014 to now. I split it into several one or two weeks times series. Only one request will be done per time serie.
So from 50000+ requests from 2014 to now, it's now ~170 requests.

But the union off all geometries within one 15 days time serie is to complex to be handled by scihub.
Here a description of the problem, took from the ([demo notebook](https://github.com/oarcher/sentinelrequest/blob/master/README.ipynb)):

![image](https://user-images.githubusercontent.com/4264660/116563716-91710a80-a904-11eb-8a12-7a4421899ac3.png)

In green is the complex user request, and in red, the simplified scihub request.

The response from scihub is filtered against the user request, to remove extra results (in yellow).

This also allow sentinelrequest to handle very complex shapes, like high resolution coastlines.

## What's next ?

I've just migrated sentinelrequest today on github, and my plan was to refactor it completely (bad coding, some features are not well implemented).
It's not widely used, just by me and few people at my lab.

If sentinelsat can have those features one day, I will be happy to not maintain sentinelrequest anymore !

So might I can try to contribute to sentinelsat if you are Ok with those functionalities (I hope I will find some time ...)

**Comment by Fernerkundung** [comment]
That is an interesting use case to be using sentinelsat with. I agree with @j08lue that we are happy to see such use-cases but I also feel that it is best to have `sentinelsat` focus on the core functionality so you and other people of the community can build use-cases on-top of it.

Looking at your queries, do you think you could simplify the data, therefore reducing the query complexity so the results are returned faster? What happens if you fit a polyline through the points of your track measurement and then run a light simplification (e.g. with GeoPandas) over it? I assume this would reduce the query size for the tracks with minimal impact on the results of the queries you do.

**Comment by oarcher** [comment]
To use sentinelsat as a dependency for sentinelrequest, I think that it will be better if the cache handling is implemented on sentinelsat side.

@Fernerkundung , the goal of sentinelrequest is already to simplify the data , with something like 
```python
simple_shape = shapely.ops.unary_union(gdf.geometry).buffer(2).simplify(1.9)
``` 
So if gdf has complex (ie long wkt string) shapes with a lot of shapes close to each other (<= 2°), `simple_shape` will be a simple and short surrounding multi-polygon (.simplify(1.9)).

The rectangle bounding box is even shorter, but it's wider, and it increase a lot the result count.

So if the caching is handled from sentinelsat, sentinelrequest will just become a geopandas time/geometries resampler and coarser .

**Comment by Fernerkundung** [comment]
Caching of requests is, in my opinion, not within the scope of what `sentinelsat` aims to do. If `sentinelrequest` would have to rely on caching on the `sentinelsat` side then we probably should close this issue.

I am happy to be convinced of the contrary, i.e. if @valgur or @j08lue want to chime in?

**Comment by j08lue** [comment]
I agree. Let us please close this discussion here.
