### ISSUE TITLE
sentinelsat -d no longer downloads; prints debug messages

### ISSUE THREAD

**Issue by daniel-j-h** [sentinelsat/sentinelsat#455]
I'm testing master right now (2fc40841ff93b45c1833573e59962f923466ce20) and can see the following problem.

Before it was possible to use the `-d` switch to start the download, as in

    sentinelsat ... -d

but by now the `-d` semantic seems to have changed to printing debug messages.

And in fact `sentinelsat --help` shows that the `-d` flag is bound twice, once for download once for debug

```
  -d, --download                  Download all results of the query.
  -d, --debug                     Print debug log messages.
```

Ideally we should fix this and get the old behavior back. Or release a major version bump since it's breaking the API.

**Comment by daniel-j-h** [comment]
Seeing https://github.com/sentinelsat/sentinelsat/issues/454 this issue is potentially blocking a new release (or needs a major version bump)

**Comment by valgur** [comment]
Thanks for pointing this out, it's a bug for sure. Since `--debug` is a very secondary option and feature, I'd sat the obvious fix is to remove the `-d` flag from `--debug`.

**Comment by j08lue** [comment]
> Ideally we should fix this and get the old behavior back. Or release a major version bump since it's breaking the API.

Thank you so much for testing and pointing this out, @daniel-j-h. Major version bumps are only needed if you have a major version number. 😉 But we really have to have that soon!
