### ISSUE TITLE
API returned authentication error but user/password works on Scihub.copernicus.eu browser

### ISSUE THREAD

**Issue by mdelgadoblasco** [sentinelsat/sentinelsat#465]
Dear all,

I am getting surprised because my command-line scripts using sentinelsat for data retrieval are not working anymore. 
Since last days I am getting authentication error (HTTP Status 401 – Unauthorized) on scripts that were largely tested and worling perfectly.

Does any of you may know the reason why?
Has anything changed in the last days/week ?

Thank you very much in advance.
Best,
Manuel

**Comment by mdelgadoblasco** [comment]
Solved! Please consider an update based on this news from scihub:

https://scihub.copernicus.eu/news/News00868 

Alternatively you can use the command as :
api = SentinelAPI(user, password, 'https://apihub.copernicus.eu/apihub/')

**Comment by j08lue** [comment]
Fixed in #450, will be part of a release soon.

**Comment by sarpulas** [comment]
Ran into this just now thanks @mdelgadoblasco for the guidance towards the quick fix
