### ISSUE TITLE
Invalid checksum/Stream error while trying to download Sentinel-2 files

### ISSUE THREAD

**Issue by yechta** [sentinelsat/sentinelsat#467]
Ever since the IP update, I have difficulties accessing to the files I could before. I updated sentinelsat to the latest release and added 'https://apihub.copernicus.eu/apihub' to access the SentinelAPI. I also make sure to get data from a month before.

I either get stream error or invalid checksum(corrupted file) errors whatever file I try to access.

Should I wait until they complete their migration or is it a sentinelsat problem?

Thanks.

**Comment by Dacoher** [comment]
I'm having the same issue with some products Id but as far as I know it seems to be the APIs fault....

**Comment by j08lue** [comment]
Can you post a minimal example and the traceback, please, and also state which version you are using? Please consider testing with latest master or wait a few days and then test with our new release. Please also include an ID of a failing product. 

*If* the problem originates from a mismatch between the file and the checksum that DHuS says the file should have, then this is an issue for their hotline instead. But you need to document that this is the case first.

**Comment by AmbitionY** [comment]
the sentinelsat  Version: 0.14 ，when I try to download S2 datas and the same problems occurs. 
InvalidChecksumError                      Traceback (most recent call last):
InvalidChecksumError: File corrupt: checksums do not match

**Comment by yechta** [comment]
I solved the problem by adding checksum=False as a parameter while downloading the file.

**Comment by j08lue** [comment]
> I solved the problem by adding checksum=False as a parameter while downloading the file.

That is not a fix, just 🙈 😉

**Comment by pandagud** [comment]
I'm having the same issue with Sentinel-2 getting the InvalidChecksumError

**Comment by j08lue** [comment]
Sample UUIDs, please?

**Comment by MapperIT** [comment]
Hi, 
I am having the same issue with Sentinel-2. 
One of the the products that I am trying to download is: '462b650d-bf33-443c-9ca4-090474161c72'

**Comment by paalge** [comment]
I see this also
`ff88c4da-738e-4cad-b56d-fc71d04ac4cc
481730f1-394b-4c81-ba97-0e7425ca282c
`

**Comment by valgur** [comment]
@paalge These two are caused by server-side bugs. The product download URLs return the following errors:
* Internal Server Error: UnsupportedOperationException : Error creating stream from file /mnt/s2bl1c/dhus/incoming/x6/x9/x1/S2B_MSIL1C_20210430T104619_N0300_R051_T32VLK_20210430T115541.zip
* Internal Server Error: UnsupportedOperationException : URL stream cannot be opened

**Comment by valgur** [comment]
@MapperIT That product has an interesting server-side bug, thanks for pointing it out. Its metadata states that the product is online but when you actually try to download it it responds with `202 Accepted` meaning it was accepted for retrieval from the LTA.

This incorrect behavior is not handled as well as it could be on our side. There are two options to make it more correct:
* Fail the download if the response is 2xx but not `200 OK` - that is, the product is offline.
* Do not trust the OData metadata at all and instead rely on the HTTP response status code for the online status of the products.

I'm inclined to go with the latter. PR is incoming...

**Comment by j08lue** [comment]
Thanks for investigating and fixing this, @valgur!

When ever the metadata and actual status do not agree, we should send an automated email to eosupport@copernicus.esa.int. Jokes aside - will anyone tell them about this problem and perhaps post their response here? @MapperIT and/or @paalge, perhaps?

**Comment by VasilisAle** [comment]
> @MapperIT That product has an interesting server-side bug, thanks for pointing it out. Its metadata states that the product is online but when you actually try to download it it responds with `202 Accepted` meaning it was accepted for retrieval from the LTA.
> 
> This incorrect behavior is not handled as well as it could be on our side. There are two options to make it more correct:
> 
> * Fail the download if the response is 2xx but not `200 OK` - that is, the product is offline.
> * Do not trust the OData metadata at all and instead rely on the HTTP response status code for the online status of the products.
> 
> I'm inclined to go with the latter. PR is incoming...

I am trying to access the response status code, but I get response 401. How did u access the response code of each product id?
