### ISSUE TITLE
Not able to download Sentinel products 

### ISSUE THREAD

**Issue by WalidGharianiEAGLE** [sentinelsat/sentinelsat#470]
I am trying to download some scenes from Sentinel 1/2 just for testing, but I getting a stream of errors, and no scenes were downloaded. I tried different start date and end dates and yet the problem is still the same. 
Here is the link to the data and an example jupyter notebook https://github.com/WalidGharianiEAGLE/test1/tree/devm/sentinelsat
I installed this library yesterday.

**Comment by valgur** [comment]
Can you try again with the development version please? We are close to publishing it as a proper release.
```
pip install git+https://github.com/sentinelsat/sentinelsat.git --upgrade
```
The error you are getting looks like something that could have been fixed or at least improved with #448.

**Comment by j08lue** [comment]
Nice documentation of your issue(s) with the notebook. 

The first issue, `TypeError: __init__() got an unexpected keyword argument 'initial'`, seems to be something weird going on with `tqdm`. If that is still the same when you test with the current dev version, please also `pip install --upgrade tqdm` and try again.

**Comment by WalidGharianiEAGLE** [comment]
Thank you for the feedback! I updated the notebook again with the latest dev version and upgraded tqdm.  
The error related to tqdm is no longer an issue, but new errors were highlighted in `sentinel.py` when downloading and no products were downloaded.

**Comment by valgur** [comment]
There's a server-side issue causing all downloads to fail right now. Keep an eye on the announcements at https://scihub.copernicus.eu/ and try again later.

**Comment by WalidGharianiEAGLE** [comment]
Alright the service is back and I was able to download some products except the offline ones.

**Comment by valgur** [comment]
Thanks for the bug report @WalidGharianiEAGLE! The sample notebook was extra useful since I personally have not used sentinelsat with a notebook in ages and it highlighted some spots we are clearly lacking in: #479, #480, #481. Thanks!
