### ISSUE TITLE
Download Error with HTTP Status 500

### ISSUE THREAD

**Issue by BenMueller** [sentinelsat/sentinelsat#483]
Hey everyone, having some issues downloading imagery with SentinelSat. I previously was able to download imagery about a month ago, but now today I'm having the following issues (I've cut it down to the relevant parts):

`bmueller@rocketship$ sentinelsat -d --uuid b1118e1c-0486-43a7-a722-37cd3427d0fb --url https://scihub.copernicus.eu/dhus`

`b1118e1c-0486-43a7-a722-37cd3427d0fb is online. Starting download`

(...)

`There was an error downloading S1B_IW_GRDH_1SDV_20210418T001439_20210418T001504_026514_032A76_B435
Traceback (most recent call last):
  File "/home/bmueller/.local/lib/python3.9/site-packages/sentinelsat/sentinel.py", line 1431, in _check_scihub_response
    response.raise_for_status()
  File "/home/bmueller/.local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://scihub.copernicus.eu/dhus/odata/v1/Products('b1118e1c-0486-43a7-a722-37cd3427d0fb')/$value`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "/home/bmueller/.local/lib/python3.9/site-packages/sentinelsat/sentinel.py", line 888, in _download_online_retry
    return self.download(id, directory_path, checksum, **kwargs)
  File "/home/bmueller/.local/lib/python3.9/site-packages/sentinelsat/products.py", line 178, in download
    return sentinelsat.SentinelAPI.download(self, id, directory_path, checksum, **kwargs)
  File "/home/bmueller/.local/lib/python3.9/site-packages/sentinelsat/sentinel.py", line 527, in download
    self._download_outer(product_info, path, checksum)
  File "/home/bmueller/.local/lib/python3.9/site-packages/sentinelsat/sentinel.py", line 565, in _download_outer
    product_info["downloaded_bytes"] = self._download(
  File "/home/bmueller/.local/lib/python3.9/site-packages/sentinelsat/sentinel.py", line 1194, in _download
    _check_scihub_response(r, test_json=False)
  File "/home/bmueller/.local/lib/python3.9/site-packages/sentinelsat/sentinel.py", line 1477, in _check_scihub_response
    raise ServerError(msg, response)
sentinelsat.exceptions.ServerError: HTTP status 500 Internal Server Error: UnsupportedOperationException : URL stream cannot be opened
9 retries left`

(... continues 9 more times)

The most relevant lines seem to be the following:
`requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://scihub.copernicus.eu/dhus/odata/v1/Products('b1118e1c-0486-43a7-a722-37cd3427d0fb')/$value`
`sentinelsat.exceptions.ServerError: HTTP status 500 Internal Server Error: UnsupportedOperationException : URL stream cannot be opened`

I've tried numerous things, such as replicating the error on a Windows machine with a fresh Python install and upgrading to the latest prerelease version in this repo, creating a new account and switching the URLs from apihub, even [using wget](https://scihub.copernicus.eu/userguide/BatchScripting) as explained on the batch scripting site (gives the same error) etc. without success.

I did note that some previously closed errors mentioned that Scihub had some outage issues the last few days, but I haven't seen anything posted today about any outages. Anyone else having these issues?

Thanks!

**Comment by j08lue** [comment]
Does downloading from the SciHub web interface not work either? That is the ultimate test. If that fails, write to EO Support.

Besides that, the only official machine download endpoint is the `apihub.copernicus.eu/apihub`, so you should not use `/dhus` or anything.

**Comment by BenMueller** [comment]
Hmm, yeah even the web interface fails on these; checking with slightly newer imagery of the same location works just fine. Going to reach out to support, thanks!

**Comment by valgur** [comment]
While the main Copernicus Open Access Hub (SciHub) is having server-side issues, you can try out any of the mirrors and alternative data providers listed here: https://github.com/Fernerkundung/awesome-sentinel
