### ISSUE TITLE
Sentinel 5P downloaded products corrupted. NO2 Data

### ISSUE THREAD

**Issue by joseurquiza88** [sentinelsat/sentinelsat#485]
Hello!
when I try to download S5P data (NO2  data) through a python command and I always get the same error :

**" MD5 checksumming: 100%|██████████|  Invalid checksum. The downloaded file for '0f91d161-f0f9-4e91-b0d5-75b8b7eb00d3' is corrupted.' is corrupted"** 

Stopping the download and trying to download again. But without downloading any images at the end. The download never ends

My code below:

```python
from sentinelsat import SentinelAPI, read_geojson, geojson_to_wkt
from datetime import date
import pandas
import os

api = SentinelAPI('s5pguest', 's5pguest', 'https://s5phub.copernicus.eu/dhus/')
footprint = geojson_to_wkt(read_geojson('corte.geojson'))
products = api.query(footprint, date=(date(2020, 4, 1), date(2020, 4, 3)), producttype='L2__NO2___', platformname='Sentinel-5')
api.download_all(products)
```

**Comment by valgur** [comment]
Downloading that product works ok for me, can't reproduce. 
```python
api = SentinelAPI('s5pguest', 's5pguest', 'https://s5phub.copernicus.eu/dhus/')
products = api.query(uuid="0f91d161-f0f9-4e91-b0d5-75b8b7eb00d3")
api.download_all(products)
```

If you delete the failed product and try again, does that get rid of the problem for you? Also, are you using the latest sentinelsat version (1.0.0)?

**Comment by StijnCaerts** [comment]
Recently, a lot of Sentinel-5 products don't have a checksum in the odata response. For example https://s5phub.copernicus.eu/dhus/odata/v1/Products('96cc1433-b327-4d98-9ed0-f5a6c4a0f612').

This causes the download to fail:
```
~/Documents/venvs/sentinelsat/lib/python3.8/site-packages/sentinelsat/sentinel.py in download_all(self, products, directory_path, max_attempts, checksum, n_concurrent_dl, lta_retry_delay, **kwargs)
    719             iterable=product_ids, desc="Fetching archival status", unit=" products"
    720         ):
--> 721             info = self.get_product_odata(pid)
    722             product_infos[pid] = info
    723             is_online = not self.trigger_offline_retrieval(pid)

~/Documents/venvs/sentinelsat/lib/python3.8/site-packages/sentinelsat/sentinel.py in get_product_odata(self, id, full)
    442         response = self.session.get(url)
    443         _check_scihub_response(response)
--> 444         values = _parse_odata_response(response.json()["d"])
    445         values["quicklook_url"] = self._get_odata_url(id, "/Products('Quicklook')/$value")
    446         return values

~/Documents/venvs/sentinelsat/lib/python3.8/site-packages/sentinelsat/sentinel.py in _parse_odata_response(product)
   1581         "title": product["Name"],
   1582         "size": int(product["ContentLength"]),
-> 1583         product["Checksum"]["Algorithm"].lower(): product["Checksum"]["Value"],
   1584         "date": _parse_odata_timestamp(product["ContentDate"]["Start"]),
   1585         "footprint": _parse_gml_footprint(product["ContentGeometry"]),

AttributeError: 'NoneType' object has no attribute 'lower'
```

This is with version 1.0.1 of the sentinelsat library.

**Comment by joseurquiza88** [comment]
Yes, I installed the new version of sentinelsat library but nothing happens.

I was trying to download that data for a polygon in Argentina, I don't know if that would be it.

On the other hand, no file is downloaded to me at the end since the checksum file is downloaded (sometimes it reaches 100% and other times it does not), and it is automatically deleted from my computer and the download starts again and so on continuously.

In response to @StijnCaerts What does it mean that a lot Sentinel-5 products don't have a checksum in the odata response? Could it be that there is no data for the area for the mentioned period?

(I apologize if my English is not the best)
Thank you very much for your help!

**Comment by valgur** [comment]
I'm not seeing any missing checksum values anymore at https://s5pguest:s5pguest@s5phub.copernicus.eu/dhus/odata/v1/Products, so I'm assuming this was a temporary problem on the SciHub side. Feel free to re-open if it's still an actual problem, though.
