### ISSUE TITLE
Installation of sentinelsat

### ISSUE THREAD

**Issue by CharlesNickmilder** [sentinelsat/sentinelsat#489]
Hello,
I have been using sentinelsat on my personnal laptop for some time and I have run into a couple of problems when I tried to deploy my code on our server. I will shortly describe them and how I managed to get past so it might offer improvement clues. I am not sure about the exact error messages given that I didn't paste them when I had them.

The first problem was that the default python was 2.7. This means that the behaviour of pip is quite strange. In order to install properly the package use python3 -m install sentinelsat.

The second problem was that I installed the library in a specific directory using the --target option of pip, mainly for portability and maintenance. It might have messed with the organisation of the library: the sentinelsat "executable" (the thing you need to call when using the command line interface) was in the bin sub-directory and couldn't manage to "touch" the rest of the code (error of type "can't find sentinelsat.cli"). I had to make a copy of this executable in the installation directory with a different name. This gives in the installation directory:

- bin
- sentinelsat (directory)
- sentinelsat0 (executable like file)

To use this executable I have to change the beginning of the command line: "sentinelsat ..." becomes ".~/sentinelsat0 ...", "./" being the installation repository.

Maybe our server was messed up that I had to modify that much but let's hope it will be usefull for others to have this troubleshooting leads.

**Comment by j08lue** [comment]
You mean `python3 -m pip install sentinelsat`, right? Why do you have to change things compared to where `pip` places executables etc.? You might also have an old version of `pip` and could update that with `python3 -m pip install --upgrade pip`.

But you should probably consider using a virtual environment instead, which you by the way can place anywhere, in case the location of the packages matters to you.

I think there is nothing special about the way we organize our entrypoint script. Could you perhaps follow a more standard path (virtualenv or conda env) and try again?

**Comment by CharlesNickmilder** [comment]
Hi,
You are right I forgot the pip :)
The reason I changed the instllation path is that I work on a shared and modular server. This involves that some parts of the server might change at any moment, that other users might need and install other version of sentinelsat and to make sure that I can simply copy paste the directory from one machine to another if I want to go on another server.  Moreover, the home directories (where it installs the lib by default) is really small and we have been asked by the system manager to avoid having files on this partition.
It might be usefull to go on a virtual env or a docker but I have never done things like that so I will leave it for later :)
Given the troubles I had during the re-installation, I'm not very happy with the idea of messing with the installation again.
Thanks for the answer.

**Comment by j08lue** [comment]
> It might be usefull to go on a virtual env

```
python3 -m venv /path/to/big/disk/venvs/myapplication
source /path/to/big/disk/venvs/myapplication/bin/activate
pip install --upgrade pip
pip install sentinelsat
```

That places your Python virtual environment on some other disk outside your home dir.

I'll close this now then.
