### ISSUE TITLE
Sentinel-2 L1C data can not be downloaded and unzipped correctly

### ISSUE THREAD

**Issue by tdk8823** [sentinelsat/sentinelsat#497]
Hi, 
I'm trying to get Sentinel-2-L1C data via sentinelsat(version 1.0.1) python API.
I got zip file, but I was not able to unzip the file.
My code and the results is here.

```python
import zipfile
from sentinelsat import SentinelAPI

product_id = "1ec665a8-0f23-40d1-b5d8-b29175afbc0a"
api = SentinelAPI(DHUS_USER, DHUS_PASSWORD)
products = api.query(uuid=product_id)
df_products = api.to_geodataframe(products)
print(f"file size: {df_products.loc[product_id, 'size']}")
api.download_all(products)

with zipfile.ZipFile("S2B_MSIL1C_20180727T012649_N0206_R074_T54SUE_20180727T031235.zip") as zf:
    zf.extractall()
```
![image](https://user-images.githubusercontent.com/57826615/121327931-d8640e00-c94e-11eb-94ff-889803cdc7df.png)

As the result shows, I found that the size of downloaded file is only 16.9Mbyte. I think file size should be 778.54Mbyte according to product metadata.
So there should be something wrong with downloading process.

**Comment by j08lue** [comment]
Please report the product ID to eosupport@copernicus.esa.int and let us know what they say. Seems like the product is broken upstream.

**Comment by serbyy** [comment]
same issue as above

**Comment by avalentino** [comment]
same here

**Comment by tdk8823** [comment]
I tried to get the data from Open Access Hub (https://scihub.copernicus.eu/dhus/#/home), but results were same.
So, I also think that the file is broken upstream.

Anyway, I sent a mail to copernicus support team, and I'll report you the response.

**Comment by tdk8823** [comment]
@j08lue 

I got response from Open Access Hub support team.
As show bellow, this issue seems to have occurred during data migration in their server.

--------------------------------------------------
With reference to your enquiry, please be informed that this is a known issue caused by the Open Access Hub Migration occurred on 28th April 2021. 
Please note that we have informed the technical team to check your product. We will let you know as soon as we receive their feedback. 
 
We would like to confirm that the technical team is already investigating on this issue and a period of adaptation where they are fine tuning the system configurations is currently ongoing, unfortunately causing a period of temporary unscheduled unavailability of the service.  
 
For more details, please refer to the news available at: https://scihub.copernicus.eu/news/News00871 
--------------------------------------------------

**Comment by j08lue** [comment]
Thanks @tdk8823 

> period of adaptation where they are fine tuning the system configurations

haha. Let's hope that period is soon over and the fine detail is fixed that they ship broken products that still pass the checksum test...

**Comment by j08lue** [comment]
Anyways, this is depressing to have open as an issue on Sentinelsat until they fix it, so please allow that I close this.
