### ISSUE TITLE
Please, allow downloading in different directories with download_all()

### ISSUE THREAD

**Issue by fpl** [sentinelsat/sentinelsat#500]
The download_all() method permits to specify one single download directory for all ids. It would be nice having the possibility to select a different download dir for each file, even. This could be useful with long series of off-line products, for instance.

**Comment by Fernerkundung** [comment]
You could just query all the product_ids that you are looking for, create a tuple for the folders and then use a loop over the `download` function to achieve this. I don't see how adding this functionality to the `download_all` function would help here, because the hard part is mapping all the folders that you want.

https://github.com/sentinelsat/sentinelsat/blob/d4591065a83b00814837ce3d0e7237d05d15706e/sentinelsat/sentinel.py#L472

**Comment by j08lue** [comment]
@fpl, moving files is extremely cheap, at least as long as the source and target are on the same disk. So you can easily create the mapping from downloaded product (file) to the folder structure you want and move the files afterwards.

With that easy solution at hand and this, IMO, being a use case very specific to your way of organizing your data, I think this is out of scope for Sentinelsat. What do you think, @Fernerkundung?

**Comment by fpl** [comment]
> You could just query all the product_ids that you are looking for, create a tuple for the folders and then use a loop over the `download` function to achieve this. I don't see how adding this functionality to the `download_all` function would help here, because the hard part is mapping all the folders that you want.
> 
> https://github.com/sentinelsat/sentinelsat/blob/d4591065a83b00814837ce3d0e7237d05d15706e/sentinelsat/sentinel.py#L472

Yes, this is exactly what I'm doing, but it is sub-optimal in case of LTA products, because the auto-retrying and download stream pool is not managed easily.

**Comment by j08lue** [comment]
I think your best option for now is to subclass (or monkeypatch) `SentinelAPI` and change for example the `_get_filepath` to return an absolute path, so the `directory_path` will actually not end up being used. Like so:

```python
api = SentinelAPI(**credentials)

directories = {
    "some-uuid": Path("/my/absolute/path")
}

def my_get_filename(self, product_info):
    product_id = product_info["uuid"]
    download_dir = directories[product_id]
    return download_dir / SentinelAPI._get_filename()

api._get_filename = my_get_filename

api.download_all()
```

Unless you get some more supporters for this feature, I think this is too much of a special use case to implement. I hope you are okay with that decision.
