### ISSUE TITLE
Possible breakage of service... 

### ISSUE THREAD

**Issue by fpl** [sentinelsat/sentinelsat#503]
This is just for your information, apparently the Copernicus service can be stuck for days on specific downloads, this is an example of it.
Still not working after some days... 

```
downloading S2B_MSIL2A_20210611T095029_N0300_R079_T34UDG_20210611T122043 data file...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sentinelsat/sentinel.py", line 1433, in _check_scihub_response
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://apihub.copernicus.eu/apihub/odata/v1/Products('cf5040de-e64b-4e92-bc34-8cc191e4b5f5')/$value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/frankie/scihub/scihub.py", line 565, in <module>
    api.download(id=uniqid, directory_path=os.path.join(outdir,sub))
  File "/usr/local/lib/python3.7/dist-packages/sentinelsat/sentinel.py", line 523, in download
    is_online = not self.trigger_offline_retrieval(id)
  File "/usr/local/lib/python3.7/dist-packages/sentinelsat/sentinel.py", line 645, in trigger_offline_retrieval
    _check_scihub_response(r, test_json=False)
  File "/usr/local/lib/python3.7/dist-packages/sentinelsat/sentinel.py", line 1479, in _check_scihub_response
    raise ServerError(msg, response)
sentinelsat.exceptions.ServerError: HTTP status 500 Internal Server Error: UnsupportedOperationException : Error creating stream from file /mnt/s2bl2a/dhus/incoming/x7/x7/x9/S2B_MSIL2A_20210611T095029_N0300_R079_T34UDG_20210611T122043.zip
```

**Comment by lvhengani** [comment]
I am also getting an error: 
`Scihub error: HTTP status 500 Internal Server Error: UnsupportedOperationException : Error creating stream from file /mnt/s2al1c/dhus/incoming/x2/x1/x9/S2A_MSIL1C_20210613T075611_N0300_R035_T34HGH_20210613T095621.zip
`
Initially, I thought its a connection issue on my side, but it is persisting even today.  Anyone knows or has a solution to this.?

**Comment by j08lue** [comment]
Thanks for reporting. Please tell the ESA EO Support about those products.

**Comment by joooeey** [comment]
I have the same problem and got a reply from ESA EO support:

> Thank you for your reply and for reporting the issue.
> 
> Please note that we have informed the technical team to check your products. We will let you know as soon as we receive their feedback.
> 
> We would like to inform you that this is a known issue already under the technical team investigation.
> 
> However, in the meantime, we would suggest you should check the availability of Sentinel archive data on the DIAS providers, which are the followings:    
> •             ONDA => More information on ONDA-DIAS can be found at: https://www.onda-dias.eu/cms/     
> •             MUNDI => More information on MUNDI-DIAS can be found at: https://mundiwebservices.com/    
> •             WEkEO => More information on WEkEO can be found at: https://www.wekeo.eu/offer    
> •             CREODIAS => More information on CREODIAS can be found at: https://creodias.eu/    
> •             Sobloo => More information on Sobloo can be found at: https://sobloo.eu/    
>       
> Apologies for the inconvenience this may cause you.
> 
> We will let you know as soon as we receive the technical team feedback.

Looks like none of the DIAS providers listed provide the DHuS API.
