### ISSUE TITLE
KeyError when downloading specific Sentinel 2 bands (SentinelProductsApi)

### ISSUE THREAD

**Issue by Justin-Sexton87** [sentinelsat/sentinelsat#505]
Hi, 
This may be a very specific issue.
Using sentinelsat 1.0.1. Python 3.8. on a windows machine if it matters.

# The Error:
 
I was trying to download specific bands from Sentinel 2 data to make an NDVI image without having to grab the whole zip.
The products search seemed ideal but I was getting the following error:

`
KeyError: 'repID'
`

The offending line is in `products.py` at line 218:

```
216    data = dict(
217        id=element.attrib["ID"],
218        rep_id=element.attrib["repID"],
219    )
```
I was able to fix this just by removing line 218 entirely. It didn't cause any extra issues, rep_id doesn't seem to be used anywhere.  I figure some sort of check is needed? is rep_id used in some other satellites / sources?

# Example
```
# setup
from sentinelsat import SentinelAPI, SentinelProductsAPI, make_path_filter
user = '<name>'
password = '<password>'

# The api for downloading nodes inside the product
product_api = SentinelProductsAPI(user, password)

# Skipping the part where you find the product
# create a filter to find the bands. This downloads the B04 and B08 bands at 10 m resolution for making NDVI images
nodefilter = make_path_filter("*_B0[48]_10m.jp2")

# This actually downloads the files
# I was using this product id which was active at the time
product_api.download('8fffde83-f60b-4773-b6db-d7452df8fcc0', nodefilter=nodefilter)
```

# Possible solution
Note I haven't actually tried this as I was able to just delete the line entirely.
```
try:
    data = dict(
        id=element.attrib["ID"],
        rep_id=element.attrib["repID"],
    )
except KeyError:
    data = dict(
        id=element.attrib["ID"]
    )
```

A more complete solution may be to identify all the 'attributes' that actually exist and only parse the ones that do. I'm not sure exactly what this code is doing.

**Comment by j08lue** [comment]
@avalentino, do you remember why you try to read the "rep_id" property? It is not used anywhere, it seems.

https://github.com/sentinelsat/sentinelsat/blame/d4591065a83b00814837ce3d0e7237d05d15706e/sentinelsat/products.py#L218

Removing it would be the right solution in that case. A PR for that is welcome, when we get confirmation from @avalentino.

**Comment by avalentino** [comment]
@j08lue yes I confirm that `repID` can be safely removed.
Personally I doubt that anyone will ever need to make a filter on it so `repID` can be just removed without attempting to check if it exists or not.

**Comment by j08lue** [comment]
Great, thanks for the clarification @avalentino. @Justin-Sexton87, will you make PR for removing that line?

**Comment by Justin-Sexton87** [comment]
Yep, I'll give it a go.

**Comment by j08lue** [comment]
Closed with PR.
