### ISSUE TITLE
Any reliable mirrors for metadata requests?

### ISSUE THREAD

**Issue by i21510** [sentinelsat/sentinelsat#507]
Hi

I'm trying to use a mirror just a as secondary source for metadata in case esa servers fail. The following request
```
                api = SentinelAPI(user, pwd, timeout=60, api_url=url)
                data = api.get_product_odata('7451f4cf-d359-4e4d-93e8-4fc64d13ffa8')
```
Does not seem to work with any of the mirrors I've tried. Mirrors https://finhub.nsdc.fmi.fi/apihub/ and https://colhub.met.no/apihub/ return the following:

```
HTTP status 404 Not Found: 
# HTTP Status 404 -
/apihub/odata/v1/Products('7451f4cf-d359-4e4d-93e8-4fc64d13ffa8')

 **type** Status report

 **message**
_/apihub/odata/v1/Products('7451f4cf-d359-4e4d-93e8-4fc64d13ffa8')_

 **description** _The requested resource is not available._

* * *

### Apache Tomcat/8.0.36
```

According to what I've read in #302, this is related to the DHus version these mirrors use

Mirror https://ipsentinel.ipma.pt/apihub/ returns the following:

```
HTTPSConnectionPool(host='ipsentinel.ipma.pt', port=443): Max retries exceeded with url: /apihub/odata/v1/Products('7451f4cf-d359-4e4d-93e8-4fc64d13ffa8')?$format=json (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
```
Am I missing any configuration details? Is there any reliable mirror that works just like ESA servers? 

Regards

**Comment by j08lue** [comment]
Are you sure that the two mirrors use the `/apihub` route? It looks like both `finhub` and `colhub` do not have any route (like `/dhus`) when you access them in the browser. So maybe just drop the `/apihub` from both and try that?

Similar for `ipsentinel`, although the response is different there.

You cannot be sure that they have all the data that you expect, though. I do not know what their ingestion strategy is - which areas, how fast...

**Comment by i21510** [comment]
After removing /apihub from the url, finhub.nsdc.fmi.fi changed the error message, colhub.met.no answered the query successfully and ipsentinel.ipma.pt returned the same error message as before

```
https://finhub.nsdc.fmi.fi/
Invalid key (7451f4cf-d359-4e4d-93e8-4fc64d13ffa8) to access Products
-----------------------
https://colhub.met.no/ 
/usr/lib/python3.6/ssl.py:809: ResourceWarning: unclosed <ssl.SSLSocket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.40', 36350), raddr=('193.167.135.37', 443)>
  server_hostname)
OK
-----------------------
https://ipsentinel.ipma.pt/ 

HTTPSConnectionPool(host='ipsentinel.ipma.pt', port=443): Max retries exceeded with url: /odata/v1/Products('7451f4cf-d359-4e4d-93e8-4fc64d13ffa8')?$format=json (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
```
I've found some info on the mirrors:
https://sentinels.copernicus.eu/web/sentinel/missions/collaborative/existing-planned#terrascope
https://sentinel.esa.int/web/sentinel/missions/collaborative/national-points-of-contact

It's worth taking a look at the technical annexes on the second link. So far , it looks like the norwegian site is the only mirror that meets all of the following:

-  Retrieves data directly from satellite
-  Not limited to a certain region, set of region or time frame

It still have to check it, but Luxembourg site seems to mirror the whole archive too, although I haven't read anything about them having their own ground stations.

**Comment by i21510** [comment]
Turns out Norway mirror does not retrieve as many products as ESA when requesting available products within a time frame

**Comment by j08lue** [comment]
If you have a Copernicus Services Project, there is one more ESA-official mirror for those at https://cophub.copernicus.eu/.
