### ISSUE TITLE
checksumName AssertionError when download S2 L1C files with SentinelProductsAPI

### ISSUE THREAD

**Issue by tvoirand** [sentinelsat/sentinelsat#517]
Hello,

When trying to download a specific band from Sentinel-2 L1C products using the SentinelProductsAPI, I am getting an AssertionError related to the checksumName of the file.

My code:

```python
from sentinelsat import SentinelProductsAPI
from sentinelsat import make_path_filter

products_api = SentinelProductsAPI("user", "password")
nodefilter = make_path_filter("*_TCI_60m.jp2")
products_api.download(
    "7ca53cd5-12da-4cc2-be28-fe0e6ec478fb",  # I found the product ID using an API query in my actual script
    nodefilter=nodefilter,
)
```

The error I am getting:

```python
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    products_api.download("7ca53cd5-12da-4cc2-be28-fe0e6ec478fb", nodefilter=nodefilter)
  File "/Users/thibautvoirand/creation/programmation/sentinelsat/sentinelsat/sentinelsat/products.py", line 197, in download
    node_infos = self._filter_nodes(manifest_path, product_info, nodefilter)
  File "/Users/thibautvoirand/creation/programmation/sentinelsat/sentinelsat/sentinelsat/products.py", line 134, in _filter_nodes
    dataobj_info = _xml_to_dataobj_info(elem)
  File "/Users/thibautvoirand/creation/programmation/sentinelsat/sentinelsat/sentinelsat/products.py", line 234, in _xml_to_dataobj_info
    assert elem.attrib["checksumName"].upper() == "MD5"
AssertionError
```

In the manifest file, all checksum names are SHA3-256 instead of MD5. It seems that the checksum algorithm was changed from MD5 to SHA3 for Sentinel-2 recently: https://sentinel.esa.int/web/sentinel/-/update-of-copernicus-sentinel-2-level-1c-and-level-2a-processing-baselines-1/1.0?redirect=%2Fweb%2Fsentinel%2Fnews%2F-%2Fasset_publisher%2FxR9e%2Fcontent%2Fid%2F3626427

If I understand correctly the code should be updated to accept both algorithms?

I have taken a few minutes to try to find a fix. For now I am getting stuck because it seems the OData API still indicates MD5 as checksum algorithm in `sentinel.py` `get_product_odata` function, even though the manifest file indicates SHA3 as checksum algorithm.

Many thanks!

**Comment by valgur** [comment]
This should be pretty easy to fix - will just need to use `hashlib.sha3_256()` instead of MD5 based on the OData attribute. Thanks for mentioning this! I might create a PR soon.

**Comment by tvoirand** [comment]
Thank you for the fix !
