### ISSUE TITLE
Sentinel 3 SLSTR Data Access via https://scihub.copernicus.eu/dhus

### ISSUE THREAD

**Issue by ramonmelser** [sentinelsat/sentinelsat#520]
I am trying to use sentinelsat to query S3 SLSTR data, however, only SY and OL data are returned when I query all S3 products. 
A previous issue on this page appeared to address the same issue, but the solution seemingly no longer works. 

I'm using 'https://scihub.copernicus.eu/dhus' in the SentinelAPI function, and my query is as following:
`products = api.query(footprint,
                     date=('20160101', '20201201'),
                     platformname='Sentinel-3',
                     cloudcoverpercentage=(0, 100))`

Please advise

**Comment by valgur** [comment]
The SLSTR products are missing the `cloudcoverpercentage` attribute and the `cloudcoverpercentage=(0, 100))` filter is excluding them since it's not in that range, strictly speaking. You can either drop that filter term or perhaps use something like
```python
products = api.query(footprint, date=('20160101', '20201201'), platformname='Sentinel-3', raw='(cloudcoverpercentage:[0 TO 20] OR instrumentshortname:SLSTR)')
```

**Comment by ramonmelser** [comment]
Dropping the cloudcoverpercentage argument solved it!
