### ISSUE TITLE
failed with response: HTTP/1.1 429 Too Many Requests

### ISSUE THREAD

**Issue by DocBO** [sentinelsat/sentinelsat#522]
Hi,
we have an app based on sentinelsat which worked very robust and stable until recently (maybe one to two weeks?).

This is one of the errors which occur lately:
```
sentinelsat.exceptions.ServerError: HTTP status 500 Internal Server Error: HttpResponseException : request: POST https://most.onda-dias.eu/v3/auth/tokens HTTP/1.1  [Sensitive data in payload, use jclouds.wire.log.sensitive override to enable logging this data.] failed with response: HTTP/1.1 429 Too Many Requests
```

We take care not to spawn many downloads, so a single download any time.

Any ideas how to prevent this? Maybe it's just temprorary.

**Comment by DocBO** [comment]
For those who encountered also some errors, it seems to be connected to a time range, where the links on dhus are broken

**Comment by panditamas93** [comment]
I have encountered the same problem. 
Does that mean that for the last few weeks all links are broken?
Did you find any fix for this?

**Comment by adamwickenden** [comment]
This happening for me on the majority of requests, regardless of date.

**Comment by j08lue** [comment]
Please ask Copernicus EO Support about this. Looks like some weird 500 (server-side) error - not sure why it somehow turns into a 429 at the end...

**Comment by valgur** [comment]
To clarify - does this happen during downloads or for search queries?

**Comment by adamwickenden** [comment]
Search queries behave as expected. It happens on download only, and its not consistent. I have managed to download a few tiles, but the majority of requests fail at the moment.

Have only been trying to download Sentinel 2 - L2A, haven't tried any other products or satellites.

**Comment by valgur** [comment]
I'm pretty sure this is due to the quota on concurrent LTA retrievals being exceeded (which is 1 product every hour or so, I think): https://forum.step.esa.int/t/esa-copernicus-data-access-long-term-archive-and-its-drawbacks/15394
There is currently no mechanism in sentinelsat to account for that quota, so it gets hit almost immediately when trying to retrieve multiple products.

**Comment by adamwickenden** [comment]
Personally i've been using download(), and filtering using the is_online() check. I'm not too sure if its related to the LTA as i've been requesting images from the last 3 months. However, I have noticed that there seems to be far less online products at the moment, it seems the window for remaining online has reduced significantly (products from early may are no longer online, is this normal? approx 3 months of online products?)
