### ISSUE TITLE
Downloading Sentinel 3 OLCI with SentinalApi

### ISSUE THREAD

**Issue by lenkafronkova** [sentinelsat/sentinelsat#527]
Hello, I am trying to download Sentinel 3 data with the script below which worked half a year ago, but now throws the following error. Do you have any idea why this could be the case? I also tried to turn it into a geodataframe/dataframe and loop through the uuids, but the same error. I installed SentinelSat using pip and working with Python 37 (Anaconda). Version:
sentinelsat               1.0.1                    pypi_0    pypi

`fromsentinelsat import SentinelAPI, read_geojson, geojson_to_wkt` 
` import pandas as pd` 
` import os` 

` downloadPath = "Z:/DP434/Working_Area/Data/Forel_Ule/Sentinel_3/2020/09/"` 
` os.chdir(downloadPath)` 

#read password and name from a text file
def apiLogin(login_doc, url):
    log_in = pd.read_csv(login_doc, sep="\t")
    user = log_in.loc[0][1] # get username
    password = log_in.loc[1][1] #get password
    
    #eumetsat credentials to login
    api = SentinelAPI(user, password, url)
    
    return api

`#read area of interest`
`footprint = geojson_to_wkt(read_geojson('Z:/DP434/Working_Area/Data/Forel_Ule/analysis/aoi/aoi.geojson'))`

`#define search start and end dates (format) for sensing`
`filter_start_date ='2020-09-01T00:00:00.000Z'`
`filter_end_date = '2020-09-30T23:59:59.000Z'`

`url = 'https://coda.eumetsat.int/'`

    #########################sentinel 3 ocean data######################################
    api = apiLogin(login_doc =login_file ,
             url= url)
    
 ` 
  products_s3 = api.query(footprint, 
          beginposition = (filter_start_date,filter_end_date), 
          area_relation='Intersects', 
          producttype='OL_2_WFR___')
  print(len(products_s3))`
    
`api.download_all(products_s3)` 

` File "C:\Users\LF06\.conda\envs\python_37\lib\site-packages\sentinelsat\sentinel.py", line 590, in _get_filename
    filename = cd.split("=", 1)[1].strip('"')
AttributeError: 'NoneType' object has no attribute 'split'`

**Comment by j08lue** [comment]
This was fixed in #495. Please update to latest `main` (e.g. `pip install --upgrade git+https://github.com/sentinelsat/sentinelsat.git`).
