### ISSUE TITLE
Outdated tqdm version requirement

### ISSUE THREAD

**Issue by jlandmann** [sentinelsat/sentinelsat#534]
Hi all,
I'm testing right now the great improvements from #532. Everything seems to work for me (thank you so much!), it's only that I got a `TqdmKeyError` for a missing key `delay`. I tried tqdm version 4.62 and it worked fine for me, while currently in `requirements.txt` only version 4.27 is required.
I suggest to change the version to minimum 4.62, and I can make a mini-PR for this, if you like.

**Comment by valgur** [comment]
Thanks! I updated the `requirements.txt`. The minimum version for `delay` appears to be 4.58 from February: https://github.com/tqdm/tqdm/releases/tag/v4.58.0
