### ISSUE TITLE
ServerError: HTTP status 500 Internal Server Error: UnsupportedOperationException : 

### ISSUE THREAD

**Issue by xianglingliwei** [sentinelsat/sentinelsat#536]
ServerError: HTTP status 500 Internal Server Error: UnsupportedOperationException : Error creating stream from file /mnt/restored/x2/x1/x2/S2A_MSIL2A_20190318T184101_N0211_R070_T11SKV_20190319T003454.zip

![image](https://user-images.githubusercontent.com/54316252/131607372-55e9db59-f587-4fa1-97f5-3a0ee3161847.png)

**Comment by xianglingliwei** [comment]
hello sir，I don't konw why this happen. please help me.

**Comment by ks716** [comment]
Maybe since the file is already requested from LTA and you are trying to re-request or download the same file .. This kind of issue arises. Thats my understanding please correct me if I am wrong :)

**Comment by valgur** [comment]
Upgrade to v1.1 if you have not already (`pip install -U sentinselsat`). If that does not help, then seek support from eosupport@copernicus.esa.int. There is nothing we can do on the sentinelsat client side to fix this issue, really.
