### ISSUE TITLE
Question about SciHub's data publication timeliness

### ISSUE THREAD

**Issue by ks716** [sentinelsat/sentinelsat#537]
I had a question on how often does scihub update data regularly, like is yesterday's data available today or in how many days can i get access to the latest data and is this trend in updation of data regular or depends on what factors?. I tried finding resources to readup on how scihub processes sentinel 2 data but could find none. If anyone can point me towards it, it would be a great help. Thanks!!

**Comment by j08lue** [comment]
I am not aware of any official overview of publication timeliness. Maybe that also depends on region / ground segment? Some dates are in the metadata, so perhaps just run a big query for your AOI and calculate some stats over the difference between `endposition` and `publicationdate`. Pls share your results here.

**Comment by Fernerkundung** [comment]
The publication time depends on a multitude of factors, most of which are the product type, acquisition plan and ground processing station. In general there are very little NRT (Near-Realtime) products created for Sentinel-2 and the regular L1C and L2A product types (https://sentinel.esa.int/web/sentinel/missions/sentinel-2/data-products) are considered NTC (Non Time Critical).

In my experience most products will be available within 2-4 days after acquisition. However - if there have been bottlenecks in the downstream or the ground station baseline processing this can be up to multiple weeks for older acquisitions to catch up and be published. 

For building a model of how long publication takes for a specific tile, product type and or ground station I propose you build a query over the metadata available in [Google BigQuery](https://console.cloud.google.com/bigquery?p=bigquery-public-data&d=cloud_storage_geo_index&t=sentinel_2_index&page=table) which should give you the answer to that in a single query that can execute in a few minutes.
