### ISSUE TITLE
Search by tile not working properly (tileid information is missing for L2A products?)

### ISSUE THREAD

**Issue by cordmaur** [sentinelsat/sentinelsat#538]
Hi, 
I've noticed a strange behavior when using <b>tileid</b> in the query.
When I search using <b>tileid</b>, only L1C products are found. 
Here is an example:
![image](https://user-images.githubusercontent.com/19617404/132510142-b47ddb39-f5bd-49c0-9aaa-ad0fe1804985.png)

When we look at the products DataFrame, it seems that a lot information (including tileid) from the L2-A products are missing (rightmost columns):
![image](https://user-images.githubusercontent.com/19617404/132510578-5bf4abbd-48d3-40fc-83a4-87dd6ac8db0e.png)

Additionally, I am receiving the `UnsupportedOperationException` for most L2-A images... I don't know if that's because of these missing info.

Would appreciate any help,
Thanks,
Maurício

**Comment by j08lue** [comment]
Yes, we have a note on this in the docs, actually https://sentinelsat.readthedocs.io/en/stable/api_overview.html#search-sentinel-2-l1c-by-tile. The docs also have an alternative way to search that should also work for L2A products.

It is the Copernicus Open Access Hub that defines which metadata are available for the different products. Please drop them a kind note if you would like to put in a vote for better tile search support for L2A.
