### ISSUE TITLE
Download TCI file only

### ISSUE THREAD

**Issue by ZenBel** [sentinelsat/sentinelsat#540]
Hello,

I am trying to download only the TCI file using `sentinelsat`. I use the following code:

`api = SentinelAPI('username', 'password')`
`path_filter = make_path_filter("*_TCI_10m.jp2")`
`api.download('c8579d0d-07ee-4b79-861d-4abb87672659', nodefilter=path_filter)`

and I got the product ID from an `api.query()`. However, only the `manifest.safe` is downloaded and not the TCI file.

Any idea what I am doing wrong?

Thanks in advance,

Zeno

**Comment by avalentino** [comment]
Hi @ZenBel probably you should include the path of the file inside your product (see also the [example](https://sentinelsat.readthedocs.io/en/stable/api_overview.html#downloading-parts-of-products) in the documentation).

Something like

```python
path_filter = make_path_filter("GRANULE/*/IMG_DATA/*_TCI_10m.jp2")
```


Not sure if the following works:

```python
path_filter = make_path_filter("**_TCI_10m.jp2")
```

**Comment by ZenBel** [comment]
Hi @avalentino  and thanks for the reply. I've tried both fixes but without success: only the `manifest.safe` file gets downloaded.

**Comment by avalentino** [comment]
ah, you are right.
There is a small bug in the functions the performs the node filtering, the component path is converted to lowercase before performing the pattern matching:

```python
def node_filter(node_info):
    match = fnmatch.fnmatch(node_info["node_path"].lower(), pattern)
    return not match if exclude else match
```

The quickest solution at the moment is to also use lowercase letters in the pattern. The following should work:

```python
path_filter = make_path_filter("*_tci_*.jp2")
```

I will try to prepare a PR to fix this ASAP.

**Comment by ZenBel** [comment]
Ah! there it is! Thanks a lot for the fix.

Z
