### ISSUE TITLE
DOWNLOAD SPECIFIC BANDWIDTHS

### ISSUE THREAD

**Issue by demtotal** [sentinelsat/sentinelsat#545]
Greetings everyone,

I'm developping a tool that perform some geospatial analysis, it's meant to be used on very large areas (size of countries), in order to do so i'm using sentinelsat python package to download sentinel-2 data automatically, i use these data to compute NDVI and EVI and therefore i only need B04, B08 and B02. So my question is: is it possible to only download these three bands instead of the whole product?

When i applied the node filter the api only downloaded  an .xml file (on the same tile without node filter it downloaded the whole product correctly), here's what i put on the node filter:

`        nodefilter = make_path_filter("*B0[248]*",exclude=False)
        api.download_all(products_df_sorted.index, nodefilter=nodefilter)`

Any help, comment or example is welcome.
Thanks in advance .

**Comment by avalentino** [comment]
Hi @demtotal, I think that your problem is connected to #540.
The issue should be fixed in the current main branch.
Coutd you please try with the it an tell us if it works for you?
