### ISSUE TITLE
Slow download speed

### ISSUE THREAD

**Issue by JackLidge** [sentinelsat/sentinelsat#547]
Hi all, 

I've been building sentinelsat into an application and I've noticed that quite often there are some very slow download speeds. As far as I can see I'm not downloading LTA data so I'm a bit puzzled as to why this is. 

Here is an output for some downloads I've been doing using the `api.download()` for specific tiles. I'm doing this for each individual tile as I'm checking in the products dataframe output from `api.query()` to see if a file has previously been downloaded.

```
Downloading S2B_MSIL2A_20211003T110809_N0301_R137_T30UXC_20211003T142740.zip: 100%|██████████████████████████████████████████████████████████████████████████████████████| 1.18G/1.18G [02:47<00:00, 1.47MB/s]
Downloading S2B_MSIL2A_20211003T110809_N0301_R137_T30UWC_20211003T142740.zip: 100%|███████████████████████████████████████████████████████████████████████████████████████| 1.02G/1.02G [23:11<00:00, 734kB/s]
Downloading S2A_MSIL2A_20211001T112121_N0301_R037_T30UWC_20211001T142311.zip: 100%|███████████████████████████████████████████████████████████████████████████████████████| 1.14G/1.14G [37:50<00:00, 503kB/s]
Downloading S2A_MSIL2A_20211001T112121_N0301_R037_T30UXC_20211001T142311.zip: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 404M/404M [12:35<00:00, 535kB/s]
Downloading S2A_MSIL2A_20210928T110841_N0301_R137_T30UWC_20210928T141544.zip: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 823M/823M [25:32<00:00, 537kB/s]
Downloading S2A_MSIL2A_20210928T110841_N0301_R137_T30UXC_20210928T141544.zip:  74%|█████████████████████████████████████████████████████████████████▍                      | 793M/1.07G [27:42<09:32, 477kB/s]
```

I'm doing this on an EC2 instance in the eu-west-1 region, and the download speed is normally quite fast. I'm wondering whether setting a higher number of concurrent downloads will have an effect? Or could this be because I am running `api.download()` for each individual tile? Would it be better to remove all the already downloaded tiles from the dataframe then run one big `download_all()` command?

Any advice on this would be much appreciated.

**Comment by kssvrk** [comment]
EC2 instance has a specific bandwidth. Higher Concurrency will slow down your individual download. But total time to download x number of products individually or concurrently should be roughly same. 

Same case is with dataframe efficiency also as far as i know
