### ISSUE TITLE
overview of sentinelsat-compatible mirrors?

### ISSUE THREAD

**Issue by joooeey** [sentinelsat/sentinelsat#552]
In the issue comments I often notice references to other DHuS mirrors. Is there an overview which are compatible with sentinelsat and what regions and timeframes they cover somewhere? I've found [this overview from ESA](https://sentinels.copernicus.eu/web/sentinel/missions/collaborative/existing-planned#terrascope) but no idea if this is helpful. Some of them only seem to have a GUI.

Right now I'm looking for a service that has global coverage 20 months back. However I think it would be useful if we maintained a list inside this repository. I found it really confusing at the start that `SentinelAPI` has a `api_url` parameter but there are no docs what URLs one can enter.

**Comment by joooeey** [comment]
So far, all I've found besides `scihub.copernicus.eu/dhus` and `apihub.copernicus.eu/apihub` is `colhub.met.no` but their archive only goes back 27 days.

**Comment by joooeey** [comment]
There's a list of mirrors [here](https://github.com/Fernerkundung/awesome-sentinel). That page implies that they are all national mirrors but at least the Norway appears to have data from all over the world but it only has recent data.

**Comment by Fernerkundung** [comment]
The national mirrors are a governance concept that was introduced with the Copernicus project. They are in full control by each nation to decided what data to mirror and also what software they use.

If you can find or create a resource that lists all publicly available deployments of DHuS compatible mirrors (i.e. ones that can be used with sentinelsat) I'll gladly merge it into my list and I am sure we can add it to the documentation of this repo as well.

**Comment by Fernerkundung** [comment]
Closing due to missing information - please respond to this issue to get it reopened.
