### ISSUE TITLE
"Error: API returned unexpected response 400 ." in a query

### ISSUE THREAD

**Issue by VasilisAle** [sentinelsat/sentinelsat#553]
Hello everyone,

I've installed the sentinelsat version == 0.6.5 and as a newone I am trying to execute this code part.

```python
from sentinelsat.sentinel import SentinelAPI, get_coordinates

api = SentinelAPI('user', 'password', 'https://scihub.copernicus.eu/dhus')

api.query(get_coordinates(map.geojson), \
                  "20161119", date(2016, 12, 29), \
                   keywords={"platformname": "Sentinel-2", \
                   "cloudcoverpercentage": "[0 TO 90]"})
```

However, when I execute it I get the message
 "Error: API returned unexpected response 400 ." and by printing the query I got None. 

I've checked the geojson file and seems ok and also covers big area.

I can't understand what's the problem..Any help will be really useful!

Thanks in advance,
Vasileios

**Comment by valgur** [comment]
v0.6.5 is absolutely ancient. Please try again with the latest version first.

**Comment by VasilisAle** [comment]
Yes, you are right! I just fixed it by installing the right library dependencies in the right way. Then, I installed the v0.14 and it worked.
