### ISSUE TITLE
How to check online/offline products with http response code?

### ISSUE THREAD

**Issue by VasilisAle** [sentinelsat/sentinelsat#555]
Hi all,

Based on a previous issue #467, I try to check the http response code of each product_id, since the metadata are not reliable enough.

I've a snippet of code and I get response 401 (it seems that I don't know use the credentials each time).  

```python
product_info = api.get_product_odata(id)
is_online = product_info['Online']
url = product_info['url']
res = requests.get(url)
print(res)
```

I also tried to use `requests.post(url,auth = HTTPBasicAuth('username','password'))`, but I got response 500.

Any help will be useful.

Vasileios

**Comment by valgur** [comment]
You can try `response = self.session.head(product_info["url"])`, if `api.is_online(product_id)` is failing you, and check the `response.status_code` as it is done in [download.py](https://github.com/sentinelsat/sentinelsat/blob/main/sentinelsat/download.py#L446-L504).

Do let us know whether that works or not. Looks like that inconsistency is still not fixed on the server side.

**Comment by Fernerkundung** [comment]
Closing due to missing information - please respond to this issue to get it reopened.
