### ISSUE TITLE
Double problem. LTA and checksum

### ISSUE THREAD

**Issue by janceviciusjulius** [sentinelsat/sentinelsat#556]
Good afternoon,

firstly I would like to a say, that about 3 months the same code worked absolutely fine and everything was okey. But now I have some problems:
1. It freezes then last file checksum is counting.
2. My downloading function:
![image](https://user-images.githubusercontent.com/64422065/156751459-ed130e8c-b73f-4094-b727-9d49b253cb4a.png)
max_attempts = 5, lta_retry_delay = 10 and sometimes it freezes then everything is downloaded and one lta file is left. So time period is short and it cant be that program is waiting. I waited 1 hour and nothing changed.

I will add some photos as examples. Program is working from beginning now. 

Looking forward to hearing from you.

**Comment by janceviciusjulius** [comment]
![image](https://user-images.githubusercontent.com/64422065/156773474-7036b4a9-5f4a-4813-a30c-016da0f74aee.png)
Great example, which shows that it stops

**Comment by Fernerkundung** [comment]
Have you tried running that code on another machine or with another version of Python? With the information you provide here it is almost impossible to estimate if that is a `sentinelsat`, a server side or a local client issue.

**Comment by Fernerkundung** [comment]
Closing due to missing information - please respond to this issue to get it reopened.
