### ISSUE TITLE
Returning metadata of offline products as well with sentinelsat?

### ISSUE THREAD

**Issue by kn0av** [sentinelsat/sentinelsat#557]
Hi guys and girls,
I’m wondering if its possible to get the metadata of offline products as well, instead of only online products using SentinelAPI.query().
I have this code that works fine for recent data, where they’re still online, and it returns the ‘title’ of the metadata, so I can easily download it later if I want, the function returns this:

![image](https://user-images.githubusercontent.com/35092729/158122727-db94a182-d095-4b66-9927-4ffa49b82463.png)

Now if I try to search for older data; they are all offline and so the query will return that there’s no available product… but I have manually searched on the copernicus website and found some offline.
Is there some way that I can change the SentinelAPI.query() to return the metadata even though it is offline?

Thanks a lot in advance!

**Comment by valgur** [comment]
See _[Python API: Getting Product Metadata](https://sentinelsat.readthedocs.io/en/stable/api_overview.html#getting-product-metadata)_ in the docs.
