### ISSUE TITLE
couldn't query all Sentinel2 images for the year of 2016 and 2017 

### ISSUE THREAD

**Issue by chryseisho** [sentinelsat/sentinelsat#558]
**Aim:** to get all available Sentinel-2 Level 1C products for a tile (e.g.T32UPU) in 2016 and 2017.

**Script:**

```python
tiles = ['32UPU']

query_kwargs = {
        'platformname': 'Sentinel-2',
        'producttype': 'S2MSI1C',
        'date': ('20160101', '20171231'),
        'relativeorbitnumber': (65)
        }

products = OrderedDict()
for tile in tiles:
    kw = query_kwargs.copy()
    kw['tileid'] = tile
    kw['raw'] = f'tileid:{tile} OR filename:*_T{tile}_*'
    pp = api.query(**kw)
    products.update(pp)

#export the result to excel to see all information
gdf = api.to_geodataframe(products)
gdf.to_excel("/Users/path...")

```

**Result:** Almost all images within this time period have been queried successfully, but there is a gap between 2016-12 and 2017-04. I first thought this is because ESA didn't publish data for this tile during these months, but then I checked manually on scihub ([https://scihub.copernicus.eu/dhus/#/home](https://scihub.copernicus.eu/dhus/#/home)) and able to get images from this time period. So it might be an issue with the sentinelsat query.

**Question:** Is this the problem with sentinelsat package? If this is, how could I fix it, or any other better alternatives you would recommend to automatically download this large amount of sentinel2 images? Thanks!!

**Comment by Fernerkundung** [comment]
Closing due to missing information - please respond to this issue to get it reopened.
