### ISSUE TITLE
sentinelsat.exceptions.InvalidChecksumError, but the file does not exist on the server

### ISSUE THREAD

**Issue by MrChebur** [sentinelsat/sentinelsat#559]
Attempting to download the scene:
https://apihub.copernicus.eu/apihub/odata/v1/Products('d6baf006-6f7d-4310-bf3a-8a0a345da394')/$value

But the file doesn't exist and the download doesn't start (even with a browser).
I assume the API must be changed to check if this is the real scene before downloading it and throwing `sentinelsat.exceptions.InvalidChecksumError`

Instead it have to throw: 
`sentinelsat.exceptions.InvalidKeyError: Invalid key (does not exists) to access Products` 

How to reproduce:

```
import sentinelsat 
sat = sentinelsat.SentinelAPI("login", "password", 'https://apihub.copernicus.eu/apihub/')
sat.download('d6baf006-6f7d-4310-bf3a-8a0a345da394', directory_path=r'G:\!Download', checksum=True)
```
Output:
```
Downloading S2A_MSIL1C_20210827T070621_N0301_R106_T41VMG_20210827T080915.zip:   0%|          | 0.00/667M [00:00<?, ?B/s]
Traceback (most recent call last):
  File "<input>", line 3, in <module>
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\sentinelsat\sentinel.py", line 590, in download
    return downloader.download(id, directory_path)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\sentinelsat\download.py", line 150, in download
    self._download_common(product_info, path, stop_event)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\sentinelsat\download.py", line 229, in _download_common
    raise InvalidChecksumError("File corrupt: checksums do not match")
sentinelsat.exceptions.InvalidChecksumError: File corrupt: checksums do not match
```

**Comment by valgur** [comment]
Can't reproduce. That product downloaded without any issues for me.

**Comment by MrChebur** [comment]
Indeed. Perhaps these were temporary problems.

**Comment by congju-fu** [comment]
I also encountered the same problem as you, did you solve it?

‘’‘
sentinelsat.exceptions.InvalidChecksumError: File corrupt: checksums do not match
‘’‘

**Comment by MrChebur** [comment]
> did you solve it?

It was a temporary problem. I didn't do anything.

**Comment by congju-fu** [comment]
> > did you solve it?
> 
> @congju-fu It was a temporary problem. I didn't do anything.

Thanks.

It has been solved. It indeed was a temporary problem.
