### ISSUE TITLE
Add return to CLI script

### ISSUE THREAD

**Issue by SlowMo24** [sentinelsat/sentinelsat#561]
When building a tool on sentinelsat, it would be great to be able to reuse the provided CLI. Currently one has to implement their own CLI that will then query the Python-API but of course there will be much duplication to https://github.com/sentinelsat/sentinelsat/blob/main/sentinelsat/scripts/cli.py .

I'm not sure if this a valid use case or feasible (considering that different options return different data). 

For example if https://github.com/sentinelsat/sentinelsat/blob/7cf7854f6b86477d8b389337bb6c0168b3e4ea0b/sentinelsat/scripts/cli.py#L372 , https://github.com/sentinelsat/sentinelsat/blob/7cf7854f6b86477d8b389337bb6c0168b3e4ea0b/sentinelsat/scripts/cli.py#L377 ,  https://github.com/sentinelsat/sentinelsat/blob/7cf7854f6b86477d8b389337bb6c0168b3e4ea0b/sentinelsat/scripts/cli.py#L384 and https://github.com/sentinelsat/sentinelsat/blob/7cf7854f6b86477d8b389337bb6c0168b3e4ea0b/sentinelsat/scripts/cli.py#L400 would `return` their result instead of printing, or duping it, it could be used in other workflows e.g. to further process the downloaded data.

**Comment by valgur** [comment]
Ok, that would be a fine addition by me. Feel free to create a PR.
