### ISSUE TITLE
Error when downloading sentinel3 data

### ISSUE THREAD

**Issue by ziqing97** [sentinelsat/sentinelsat#567]
Hi,

I am trying to download the data from sentinel 3 using this tool and this is what I have done. 
```python
from sentinelsat import SentinelAPI, read_geojson, geojson_to_wkt
from datetime import date

api = SentinelAPI(myusername, mypassword, 'https://scihub.copernicus.eu/dhus/#/home')
products = api.query(filename = '*S3A_SR_2_LAN____*LN3_O_NT_004*', date=('2021-04-01T00:00:00.000Z', '2021-04-30T00:00:00.000Z'))
 
api.download_all(products)
```

however I got the error like this for every product I was trying to get

sentinel.py", line 1065, in _check_scihub_response
    raise SentinelAPIError(msg, response)
sentinelsat.exceptions.SentinelAPIError: HTTP status 200 OK: 

which I found strange since status 200 looks very positiv.

If I change the time to 
```python
date=('2022-04-01T00:00:00.000Z', '2022-04-30T00:00:00.000Z')
```

the script did actually nothing. Nothing was downloaded and no error was returned. 

does anyone know the reason and how can I fix this?

Thanks a lot.

**Comment by valgur** [comment]
The API URL you are using (`'https://scihub.copernicus.eu/dhus/#/home'`) is incorrect. You can simply leave it unset for `scihub.copernicus.eu`. Does that fix things for you?

**Comment by ziqing97** [comment]
> The API URL you are using (`'https://scihub.copernicus.eu/dhus/#/home'`) is incorrect. You can simply leave it unset for `scihub.copernicus.eu`. Does that fix things for you?

Hi,

thanks for your replying! Yeah, this did work for the first problem, but I still got nothing if I set the time to April 2022. (Also no errors)

**Comment by ziqing97** [comment]
OK, I got the problem, according to the esa

„Following the renewal of the ESA S3 Processing Services, the former Land Processing Centre codes "LN1", "LN2" and "LN3" will no longer be used. Instead two new Centre Codes "PS1" and "PS2" will be used to identify the new Processing Services. Nominally "PS1" corresponds to the service performing the systematic processing of "S3-A" data and "PS2" to the service performing the systematic processing of "S3-B" data”

which  means I need to delete LN3 in the 'filename'
```python
filename = '*S3A_SR_2_LAN____*O_NT_004*'
```

and it works
