### ISSUE TITLE
Missing OCN products ?

### ISSUE THREAD

**Issue by Rignak** [sentinelsat/sentinelsat#568]
Hello, I was trying to retrieve the OCN products for Sentinel-1A. I assumed every GRD is associated with one OCN, but it seems that a lot of L2 OCN are missing.

For products in 2022, it works well. Here I put the two limit datetimes, then the filenames retrieved by the API :
2022-01-05T03:24:43Z 2022-01-05T03:25:13Z
         S1A_IW_GRDH_1SDV_20220105T032458_20220105T032523_041320_04E983_328B.SAFE
         S1A_IW_SLC__1SDV_20220105T032457_20220105T032524_041320_04E983_CA7C.SAFE
         S1A_IW_OCN__2SDV_20220105T032458_20220105T032523_041320_04E983_FC19.SAFE
         S1A_IW_RAW__0SDV_20220105T032454_20220105T032527_041320_04E983_C0FA.SAFE

But for earlier products, OCN aren't returned :
2018-01-02T03:24:18Z 2018-01-02T03:24:48Z
         S1A_IW_SLC__1SDV_20180102T032432_20180102T032459_019970_022034_E3C2.SAFE
         S1A_IW_GRDH_1SDV_20180102T032433_20180102T032458_019970_022034_AC23.SAFE
         S1A_IW_RAW__0SDV_20180102T032430_20180102T032502_019970_022034_B102.SAFE
2019-01-21T03:24:25Z 2019-01-21T03:24:55Z
         S1A_IW_SLC__1SDV_20190121T032439_20190121T032506_025570_02D661_E585.SAFE
         S1A_IW_GRDH_1SDV_20190121T032440_20190121T032505_025570_02D661_8075.SAFE
         S1A_IW_RAW__0SDV_20190121T032436_20190121T032508_025570_02D661_8A3B.SAFE
2020-01-04T03:24:31Z 2020-01-04T03:25:01Z
         S1A_IW_SLC__1SDV_20200104T032445_20200104T032512_030645_038307_36BE.SAFE
         S1A_IW_GRDH_1SDV_20200104T032446_20200104T032511_030645_038307_B986.SAFE
         S1A_IW_RAW__0SDV_20200104T032443_20200104T032515_030645_038307_01ED.SAFE
2021-01-10T03:24:37Z 2021-01-10T03:25:07Z
         S1A_IW_SLC__1SDV_20210110T032451_20210110T032518_036070_043A46_F369.SAFE
         S1A_IW_GRDH_1SDV_20210110T032452_20210110T032517_036070_043A46_41D2.SAFE
         S1A_IW_RAW__0SDV_20210110T032448_20210110T032521_036070_043A46_676E.SAFE

It looks like it changed in february/march 2021 : 
2021-02-15T03:24:36Z 2021-02-15T03:25:06Z
         S1A_IW_SLC__1SDV_20210215T032450_20210215T032517_036595_044C91_B1E1.SAFE
         S1A_IW_GRDH_1SDV_20210215T032451_20210215T032516_036595_044C91_9CD9.SAFE
         S1A_IW_RAW__0SDV_20210215T032447_20210215T032520_036595_044C91_2148.SAFE
2021-03-11T03:24:36Z 2021-03-11T03:25:06Z
         S1A_IW_SLC__1SDV_20210311T032450_20210311T032517_036945_0458B9_0F84.SAFE
         S1A_IW_RAW__0SDV_20210311T032447_20210311T032520_036945_0458B9_698C.SAFE
         S1A_IW_GRDH_1SDV_20210311T032451_20210311T032516_036945_0458B9_1B96.SAFE
         S1A_IW_OCN__2SDV_20210311T032451_20210311T032516_036945_0458B9_312A.SAFE

Is that intended ? I think I remember being able to list OCN products previously, even before 2021.

**Comment by Fernerkundung** [comment]
Are you getting the same list of responses when using the DHuS webinterface? I assume what you are seeing has more to do with data availability on the server and not `sentinelsat`. 

If the data however is available via the webinterface and not `sentinelsat` then this would actually be a bug.

**Comment by Rignak** [comment]
You are right: I can't retrieve the data from the hub either. I was under the impression that OCN products were generated for each observation over the sea, but it seems to be the case only since 2021.
