### ISSUE TITLE
 Can't fiter cloud

### ISSUE THREAD

**Issue by geoschen** [sentinelsat/sentinelsat#571]
Why can't I filter cloud cover with this parameter
E.g:
```python
output_dir = r"d:\江浙沪皖Sentinel-2(20220101-0831)"             
query_excel_fn = "搜索结果.xls"      
success_excel_fn = "success.xls"     
aoi_geojson_fp = r'C:\Users\DELL\Desktop\各省json合集\jiangzhehu.geojson'# 感兴趣区域的GeoJSON文件
query_kwargs = {  # 查询的参数
    "platformname" :'Sentinel-2',
    "date" : ('20220101','20220831'),
    "producttype" : 'S2MSI1C',
    'cloudcoverpercentage':'15'
    # "sensoroperationalmode" : 'IW',
    # "orbitnumber" : 16302,
    # "relativeorbitnumber" : 130,
    # "orbitdirection" : 'ASCENDING',
}
```

**Comment by valgur** [comment]
The `cloudcoverpercentage` param needs to be a range instead of a single value: `"cloudcoverpercentage": (0, 15)`.

I concur that this can be a bit confusing after using the CLI first, where the argument is used to set the maximum value of the range.

**Comment by geoschen** [comment]
> The `cloudcoverpercentage` param needs to be a range instead of a single value: `"cloudcoverpercentage": (0, 15)`.
> 
> I concur that this can be a bit confusing after using the CLI first, where the argument is used to set the maximum value of the range.

thanks
