### ISSUE TITLE
Make_path_filter with several conditions

### ISSUE THREAD

**Issue by siana1234** [sentinelsat/sentinelsat#574]
Hi,

I am downloading S2 data and I want to download only one band. I use make_path_filter in order to define my filter, for example:
path_filter = make_path_filter("*B01*", exclude=False) to download only B01 band. It works but I also need xml files that are available in the products. How can I add an other condition in make_path_filter to download one band and xml files ?

Thanks in advance for your help.

**Comment by siana1234** [comment]
Hi @avalentino,
Thank you for your answer but I still don't understand how to create a nodefilter permitting to download only one jp2 band (only B01 for example) and all xml files included in a S2 product. In all examples I saw (in your reference [3] for example), there is only one type of downloaded file.
With the glob module I think I can't specify multiple filetypes.
With the command : path_filter = make_path_filter("*B01*", exclude=False), I download all files containing the string 'B01' but I would to define a path_filter with 2 conditions: path_filter = make_path_filter(["*B01*",'*.xml'], exclude=False). However I can't use a list in make_path_filter. 
Do you have an idea of the correct syntax ?
Thank you for your help.

**Comment by avalentino** [comment]
Dear @cOsprey,
your solution is perfectly fine.
Anyway, if you wan to submit a patch I would recommend to extend the existing function to accept both a single pattern and a list.
Something like the following (not tested):

```python
def make_path_filter(pattern, exclude=False):
    """Generate a nodefilter function to download only files matching the specified pattern.

    Parameters
    ----------
    pattern : str, sequence[str]
        glob patter (or sequence of patterns) for files selection
    exclude : bool, optional
        if set to True then files matching the specified pattern are excluded. Default False.

    .. versionadded:: 0.15
    .. versionchanged:: 1.2.0
       The `pattern` parameter can also be a list of patterns.
    """

    patterns = [pattern] if isinstance(pattern, str) else pattern

    def node_filter(node_info):
        match = False
        for pattern in patterns:
            match = fnmatch.fnmatch(node_info["node_path"], pattern)
            if match:
                break

        return not match if exclude else match

    return node_filter
```

**Comment by avalentino** [comment]
Another options could be to have a function to chain existing node filters.
E.g. (not tested):

```python
def chain_filters(filters, op=operator.or_, exclude=False):
    """Generate a nodefilter function by chaining a sequence of note filter.

    Parameters
    ----------
    filters : sequence
        sequence of node filter to be evaluated according to the operator `op`
    op : opriona operator
        operator used to chain the input node filters (default `or`)
    exclude : bool, optional
        if set to True then files matching the specified pattern are excluded. Default False.

    .. versionadded:: 1.2.0
    """
    def node_filter(node_info):
        results = [nodefilter(node_info) for nodefilter in filters]
        result = functools.reduce(op, results)
        return not result if exclude else result

    return node_filter
```

**Comment by cOsprey** [comment]
Dear @avalentino ,
I tested both the methods you suggested locally, the first one seems easier for understanding & usage.
Can you suggest which one should we prefer ?
Would like to know your thoughts.
Thank you!

**Comment by avalentino** [comment]
@cOsprey if you only need to filter basing on glob pattern the first solution is for sure simpler to use.
It should be enough to answer the @siana1234 question.

The second one is more general because you can chain any kind of node filter, including the ones based on the data size or any other node property.

**Comment by cOsprey** [comment]
@avalentino, thank you for the explanation I get a more better understanding.
True, the second one is surely more general. I will follow and will submit a request for the same.
Also please do let me know if there is something more required alongside with request.
Thank You!

**Comment by avalentino** [comment]
If you plan to make a PR you could include both the functions.
By the way I'm not a developer/maintainer of this package, @valgur and @j08lue for sure may have better advices.

**Comment by cOsprey** [comment]
Thank you @avalentino !
Will wait for @valgur  & @j08lue.

**Comment by kr-stn** [comment]
This is a community project - no need to wait for approval of creating a PR if you (aka. part of the community) have an improvement proposal that other people think makes sense as well. Go forth and contribute - that's why this project is open source! 👍 

To quote our own contribution guide
>Welcome to the sentinelsat open source project. We invite anyone to participate by contributing code, reporting bugs, fixing bugs, writing documentation and tutorials and discussing the future of this project.

**Comment by siana1234** [comment]
@cOsprey and @avalentino, thank you very much for your help, it's exactly what I need !
