### ISSUE TITLE
Convert raw data to an image

### ISSUE THREAD

**Issue by AgentNemo00** [sentinelsat/sentinelsat#580]
Hello,

I'm trying to write my own tool for downloading and converting the data to an image. Downloading the data does not seem to be a problem as it is well documented but I do not understand the raw data at all. I found out that there are a bunch of netcdf files but I do not know how to interpreted them. Is there any documentation on that ?

**Comment by kr-stn** [comment]
This question is entirely too broad in the way it is written and also out of scope of this repository.

I suggest to go take a look at https://gis.stackexchange.com/tour or other sources that can help with more general questions like yours.

**Comment by AgentNemo00** [comment]
I do not understand why the question is to broad. I get An zip file with a lot of nc files in and want to convert it to an image. I just wanted to ask if there is some documentation on that so I do not need to reserve engineer the python code.

**Comment by AgentNemo00** [comment]
> This question is entirely too broad in the way it is written and also out of scope of this repository.
> 
> I suggest to go take a look at https://gis.stackexchange.com/tour or other sources that can help with more general questions like yours.


I do not understand why the question is to broad. I get An zip file with a lot of nc files in and want to convert it to an image. I just wanted to ask if there is some documentation on that so I do not need to reserve engineer the python code.

**Comment by j08lue** [comment]
How to get from data to visualization depends on what kind of product (platform, sensor, level, parameter) you are interested in. Chances are the data needs more processing before you can make meaningful plots. [SNAP](https://step.esa.int/main/toolboxes/snap/) is ESA's standard tool for processing and plotting.

On the note of the file format - a very nice library for loading and plotting data from NetCDF (nc) files is [Xarray](https://docs.xarray.dev/).

But @kr-stn is right - more support for working with the products is beyond the scope of our project here. 😄 Good luck!
