### ISSUE TITLE
Decreasing results with larger footprint - paging issue?

### ISSUE THREAD

**Issue by jmettes** [sentinelsat/sentinelsat#588]
I'm getting this unexpected behaviour where the bigger I make the bounding box the less results I get.

```python
>>> east, west, south, north = -10, 180, -90, -60
>>> footprint = f"POLYGON (({east} {north}, {east} {south}, {west} {south}, {west} {north}, {east} {north}))"
>>> results = api.query(footprint,
                      date=(date(2020, 1, 1), date(2020, 12, 31)),
                      producttype='GRD',
                      platformname="Sentinel-1")
Querying products: 100% 23836/23836 [05:19<00:00, 75.78product/s]
>>> print(len(results))
23836
```
I'd assume the bigger the footprint, the more results I get, but instead it reduces the number of results

```python
>>> east, west, south, north = -30, 180, -90, -60
>>> footprint = f"POLYGON (({east} {north}, {east} {south}, {west} {south}, {west} {north}, {east} {north}))"
>>> results = api.query(footprint,
                      date=(date(2020, 1, 1), date(2020, 12, 31)),
                      producttype='GRD',
                      platformname="Sentinel-1")
Querying products: 100% 20958/20958 [03:51<00:00, 84.35product/s]
>>> print(len(results))
20958
```

The results progressively decrease with each degree I add to the eastern bounds

```python
>>> east, west, south, north = -180, 180, -90, -60
>>> footprint = f"POLYGON (({east} {north}, {east} {south}, {west} {south}, {west} {north}, {east} {north}))"
>>> results = api.query(footprint,
                      date=(date(2020, 1, 1), date(2020, 12, 31)),
                      producttype='GRD',
                      platformname="Sentinel-1")
Querying products: 100% 1860/1860 [00:17<00:00, 111.73product/s]
>>> print(len(results))
1860
```

The [API docs](https://scihub.copernicus.eu/twiki/do/view/SciHubUserGuide/OpenSearchAPI#Discover_the_products_over_a_pre) mention:

> The maximum footprint extent possible is defined by the Mercator projection used on DHuS, i.e. LAT [-180, + 180] and LONG [-85.05, +85.05].

So in theory I should be able to query that amount. I'm suspecting maybe it's a paging thing going on behind the scenes?

Notebook describing the issue in more detail: https://nbviewer.org/gist/jmettes/d180891df997a21723c291616d8a5258

**Comment by valgur** [comment]
Related: #570
Spatial queries that span the whole globe don't really work that well with how the queries are implemented on the server. 

Use `ENVELOPE(-180, 180, 90, -90)` instead of polygons for box-shaped footprints, especially for ones with extreme extents. Also, you can make use of `api.count()` in the above queries (which also helps rules out any effects from paging).

With `ENVELOPE` the above queries return:
| Southern limit | Count   |
|----------------|---------|
| -10            | 238,102 |
| -30            | 258,603 |
| -180           | 385,845 |
