### ISSUE TITLE
ServerError: 504 Gateway Time-out when downloading a product

### ISSUE THREAD

**Issue by sparkvilla** [sentinelsat/sentinelsat#590]
Hi. I am using the sentinelsat API to query and download a sentinel2 tile. Tile name = `T20MLC`, product id=`be174d1c-cd0a-44e6-97c9-992981f5c345`. I can use the sentinelsat to query the tile by using:

     name = "T20MLC"
     products = api.query(filename=f'*_{name}_*',
             date=date,
             platformname='Sentinel-2',
             processingLevel=f'Level-{level}',
             cloudcoverpercentage=cc)

This returns the different products correctly. I then select the id I would like to download: `be174d1c-cd0a-44e6-97c9-992981f5c345`
When downloading the tile with:

    products = api.download("be174d1c-cd0a-44e6-97c9-992981f5c345", outdirpath)

I get:

sentinelsat.exceptions.ServerError: HTTP status 504 Gateway Time-out:
# 504 Gateway Time-out

What is the problem?

**Comment by j08lue** [comment]
500-codes indicate server errors, so please contact [SciHub support](mailto:eosupport@copernicus.esa.int).

To help them debug, perhaps try to download the same product via https://scihub.copernicus.eu/ and see whether you get the same error there.

**Comment by sparkvilla** [comment]
@j08lue  Thank you for your replay. I am trying to send an email to the scihub support but it gives me invalid email address..

**Comment by j08lue** [comment]
I have not tried in a while - eosupport@copernicus.esa.int used to work. 🤷 Please share here if you find a way to contact them.

**Comment by sparkvilla** [comment]
@j08lue  Unfortunately that doesn't work either..
