### ISSUE TITLE
Problem downloading Sentinel-3 LST data

### ISSUE THREAD

**Issue by MartinaFrezza** [sentinelsat/sentinelsat#602]
Hello everyone,
I have a problem downloading Sentinel-3 Land Surface Temperature products.
This is the script I use:
![image](https://github.com/sentinelsat/sentinelsat/assets/137999073/dfab34d8-dba8-4ee4-8bc2-ffc9e41cb0ce)
![image](https://github.com/sentinelsat/sentinelsat/assets/137999073/7e941e86-9486-40dc-b3c2-b0c64693299c)

The script works correctly, and this is what I get:
![image](https://github.com/sentinelsat/sentinelsat/assets/137999073/a025967a-188b-4ce6-96b7-93f32b9bfeb0)
Number of LST-Sentinel-3 products: 0

So, the products I wanted download seems not be available (on the website they are available instead)
My question is: Anyone knows how to get Sentinel-3 SLSTR products via APIs? (LST and I am also looking for WST products)…
Thanks to everyone :slight_smile:

**Comment by j08lue** [comment]
Copernicus Open Access Hub / SciHub is gradually reducing their offering until shut-down of the service. Maybe they already discontinued / removed S3 SLSTR?

The new default source for S3 data would be the Copernicus Data Space Ecosystem: https://dataspace.copernicus.eu/explore-data/data-collections/sentinel-data/sentinel-3

But other platforms have it, too, like EuroDataCube https://collections.eurodatacube.com/sentinel-3-l1b-slstr/ or Microsoft Planetary Computer https://planetarycomputer.microsoft.com/dataset/sentinel-3-slstr-lst-l2-netcdf.
