### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by arind123** [sentinelsat/sentinelsat#603]
Hi Team, I have been an avid user of your package .
As per news announced by Copernicus [https://scihub.copernicus.eu/news/News01189] they are asking you to use the new interface from the Copernicus Data Access Ecosystem to get the full Sentinel-2 data offer, available at [https://dataspace.copernicus.eu]. And For what concerns the Copernicus Data Space Ecosystem  will replace the actual Copernicus Open Access Hub.

So do you guys have any plans to release newer versions of your package to incorporate these changes?

**Comment by valgur** [comment]
Hi, @arind123! There's an ongoing discussion at #583 on this topic. See that issue for the current status and to discuss any possible solutions.
