### ISSUE TITLE
Package Needs Update as Copernicus Open Access Hub is closing at the end of October 2023 and moving to dataspace.copernicus.eu  

### ISSUE THREAD

**Issue by saqibzia-dev** [sentinelsat/sentinelsat#604]
Hello ,
I have attached the image below which states that "Copernicus Open Access Hub is closing at the end of October 2023. Copernicus Sentinel Data Access is now fully available in the Copernicus Data Space Ecosystem. As previously announced in [January](https://scihub.copernicus.eu/news/News01146) the Copernicus Open Access Hub service continued its full operations until the end of June 2023, followed up by a gradual ramp-down phase until September 2023. The Copernicus Open Access Hub will be exceptionally extended for another month and will cease operations at the end of October 2023. To continue accessing Copernicus Sentinel data users will need to [self-register](https://documentation.dataspace.copernicus.eu/Registration.html) on the new [Copernicus Data Space Ecosystem](https://dataspace.copernicus.eu/). A guide for migration is available [here](https://dataspace.copernicus.eu/news/2023-7-13-accessing-sentinel-mission-data-new-copernicus-data-space-ecosystem-apis)."

The new service offers access to a wide range of Earth observation data and services as well as new [tools](https://dataspace.copernicus.eu/analyse), [GUI](https://dataspace.copernicus.eu/browser/) and [APIs](https://documentation.dataspace.copernicus.eu/APIs.html) to help users explore and analyse satellite imagery. Discover more about the Copernicus Data Space Ecosystem at https://dataspace.copernicus.eu/".
**Will you upgrade this package accordingly?**
![Untitled](https://github.com/sentinelsat/sentinelsat/assets/56071934/9dd67e13-a3e0-428f-b112-7b67627af86b)

**Comment by j08lue** [comment]
Please refer to this thread: 

- https://github.com/sentinelsat/sentinelsat/issues/583#issuecomment-1749738269

The gist: the Sentinelsat for SciHub maintainers are not currently working on an effort to turn Sentinelsat into a CDSE client library, but others might take over.
