### ISSUE TITLE
sentinelsat API access issue

### ISSUE THREAD

**Issue by Abbas47** [sentinelsat/sentinelsat#606]
sentinelsat API is not been access through the old URL: https://scihub.copernicus.eu/dhus because now Copernicus data can be access through new URL: https://dataspace.copernicus.eu.
Does someone know how to access sentinelsatAPI using new URL?

**Comment by j08lue** [comment]
Pls see https://github.com/sentinelsat/sentinelsat/issues/583#issuecomment-1405131851
