### ISSUE TITLE
ConnectTimeout Error of SentinelAPI query

### ISSUE THREAD

**Issue by yoseyo** [sentinelsat/sentinelsat#615]
Hi!

I have the following error after running the code below, tho I haven't run it more than twice:

> ConnectTimeout: HTTPSConnectionPool(host='apihub.copernicus.eu', port=443): Max retries exceeded with url: /apihub/search?format=json&rows=100&start=0&q=beginPosition%3A%5B%222019-02-25T00%3A00%3A00Z%22+TO+%222019-02-27T00%3A00%3A00Z%22%5D+cloudcoverpercentage%3A%5B%220%22+TO+%2220%22%5D+platformname%3A%22Sentinel-2%22+processinglevel%3A%22Level-2A%22+footprint%3A%22Intersects%28GEOMETRYCOLLECTION%28POLYGON%28%28-1.5905+50.7739%2C-1.5819+50.5371%2C-1.0038+50.5353%2C-1.0104+50.7757%2C-1.5905+50.7739%29%29%29%29%22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16b10cce0>, 'Connection to apihub.copernicus.eu timed out. (connect timeout=None)'))

```
api = SentinelAPI(user, password, 'https://apihub.copernicus.eu/apihub/')

footprint = geojson_to_wkt(read_geojson(boundsdata))

print (footprint)

products = api.query(footprint,
                     date = ('20190225', '20190227'),
                     platformname = 'Sentinel-2',
                     processinglevel = 'Level-2A',
                     cloudcoverpercentage = (0, 20))

```

Can you please help me to find out the issue?

Thanks in advance!

**Comment by yoseyo** [comment]
I have just read that "Sentinelsat is currently not functional for downloading from the CDSE."

**Comment by drashti-amin** [comment]
Hi, 
I also get a similar error as of Feb 5, 2025. Could anyone please help me with this?
Thank you!

**Comment by maxsivertsen** [comment]
Hi,

I have the same error. I am following the exact code as given in the documentation. Obviously with my own user/pw

Thanks!
