### ISSUE TITLE
Question about md5 checksum

### ISSUE THREAD

**Issue by melchisedech** [sentinelsat/sentinelsat#88]
Hi all,
I have a problem with checksum control with sentinel sat.
Download is ok, but at the end of the process, there is an error with checksum control. I can't write the corrupt_scenes.txt:

Traceback (most recent call last):
  File "/home/geouser/anaconda2/bin/sentinel", line 11, in <module>
    sys.exit(cli())
  File "/home/geouser/anaconda2/lib/python2.7/site-packages/click/core.py", line 716, in __c                                   all__
    return self.main(*args, **kwargs)
  File "/home/geouser/anaconda2/lib/python2.7/site-packages/click/core.py", line 696, in mai                                   n
    rv = self.invoke(ctx)
  File "/home/geouser/anaconda2/lib/python2.7/site-packages/click/core.py", line 1060, in in                                   voke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geouser/anaconda2/lib/python2.7/site-packages/click/core.py", line 889, in inv                                   oke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geouser/anaconda2/lib/python2.7/site-packages/click/core.py", line 534, in inv                                   oke
    return callback(*args, **kwargs)
  File "/home/geouser/anaconda2/lib/python2.7/site-packages/sentinelsat/scripts/cli.py", lin                                   e 95, in search
    with open(os.path.join(path, "corrupt_scenes.txt"), "w") as outfile:
IOError: [Errno 20] Not a directory: u'/home/geouser/SENTINELSAT/DWNLD/S2A_OPER_PRD_MSIL1C_P                                   DMC_20160928T010718_R044_V20160927T233112_20160927T233110.zip/corrupt_scenes.txt'
geouser@ubuntu:~/anaconda2/bin$

Anyone have an idea ?
( i am sorry if it's not the correct canal for this question)

**Comment by j08lue** [comment]
It seems like your `--path` argument points to a `.zip` file. It should be a directory.

Try again with `--path /home/geouser/SENTINELSAT/DWNLD`.

**Comment by melchisedech** [comment]
Thank you for your help j08lue,
 i should have start with my command line (user and password have been changed):

sentinel search -s 20160927 -e 20160928 -p "/home/geouser/SENTINELSAT/DWNLD" --sentinel2 --md5 -c 20 -u "https://scihub.copernicus.eu/dhus" "username" "password" "/home/geouser/SENTINELSAT/GeoJSon/NC-ALL.geojson"

My path seems to be good... and i think the script would write on a tile.zip...
Thank you for your help

**Comment by Fernerkundung** [comment]
This might be related to conflicting name-space in [cli.py L95](https://github.com/ibamacsr/sentinelsat/blob/master/sentinelsat/scripts/cli.py#L95). Where `path` in the scope of the list comprehension means "path of product to write (ending with .zip") and outside of it means "directory path".

```python
            corrupt_scenes = [(path, info["id"]) for path, info in result.items() if info is not None]
            if len(corrupt_scenes) > 0:
                with open(os.path.join(path, "corrupt_scenes.txt"), "w") as outfile:
                    for corrupt_tuple in corrupt_scenes:
                        outfile.write("%s : %s\n" % corrupt_tuple)
```

**Comment by melchisedech** [comment]
Any idea to correct this problem ?
thanks

**Comment by valgur** [comment]
Fernerkundung is right, the `path` variable is being unintentionally overwritten in the list comprehension. You could fix that by changing `(path, info["id"])` to `(product_path, info["id"])`, for example.

Overall, the code for generating the corrupt scenes list is a ugly mess right now. I wrote the current version and I seriously tested it for the first time just now. It does not really appear to work at all, ugh. It needs rewriting and some proper unit tests. I'll see what I can do.

**Comment by melchisedech** [comment]
I have done that, but there is still an error:

Traceback (most recent call last):ââ         | 559M/1.05G [00:01<00:01, 361MB/s]
  File "/home/geouser/anaconda2/bin/sentinel", line 11, in <module>:01, 368MB/s]
    sys.exit(cli()) 7%|ââ                   | 39.7M/1.05G [00:00<00:02, 397MB/s]
  File "/home/geouser/anaconda2/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/geouser/anaconda2/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/geouser/anaconda2/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geouser/anaconda2/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geouser/anaconda2/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/geouser/anaconda2/lib/python2.7/site-packages/sentinelsat/scripts/cli.py", line 105, in search
    corrupt_scenes = [(product_path, info["id"]) for path, info in result.items() if info is not None]
NameError: global name 'product_path' is not defined

Any idea ?
Thanks for your feedback

**Comment by Fernerkundung** [comment]
@melchisedech I think @valgur meant something like this:

```
corrupt_scenes = [(product_path, info["id"]) for product_path, info in result.items() if info is not None]
if len(corrupt_scenes) > 0:
   with open(os.path.join(path, "corrupt_scenes.txt"), "w") as outfile:
      for corrupt_tuple in corrupt_scenes:
      outfile.write("%s : %s\n" % corrupt_tuple)
```

**Comment by melchisedech** [comment]
Thank you for your help Fernerkundung, it works well !
I have another questions, the output consist in a txt file named corrupt_scenes.txt like that:
/media/HDD/S1/2015/S1A_IW_GRDH_1SDV_20150501T182244_20150501T182302_005731_0075BC_8DD6.zip : c5a5c6f0-37bf-48ae-978c-8e6096d12b67
/media/HDD/S1/2015/S1A_IW_GRDH_1SDV_20151114T183028_20151114T183058_008604_00C360_4DAB.zip : d1b7eee4-e190-403e-af68-8b4aad5f5c19
/media/HDD/S1/2015/S1A_IW_GRDH_1SDV_20150508T072017_20150508T072046_005826_0077EE_2480.zip : 2e910887-8489-49c8-837f-fad7b39aafda

All these files are corrupted ? (its 'all the downloaded files)

**Comment by Fernerkundung** [comment]
That would indeed mean that all your files are corrupt? Can you open the ZIP archives? A broken archive can usually not be opened - if you can indeed open them and the images look OK our implementation of the checksum might be broken.

**Comment by melchisedech** [comment]
Everything seems to be ok with my product scene ... (i don't test them all, i have already downloaded 635 products...).

**Comment by Fernerkundung** [comment]
If your products are OK I would ignore the output of the MD5 check. It looks like we have a bug in there somewhere that we need to work out.

**Comment by melchisedech** [comment]
Thank you very much Fernerkundung for your help,
i will work on it and i will do a report.
