### ISSUE TITLE
add support for netrc file

### ISSUE THREAD

**Issue by lucadelu** [sentinelsat/sentinelsat#90]
Hi,

do you think [netrc file](https://docs.python.org/2/library/netrc.html) support could be useful? 
(I think yes so we don't need to pass user and specially password in the command line)

I started to implement it in netrc branc 52ee682

**Comment by Fernerkundung** [comment]
I don't think this is a good idea, unless we can automatically determine different netrc files for different API endpoints.

For instance:
- `dhus` and `apihub` can be used with the same user:password (after an undetermined syncing period)
- the [S-3 PreOpsHub](https://scihub.copernicus.eu/s3/) uses s3guest:s3guest
- all the [national mirrors](https://github.com/Fernerkundung/awesome-sentinel#data-hubs-and-national-mirrors) require their own user:password combination

The returns of the netrc files start to diminish fast, if we want to keep `sentinelsat` as flexible as possible for all API endpoints.

What I would favour is a way to provide the password in a hashed/encrypted format, for instance when you want to use `sentinelsat` on a machine multiple people can access and you don't want your password to be plainly visible. Although I don't think that would be technically possible - unless we go down the rabbit hole of cookie/session storing?

**Comment by valgur** [comment]
Both [`requests`](http://docs.python-requests.org/en/master/user/authentication/#netrc-authentication) and [`pycurl`](http://www.programcreek.com/python/example/53121/pycurl.NETRC) appear to support netrc files out of the box, surprisingly enough. It might even require relatively little additional code to get netrc support in sentinelsat, but automatically testing it is going to be painful.

Try and see if you can get the automatic support in `requests` and `homura`/`pycurl` working. Setting the auth to `None` should be sufficient for `requests`. For homura you should try adding `kwargs[pycurl.NETRC] = 1` to `api.download()`. I'm actually kind of curious to see how well this will work.

**Comment by lucadelu** [comment]
@Fernerkundung yes it is possible (and already implemented) to  have different API endpoints in only one netrc file, this is mine for example

```
machine urs.earthdata.nasa.gov
login USERNASA
password PASSWDNASA

machine e4ftl01.cr.usgs.gov 
login USERNASA
password PASSWDNASA

machine https://scihub.copernicus.eu/apihub/
login USERHUB 
password PASSWDHUB
```
@valgur ok I will try in the next days

**Comment by Fernerkundung** [comment]
@lucadelu I never knew - in that case it sounds like a good idea to use the netrc file if the API endpoint is included ad user:password are `None`.

**Comment by lucadelu** [comment]
@valgur I tried to set auth to `None` but it didn't work

```
SentinelAPIError: (HTTP status: 401, code: None) 
# HTTP Status 401 - Full authentication is required to access this resource

**type** Status report

**message** _Full authentication is required to access this resource_

**description** _This request requires HTTP authentication._

* * *
```

so I moved the function to read the netrc into `sentinel.py` and I also added a test in `test_mod.py`. Probably it is not the best implementation but at least it work and it is just few lines of code to maintain.

Let me know, what do you think

**Comment by valgur** [comment]
@j08lue Can this issue be closed?

**Comment by j08lue** [comment]
yes. :-)
