### ISSUE TITLE
libcurl link-time version (7.51.0) is older than compile-time version (7.52.1)

### ISSUE THREAD

**Issue by unnic** [sentinelsat/sentinelsat#98]
Hello,

I tried again to get sentinelsat to work with a complete reinstallation after the last [issue](https://github.com/ibamacsr/sentinelsat/issues/89)

If I run a command like `sentinel search --sentinel2 -s 20170115 user pwd aoi.json -d` I get the error:
`ImportError: pycurl: libcurl link-time version (7.51.0) is older than compile-time version (7.52.1)`

I tried `pip install libcurl --upgrade`

which resulted in:

`Could not find a version that satisfies the requirement libcurl (from versions: )
No matching distribution found for libcurl`

Windows 10
Python 2.7.13 (installed through Anaconda because of sen2cor)

**Comment by Fernerkundung** [comment]
Can you post the output of `conda env export -n <your-environment`?

It is very likely just an issue with the packaged (py)curl version in your environment. You could try to install pycurl from another channel, i.e. `conda install pycurl -c conda-forge`. Not really a `sentinelsat` issue but some curl dependency mismatch in your anaconda environment.

**Comment by unnic** [comment]
`conda env export -n <your-environment>`

```
name: root
channels: !!python/tuple
- !!python/unicode
  'rios'
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'defaults'
dependencies:
- _license=1.1=py27_1
- alabaster=0.7.9=py27_0
- anaconda-client=1.6.0=py27_0
- anaconda=custom=py27_0
- anaconda-navigator=1.4.3=py27_0
- argcomplete=1.0.0=py27_1
- astroid=1.4.9=py27_0
- astropy=1.3=np111py27_0
- babel=2.3.4=py27_0
- backports=1.0=py27_0
- backports_abc=0.5=py27_0
- beautifulsoup4=4.5.3=py27_0
- bitarray=0.8.1=py27_1
- blaze=0.10.1=py27_0
- bokeh=0.12.4=py27_0
- boto=2.45.0=py27_0
- bottleneck=1.2.0=np111py27_0
- bzip2=1.0.6=vc9_3
- cdecimal=2.3=py27_2
- cffi=1.9.1=py27_0
- chardet=2.3.0=py27_0
- chest=0.2.3=py27_0
- click=6.7=py27_0
- cloudpickle=0.2.2=py27_0
- clyent=1.2.2=py27_0
- colorama=0.3.7=py27_0
- comtypes=1.1.2=py27_0
- conda-forge::conda=4.2.13=py27_0
- conda-forge::conda-env=2.6.0=0
- conda-forge::expat=2.1.0=vc9_2
- conda-forge::freexl=1.0.2=vc9_1
- conda-forge::gdal=2.1.3=np111py27_vc9_1
- conda-forge::geos=3.5.1=vc9_1
- conda-forge::h5py=2.6.0=np111py27_7
- conda-forge::hdf4=4.2.12=vc9_0
- conda-forge::hdf5=1.8.17=vc9_9
- conda-forge::kealib=1.4.6=vc9_3
- conda-forge::libiconv=1.14=vc9_4
- conda-forge::libnetcdf=4.4.1.1=vc9_2
- conda-forge::libpng=1.6.28=vc9_0
- conda-forge::libpq=9.5.4=vc9_3
- conda-forge::libspatialite=4.3.0a=vc9_14
- conda-forge::libxml2=2.9.4=vc9_4
- conda-forge::openjpeg=2.1.2=vc9_2
- conda-forge::pcre=8.39=vc9_0
- conda-forge::proj4=4.9.3=vc9_2
- conda-forge::pytables=3.3.0=np111py27_0
- conda-forge::sqlite=3.13.0=vc9_1
- conda-forge::vc=9=0
- conda-forge::xerces-c=3.1.4=vc9_3
- configobj=5.0.6=py27_0
- configparser=3.5.0=py27_0
- console_shortcut=0.1.1=py27_1
- contextlib2=0.5.4=py27_0
- cryptography=1.7.1=py27_0
- curl=7.52.1=vc9_0
- cycler=0.10.0=py27_0
- cython=0.25.2=py27_0
- cytoolz=0.8.2=py27_0
- dask=0.13.0=py27_0
- datashape=0.5.4=py27_0
- decorator=4.0.11=py27_0
- dill=0.2.5=py27_0
- docutils=0.13.1=py27_0
- entrypoints=0.2.2=py27_0
- enum34=1.1.6=py27_0
- et_xmlfile=1.0.1=py27_0
- fastcache=1.0.2=py27_1
- flask=0.12=py27_0
- flask-cors=3.0.2=py27_0
- freetype=2.5.5=vc9_2
- funcsigs=1.0.2=py27_0
- functools32=3.2.3.2=py27_0
- futures=3.0.5=py27_0
- get_terminal_size=1.0.0=py27_0
- gevent=1.2.1=py27_0
- greenlet=0.4.11=py27_0
- grin=1.2.1=py27_3
- heapdict=1.0.0=py27_1
- icu=57.1=vc9_0
- idna=2.2=py27_0
- imagesize=0.7.1=py27_0
- ipaddress=1.0.18=py27_0
- ipykernel=4.5.2=py27_0
- ipython=5.1.0=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=5.2.2=py27_1
- isort=4.2.5=py27_0
- itsdangerous=0.24=py27_0
- jdcal=1.3=py27_0
- jedi=0.9.0=py27_1
- jinja2=2.9.4=py27_0
- jpeg=9b=vc9_0
- jsonschema=2.5.1=py27_0
- jupyter=1.0.0=py27_3
- jupyter_client=4.4.0=py27_0
- jupyter_console=5.0.0=py27_0
- jupyter_core=4.2.1=py27_0
- lazy-object-proxy=1.2.2=py27_0
- libgdal=2.0.0=vc9_1
- libtiff=4.0.6=vc9_3
- llvmlite=0.15.0=py27_0
- locket=0.2.0=py27_1
- lxml=3.7.2=py27_0
- markupsafe=0.23=py27_2
- matplotlib=2.0.0=np111py27_0
- menuinst=1.4.4=py27_0
- mistune=0.7.3=py27_0
- mkl=2017.0.1=0
- mkl-service=1.1.2=py27_3
- mpmath=0.19=py27_1
- multipledispatch=0.4.9=py27_0
- nbconvert=4.2.0=py27_0
- nbformat=4.2.0=py27_0
- networkx=1.11=py27_0
- nltk=3.2.2=py27_0
- nose=1.3.7=py27_1
- notebook=4.3.1=py27_1
- numba=0.30.1=np111py27_0
- numexpr=2.6.1=np111py27_2
- numpy=1.11.3=py27_0
- numpydoc=0.6.0=py27_0
- odo=0.5.0=py27_1
- openpyxl=2.4.1=py27_0
- openssl=1.0.2k=vc9_0
- pandas=0.19.2=np111py27_1
- partd=0.3.7=py27_0
- path.py=10.0=py27_0
- pathlib2=2.2.0=py27_0
- patsy=0.4.1=py27_0
- pep8=1.7.0=py27_0
- pickleshare=0.7.4=py27_0
- pillow=4.0.0=py27_0
- pip=9.0.1=py27_1
- ply=3.9=py27_0
- prompt_toolkit=1.0.9=py27_0
- psutil=5.0.1=py27_0
- py=1.4.32=py27_0
- pyasn1=0.1.9=py27_0
- pycosat=0.6.1=py27_1
- pycparser=2.17=py27_0
- pycrypto=2.6.1=py27_5
- pycurl=7.43.0=py27_2
- pyflakes=1.5.0=py27_0
- pygments=2.1.3=py27_0
- pylint=1.6.4=py27_1
- pyopenssl=16.2.0=py27_0
- pyparsing=2.1.4=py27_0
- pyqt=5.6.0=py27_2
- pytest=3.0.5=py27_0
- python=2.7.13=0
- python-dateutil=2.6.0=py27_0
- pytz=2016.10=py27_0
- pywin32=220=py27_2
- pyyaml=3.12=py27_0
- pyzmq=16.0.2=py27_0
- qt=5.6.2=vc9_3
- qtawesome=0.4.3=py27_0
- qtconsole=4.2.1=py27_2
- qtpy=1.2.1=py27_0
- requests=2.12.4=py27_0
- rope=0.9.4=py27_1
- ruamel_yaml=0.11.14=py27_1
- scandir=1.4=py27_0
- scikit-image=0.12.3=np111py27_1
- scikit-learn=0.18.1=np111py27_1
- scipy=0.18.1=np111py27_1
- seaborn=0.7.1=py27_0
- setuptools=27.2.0=py27_1
- simplegeneric=0.8.1=py27_1
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- snowballstemmer=1.2.1=py27_0
- sockjs-tornado=1.0.3=py27_0
- sphinx=1.5.1=py27_0
- spyder=3.1.2=py27_0
- sqlalchemy=1.1.5=py27_0
- ssl_match_hostname=3.4.0.2=py27_1
- statsmodels=0.6.1=np111py27_1
- subprocess32=3.2.7=py27_0
- sympy=1.0=py27_0
- tk=8.5.18=vc9_0
- toolz=0.8.2=py27_0
- tornado=4.4.2=py27_0
- traitlets=4.3.1=py27_0
- unicodecsv=0.14.1=py27_0
- vs2008_runtime=9.00.30729.5054=0
- wcwidth=0.1.7=py27_0
- werkzeug=0.11.15=py27_0
- wheel=0.29.0=py27_0
- widgetsnbextension=1.2.6=py27_0
- win_unicode_console=0.5=py27_0
- wrapt=1.10.8=py27_0
- xlrd=1.0.0=py27_0
- xlsxwriter=0.9.6=py27_0
- xlwings=0.10.2=py27_0
- xlwt=1.2.0=py27_0
- zlib=1.2.8=vc9_3
- pip:
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - certifi==2017.1.23
  - et-xmlfile==1.0.1
  - geojson==1.3.4
  - glymur==0.8.6
  - homura==0.1.5
  - html2text==2016.9.19
  - humanize==0.5.1
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.1
  - mock==2.0.0
  - pbr==1.10.0
  - prompt-toolkit==1.0.9
  - sen2cor==2.3.1
  - sentinelsat==0.8.1
  - tables==3.3.0
  - tqdm==4.11.2
  - win-unicode-console==0.5
```

**Comment by Fernerkundung** [comment]
Does `conda update -f curl pycurl` help? It looks like `pycurl=7.43.0` depends on `curl=7.51.0` but you have `curl=7.52.1` installed. 

Again, this is not a sentinelsat issue but completely conda/pycurl dependent.

**Comment by unnic** [comment]
No,  same error. The `conda env` output is changed to to `- conda-forge::curl=7.52.1=vc9_0`

**Comment by benmack** [comment]
I ran in the same problem when I tried to setup sen2cor and sentinelsat with Python 2.7.13 and Anaconda on Windows 10.

A simple solution is to download pycurl from Gohlke (http://www.lfd.uci.edu/~gohlke/pythonlibs/#pycurl), conda uninstall pycurl, reinstall the Gohlke wheel and try again (for me it worked):

	C:\Users\ben\Downloads>python
	Python 2.7.13 |Anaconda 4.3.1 (64-bit)| (default, Dec 19 2016, 13:29:36) [MSC v.1500 64 bit (AMD64)] on win32
	Type "help", "copyright", "credits" or "license" for more information.
	Anaconda is brought to you by Continuum Analytics.
	Please check out: http://continuum.io/thanks and https://anaconda.org
	>>> import pycurl
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	ImportError: pycurl: libcurl link-time version (7.39.1-DEV) is older than compile-time version (7.52.1)
	>>> exit()

        C:\Users\ben\Downloads>conda uninstall pycurl
	Fetching package metadata .............
	Solving package specifications: .

	Package plan for package removal in environment D:\Programme\Anaconda2:

	The following packages will be REMOVED:

		anaconda: 4.3.1-np111py27_0
		pycurl:   7.43.0-py27_2

	Proceed ([y]/n)? y


	C:\Users\ben\Downloads>pip install pycurl-7.43.0-cp27-cp27m-win_amd64.whl
	Processing c:\users\ben\downloads\pycurl-7.43.0-cp27-cp27m-win_amd64.whl
	Installing collected packages: pycurl
	Successfully installed pycurl-7.43.0

	C:\Users\ben\Downloads>python
	Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 19 2016, 13:29:36) [MSC v.1500 64 bit (AMD64)] on win32
	Type "help", "copyright", "credits" or "license" for more information.
	Anaconda is brought to you by Continuum Analytics.
	Please check out: http://continuum.io/thanks and https://anaconda.org
	>>> import pycurl
	>>>

**Comment by j08lue** [comment]
@benmack and @unnic, we just merged @valgur's PR #117 which gets rid of the `pycurl` dependency altogether.

It is not on PyPI yet, but you can update from this repository. That should resolve all your `curl` trouble.

Please let us know if this issue can be closed now.

**Comment by Fernerkundung** [comment]
This should be solved with the `v0.11` release, which removes the `curl` dependency. Should you for some reason depend on the version using curl please comment and we can reopen this issue.

**Comment by jmpark1115** [comment]
After I uninstall pycurl, I install pycurl again.   I solve the problem.   Environment is Window and Anaconda.

**Comment by Fernerkundung** [comment]
@jmpark1115 please note that (py)curl is not a dependency of sentinelsat anymore as all downloads are handled by the `requests` package. You might want to consider updating your sentinelsat installation.

**Comment by geocarvalho** [comment]
For Ubuntu 18.04
`conda install pycurl`
